import { SongT } from "@/types/song";

export const kiJingrwaiIaKiSamla: SongT[] = [
  {
    id: "song-620",
    title: "Ka Jingduwai ïa ka bor U Blei",
    metadata: {
      number: 620,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "S.S. 718",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ah Trai Jisu, sha Me ngi phai,`,
          `Kum ki samla, ngi tlot, ngi swai;`,
          `Jingim jong ngi to nang pynshai,`,
          `Ban long jong Me, (3)`,
          `Jingim jong ngi to nang pynshai,`,
          `Ban long jong Me.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Їalam ïa ngi, Ah Trai babha,`,
          `Ha lynti dum ba dap jingma;`,
          `Tang ha Me ai ngin shem sngewbha,`,
          `Ban bud ïa Me, (3)`,
          `Tang ha me ai ngin shem sngewbha,`,
          `Ban bud ïa Me.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `To ai ngin sngew ka Ktien jong Me,`,
          `Ban shan ïa ngi ha ki jingeh;`,
          `Sha Me, Ah Trai, ngi phet ban rieh,`,
          `To da ïa ngi, (3)`,
          `Sha Me, Ah Trai, ngi phet ban rieh,`,
          `To da ïa ngi.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Jingim jong ngi, Trai to pynbeit,`,
          `Ai ba ngin im da ka jingngeit;`,
          `Tang sha Me, ai ba ngin ïai peit,`,
          `Man la ka sngi, (3)`,
          `Tang sha Me, ai ba ngin ïai peit,`,
          `Man la ka sngi.`,
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          `Ai bor, Trai, ïa ngi ki Samla,`,
          `Na ki jingpynshoi ruh to da;`,
          `Lam ïa ngi sha kjat ka diengphna,`,
          `Ba ngin ïoh im, (3)`,
          `Lam ïa ngi sha kjat ka diengphna,`,
          `Ba ngin ïoh im.`,
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          `Phah, Ah Trai, l'U Mynsiem ban trei,`,
          `Їa Me ban pynpaw ha pyrthei;`,
          `Soh U Mynsiem, to ai ngin sei,`,
          `Pynkhuid ïa ngi, (3)`,
          `Soh U Mynsiem to ai ngin sei,`,
          `Pynkhuid ïa ngi.`,
        ],
      },
    ],
  },
  {
    id: "song-621",
    title: "Y Milwr Bychan",
    metadata: {
      number: 621,
      language: "khasi",
      composer: "G.A.J.",
      syllables: "76.76.D. & REFRAIN",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Nga kwah ban long u shipai,`,
          `Hapoh ka lama lieh,`,
          `Ngan kohnguh Syiem ï'U Jisu,`,
          `U Trai Uba ha khlieh,`,
          `Ngan shim ka jingkieng atiar,`,
          `Ba lah ban da ïa nga,`,
          `Ba ngan ïoh long shi-yrta,`,
          `U shipai uba bha.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Trai ba bha, to shong bad nga,`,
          `Katba rhem ka thyma;`,
          `Ynda wai ha ka ri jingshai,`,
          `Ngan shong ha la ka rta.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Ka rhem jur ka thma mynta,`,
          `U bymman u pynjot;`,
          `Ki sum ba meh ding jong u,`,
          `Ki thew sha nga ba tlot,`,
          `Ngan kieng ka stieh ka jingngeit,`,
          `Ka waitlam U Mynsiem,`,
          `Ka jingda khlieh bad shadem,`,
          `Ka hok bad jingpynim.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Katba ka nang jur ka thma,`,
          `To long ka jakarieh;`,
          `Ai bor ïa nga ban ïaineh,`,
          `Ban ïeng ruh khlem da khih,`,
          `Te ynda kut ka jingleit,`,
          `Ka jingim ruh la wai,`,
          `Ngan ïoh shongthait shi junom,`,
          `Ha ri ka jingsuk jai.`,
        ],
      },
    ],
  },
  {
    id: "song-622",
    title: "Ki Samla U Khrist",
    metadata: {
      number: 622,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "Christian Worship No. 236, LONDONDERRY AIR",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Phi ki Samla ha U Khrist, to ïeng joit mynta,`,
          `Ka jingieit U Nongpynim ban pynbna;`,
          `Da jingaiei U siew ka ram halor diengphna,`,
          `Ba jingim bymjukut phin ïoh shisha,`,
          `Long kiba khlaiñ, bad ka jingbha U Trai to mad,`,
          `Ka bor U Mynsiem Bakhuid ruh to wad;`,
          `Їaineh skhem ha ka jingngeit bad ka jingduwai,`,
          `Ka kyrteng jong U ban ïalap khlem da tyngkai.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Phi ki Samla ha U Khrist, to ïeng ban sakhi,`,
          `Ha pyrthei jied tang ïa U ban shakri;`,
          `Spah bad burom baroh ha ki to wat shaniah,`,
          `Ha jingsngewbha pyrthei wat pynbyrngia.`,
          `Sharai, duwai ba phin ym hap ha jingpynshoi,`,
          `Ban im namar U Jisu to pynkloi;`,
          `To peit sha U la jingïaleh bajur ki wan,`,
          `Jingjop bakhraw ïa phi Un ai, bad Un kyrshan.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Phi ki Samla ha U Khrist, to ïeng joit mynta,`,
          `To kup da jingsngewrit bad jingshisha;`,
          `Sngap, U Trai hi U ong, “Dei ban kha pat ïa phi,”`,
          `La jingim baroh ha U to aiti.`,
          `Їa ka Balang U Blei, mynta to ïeng ban tei,`,
          `Da jingsngew shitrhem bad jinglong kawei;`,
          `La phi la tlot bad ban khia da jingkhuslai,`,
          `To wan sha U, ka jingjahthait ïa phi Un ai.`,
        ],
      },
    ],
  },
  {
    id: "song-623",
    title: "Ka Kam ki Samla",
    metadata: {
      number: 623,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "S.S. 810",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `To ïeng, Samla, U Trai ïa ngi U khot sngewbha,`,
          `Їeng noh, mynta, to ngeit ka Ktien jong U;`,
          `To khie, pynbna, ka khubor jingpynim babha,`,
          `Їa lade, ai lut ban len namar U Jisu.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Shaphrang, to ngin nang ïaid,`,
          `Ka Kam U Trai jong ngi, ngin mih ban ïatrei,`,
          `Shaphrang, to ngin nang ïaid,`,
          `Hima jong U ban pynïar ha pyrthei;`,
          `Longshlur, wat sheptieng, b'U Trai U don hajan,`,
          `Kum shipai babha ngin tur ngin ym kynran;`,
          `La jingeh bunjait ngin shem,`,
          `Bad U Jisu ngin sngew skhem,`,
          `Їa ngi Un ai bor, ha jingtlot Un kyrshan.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Ka jingpyrta bajur ka wan na ri bajngai,`,
          `Pynkloi, mynta, ka Gospel ban ïalap;`,
          `Ki jaidbynriew ki dang ap ban ïoh ka jingshai,`,
          `Ki khun jingjynjar baroh, to ïeng ban ïarap.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Ki nongïaid wir baroh b'la jah na sem U Trai,`,
          `Na jingjot b'la hap, ïa ki ban pynphai;`,
          `Їeng joit, mynta, ka hukum jong U ban pyndep,`,
          `Ka bainong ngin ïoh ynda jingtrei ka la wai.`,
        ],
      },
    ],
  },
  {
    id: "song-624",
    title: "Namar U Khrist bad ka Balang",
    metadata: {
      number: 624,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "ALEX. III NO. 406",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Namar U Khrist bad ka Balang, to ngin ïaroh jam,`,
          `Da sur ba thymmai bad bathiang tam;`,
          `Ha ka bor ka jinglong samla, to ïeng ban ïatrei,`,
          `Burom U Trai ban pynpaw ha pyrthei.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Namar U Khrist hi,`,
          `Ngin ïeng ban sakhi;`,
          `Ha jinglong kawei ïa U ban shakri;`,
          `Namar ka Balang jong u,`,
          `Ngin trei ngin ym man thait shuh;`,
          `“Ah Trai, ma Me, ïa ngi to nang pynbit.”`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Namar U Khrist bad ka Balang, ka jingbha ngin wad,`,
          `Diengphna ngin bah, ban bud l'U Kynrad;`,
          `To ngin pyndem ïa lade ha ka bor U Mynsiem,`,
          `Ban ïai shakri ïa U katba dang im.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Namar U Khrist bad ka Balang ngin ai ïa lade,`,
          `Spah, ka por, ki sap, bad bor ruh de;`,
          `Ngin ai lut katba don na bynta U Trai jong ngi,`,
          `Da jingieit ngin ïeng, ïa U ban sakhi.`,
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          `Namar U Khrist bad ka Balang, ngin bret lut baroh,`,
          `Lynti pyrthei bad jingbrai ka doh;`,
          `To shim ka Ktien jong U, bad ïaineh ha jingduwai,`,
          `Ka bor ba ngin jop, ïa ngi hi Un ai.`,
        ],
      },
    ],
  },
  {
    id: "song-625",
    title: "To ïeng mynta phi ki Samla",
    metadata: {
      number: 625,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "S.S. 510",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Samla Khristan ki donkam ï'U Jisu,`,
          `Hapdeng ki erïong ba kyrhuh;`,
          `Kum ki pukni kin ïoh pynthymmai bor,`,
          `Ka kam ban trei khlem kheiñ ka dor.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `To ïeng mynta, phi ki Samla,`,
          `Jingieit U Blei kylleng ban leit rah;`,
          `To kup ka hok U Trai jong ngi,`,
          `Namar jong U khlem thait ngin trei.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Ki ïing jong ngi ki donkam ï'U Jisu,`,
          `Jingbha kin ïoh bad jingsuk ruh;`,
          `Ki jingkyrkhu ba dap kyrhai kin shem,`,
          `Jingshakri Blei ruh kin nang rhem.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Ki shnong jong ngi ki donkam ï'U Jisu,`,
          `Jingieit, jingshisha kim don shuh;`,
          `Ki jingsniew babun jaid ki la nangroi,`,
          `Jingshai Gospel ka dei ban poi.`,
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          `Ka ri jong ngi ka donkam ï'U Jisu,`,
          `Samla, to ïeng ban leit ïathuh;`,
          `Ki mynsiem b'la jot ngi dei ban ïarap,`,
          `Ka Ktien jingaiei ban ïalap.`,
        ],
      },
      {
        id: "verse-5",
        order: 6,
        type: "VERSE",
        lines: [
          `Ka pyrthei hi ka donkam ï'U Jisu,`,
          `Samla, to ïeng ban leit ïathuh;`,
          `Ki jaidbynriew, jingsuk shisha ki wad,`,
          `Ha U kin ïoh jingim badap.`,
        ],
      },
    ],
  },
  {
    id: "song-626",
    title: "Ka Soskular ki Samla",
    metadata: {
      number: 626,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "87.87.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ngi kular mynta, ha Me, Trai,`,
          `Jingshakri jong ngi ban ai;`,
          `Namar jong Me, ngi kloi ban len,`,
          `Pyndap ïa ngi da jingkmen.`,
          `Їa ngi ki Samla kiba tlot,`,
          `Sha ka Kam jong me to khot;`,
          `Ngi kular ban kohnguh ïa Me,`,
          `Ai ngin pyndem ïa lade.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Trai, ngi kular da mon sngewbha,`,
          `Ban ïai bud ïa Me shirta;`,
          `Jingim jong ngi to pynthymmai,`,
          `Ba ngin im bad Me khlem wai.`,
          `Jingthmu jong ngi don tang kawei,`,
          `Ka Balang jong Me ban tei;`,
          `Ha kano ma kaba ngi leh,`,
          `Ngin pyndonburom ïa Me.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Trai, ngi kular ba ngin ïaid beit,`,
          `Ha khmat jong Me da jingngeit;`,
          `Ba ki briew baroh kin ïohi,`,
          `Їa Me ha jingim jong ngi.`,
          `Їarap ïa ngi, Trai, ban sumar,`,
          `Hukum jong Me baroh phar;`,
          `Ngi donkam ïa ka bor jong Me,`,
          `Ba ngin jop ki jingïaleh.`,
        ],
      },
    ],
  },
  {
    id: "song-627",
    title: "Khie joit ko Samla",
    metadata: {
      number: 627,
      language: "khasi",
      composer: "G.R.S.",
      syllables: "S.S. 795",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Pyrthei dap tang jingkylla na kut sha kut,`,
          `Ka pynthame ïa ngi da ki jingsngewbha;`,
          `U soitan syiem jingdum u trei don bor lut,`,
          `Khie joit, khie joit, ko Samla.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Khie joit, khie joit, ko Samla, (2)`,
          `Ka thma u syiem jingdum ka rhem bha mynta;`,
          `Khie joit, khie joit, ko Samla.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Haba tehmraw ïa ngi da jingmlien basniew,`,
          `Kynmaw ba ngim dei ban shu sah kut hangta;`,
          `Ngin ïathuh ha U Jisu ba Un kyrsiew,`,
          `Khie joit, khie joit, ko Samla.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Don bun ki kam ban trei namar U Kynrad,`,
          `Kumjuh ruh namar jingieit bah ka diengphna;`,
          `Ka Balang ruh ka donkam bad ka ïai wad,`,
          `Khie joit, khie joit, ko Samla.`,
        ],
      },
    ],
  },
  {
    id: "song-628",
    title: "To ïalam ïa ngi Trai Babha",
    metadata: {
      number: 628,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "PRECIOUS LORD, TAKE MY HAND",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `To ïalam Trai babha,`,
          `Їa ngi ki khun Samla,`,
          `Ki nongpop ba la rem bad baswai;`,
          `Lyngba jingeh baroh,`,
          `Tang ha Me ai ngin snoh,`,
          `Lam ïa ngi sha burom jong Me, Trai.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Lynti jingïaid jong ngi,`,
          `Dap jingsniew ba jyrsieh,`,
          `Trai baieit, sha Me mynta ngi phai;`,
          `Jingma batriem ki ap,`,
          `Jingdum ïa ngi ka tap,`,
          `Lam ïa ngi sha burom jong Me, Trai.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ynda jingtrei la wai,`,
          `Ngin ïoh shong bad Me, Trai,`,
          `Jingsuk jingkmen ngin shem ruh kyrhai;`,
          `Ha ka ri baphyrnai,`,
          `Long ma Me ka jingshai,`,
          `Lam ïa ngi sha burom jong Me, Trai.`,
        ],
      },
    ],
  },
  {
    id: "song-629",
    title: "U Nongrah Atiar",
    metadata: {
      number: 629,
      language: "khasi",
      composer: "S.T.",
      syllables: "S.S. 670",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Tang kum u nongrah atiar, nga nga ïeng skhem,`,
          `Nga ap ban bud tang shu hukum U Syiem;`,
          `Ban tur, lada shaphrang U phah ïa nga,`,
          `Ryngkat bad U Kapten kum shipai babha.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Sngap, sngap ka jingpyrta!`,
          `‘Shaphrang,’ ka khot;`,
          `Khmih kiba artatien shadien ki ran,`,
          `Nga tip U Kapten Un shaniah ïa nga,`,
          `La tang nongrah atiar nga long shisha.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Tang kum u nongrah atiar hapdeng ka thma,`,
          `Ki jingriam ba phyrnai nga don ban da;`,
          `Nga ap ban sngew ïa ka hukum ban poi,`,
          `Hangta hi ban jubab, Kynrad nga la kloi.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Tang kum u nongrah atiar nga long, hynrei,`,
          `Ngan ïoh ka pansngiat ba phyrnai U Blei;`,
          `Un burom ruh ha khmat ki paid ka bneng,`,
          `Lada ha ka thma haduh ba kut nga ïeng.`,
        ],
      },
    ],
  },
  {
    id: "song-630",
    title: "Shaphrang shipai",
    metadata: {
      number: 630,
      language: "khasi",
      composer: "J.J.",
      syllables: "S.S. 670",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Shaphrang shipai! Shaphrang mynta!`,
          `Khrist U Kapten U dang pyrta;`,
          `Sha ka thyma ïa ngin ïamih,`,
          `Rah ka wait bad stieh!`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Shaphrang! Shaphrang! U ong U Trai,`,
          `Wat tieng long shlur, ka bor Un ai;`,
          `Un ap, Un da ma U ïa ngi,`,
          `Katba sah ka sngi.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Shaphrang shipai! to wat leh tud,`,
          `Sngew, U hukum, ïa U to bud;`,
          `Da U ngin jop, ïa ngi ïaleit,`,
          `Nongshun ngim khaweit.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Shaphrang shipai! ka hok ka neh,`,
          `La ka lama to nang kaweh;`,
          `Shen ‘Ka jingjop’ ngin ïoh riwai,`,
          `Bad U Khrist U Trai.`,
        ],
      },
    ],
  },
  {
    id: "song-631",
    title: "Ki Shipai U Khrist",
    metadata: {
      number: 631,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "S.S. 877",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Shipai U Khrist ka kam mynta ka dawa,`,
          `U Trai, ïa ngi baroh ban trei, U la phah;`,
          `Ka Balang ban tei, kyrteng jong U ban phla,`,
          `Ha pyrthei ba dum, dap jingthala.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `To ngin pyrshang,`,
          `Їa ki kam kiba khraw na ka bynta U Blei`,
          `To khmih lynti`,
          `Їa ki kular kiba khraw na U hi.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Shipai U Khrist, ka Gospel khie leit pynbna,`,
          `Sha ki jaitbynriew, ba na pop kin phai noh;`,
          `Jingsuk ban ai ha pyrthei dap jingkylla,`,
          `Dei tang h'U Jisu, jingim kin ïoh.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Namar U Khrist bad ka Balang ïeng mynta,`,
          `Katba por ka dang don, wat ai ngin buhteng;`,
          `To ngin iehnoh ka pyrthei bad jingsngewbha,`,
          `Ki jingeh baroh U Trai Un weng.`,
        ],
      },
    ],
  },
  {
    id: "song-632",
    title: "Їeng joit mynta",
    metadata: {
      number: 632,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "ALEX. III No. 229",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Їeng joit mynta, ka turoi ka la sawa jam,`,
          `Na kylleng sawdong ka wan jingpyrta;`,
          `Їa ngi ka khot, ki bor ka jingdum ban pyndam;`,
          `Ka jingshai U Khrist ngin pynpaw shynna.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Їeng mynta, kum ki Samla Khristan,`,
          `La jur ka thma to wat kynran;`,
          `Rah la ki atiar, jingdum kan shai kdar,`,
          `U Trai ki paid U don hajan;`,
          `Ka jingïaleh ka dang rhem mynta,`,
          `Ha ka bor jong U to shaniah;`,
          `Ha ka liang U Trai, ïeng khlem da tyngkai,`,
          `Jingjop bakhraw ha ngi Un ai.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Kum kiba khlaiñ ha U Trai, ngin ïeng khlem [sheptieng,`,
          `Ban tur shaphrang la ki jingeh ki wan;`,
          `Ngin pynkhreh ïalade, la ki atiar ngin kieng;`,
          `Ha por baroh Trai ïa ngi Un kyrshan.`,
        ],
      },
    ],
  },
  {
    id: "song-633",
    title: "Ki kam babha to trei",
    metadata: {
      number: 633,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "S.S. 518",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Їaroh ï'U Blei ba pyrthei b'U la thaw,`,
          `Ka nam jong U ngin nang pynkhraw;`,
          `Ki khunswet, khun rangli, jaidbynriew baroh,`,
          `Kajuh ka jingieit ki ïa ïoh.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Sngap, phi, ki samla,`,
          `U Trai U dawa;`,
          `Ki kam babha baroh to trei,`,
          `Kane ka long jingkhot U Blei,`,
          `Met bad mynsiem ban pynim ngi dei.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Kiba pang, shitom, baduk bad kyrduh,`,
          `Ki ud bym don jingkyrmen shuh;`,
          `Kiba shem jingjynjar, lanot bad shipa,`,
          `Їarap ïa ki da mon sngewbha.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Ka pyrthei hi jingsuk kam lah ban shem,`,
          `Ka wad jingshngaiñ bad jingsngewskhem;`,
          `Tang ïa U Jisu ha ka ban ai ngi dei,`,
          `Da met bad mynsiem ruh ngin trei.`,
        ],
      },
    ],
  },
];
