import { SongT } from "@repo/types";

export const shaphangUBlei: SongT[] = [
  {
    id: "song-001",
    title: "U Blei Uba Halor Baroh",
    metadata: {
      number: 1,
      language: "khasi",
      author: "J.R.",
      composer: "Lowel O.C.H. 222",
      syllables: "L.M.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Don Uwei U Blei ha byneng,",
          "U Trai ïa baroh ba la seng;",
          "U synshar hi na mynbarim;",
          "Ngan ieit, ngan iaroh katba im.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ki hukum don ba U la ai,",
          "Ban hikai ïa ka mon U Trai;",
          "Ngan ngeit ka ktien jong U ba neh,",
          "Ba kaba hok, ba shisha eh.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "La wan ka Gospel Blei ha ngi,",
          "Ka jingsuk jai na ka la mih;",
          "Ha ka, Ah Blei, ngin shem ïa Me,",
          "Ai bor ngin wad nongrim ba neh.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "La buh ka por ïa nga ban iap,",
          "Leh kyndit eh ïa nga kan lap;",
          "Ki samla bad ki khynnah ruh,",
          "Ki iap, ban khreh ngan ym tud shuh.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Ngan sumar ïa ki por ba sah;",
          "To wan, Mynsiem, pynkhreh ïa nga;",
          "Tang lap ka jingiap ngam lah phai,",
          "Ka aiom wad jingmap la wai.",
        ],
      },
    ],
  },
  {
    id: "song-002",
    title: "Ka Jingdon U Blei",
    metadata: {
      number: 2,
      language: "khasi",
      author: "J.R.",
      composer: "Oldenburg Iambic O.W. 77",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ka khyndew long ka jong U Trai,",
          "Jingdap kyrhai de jong ka;",
          "Ka pyrthei bad ki briew ki long,",
          "Ki jong U Trai ki paidbah.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ka nongrim jong ka U la seng,",
          "Hapdeng ki um ka duriaw;",
          "Ha jingshlei um U pynskhem bha,",
          "Ia ka, ngi shngain ban kynmaw.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Uei ban kiew sha iing U Trai,",
          "Ban ym phai khymat nangta?",
          "Ha lum ba kyntang Me, Ah Blei,",
          "Uei un ioh ieng hangta?",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Riewkhuid ka dohnud bad ki kti,",
          "Bym iaid ha lynti jubor;",
          "Sha kaba thala um ju phai,",
          "Um smai da kaba shukor.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Jingkyrkhu na U Trai un ioh,",
          "Ban kerkut baroh sawdong;",
          "Ka hok de na U Blei ba im,",
          "Ka jingpynim ba pynlong.",
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          "Ka pateng bynriew ba ju wad,",
          "L’U Kynrad ka long kane;",
          "Ah Blei u Jakob! ki iadem,",
          "Ban shem ka khymat jong Me.",
        ],
      },
    ],
  },
  {
    id: "song-003",
    title: "Ka Jingïaroh Ïa Uwei-Lai",
    metadata: {
      number: 3,
      language: "khasi",
      author: "J.R.",
      composer: "Nicaea S.S. 22",
      syllables: "11.12.12.10",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Bakhuid, Bakhuid, Bakhuid, Bakhrawbor, Ah Blei!",
          "Dang step phyngab, Kynrad, ngi rwai nguh ïa Me;",
          "Bakhuid, Bakhuid, Bakhuid, khlaiñ bad dap jingisynei,",
          "Lai ngut ba tang Wei long U Trai ba neh!",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Bakhuid, Bakhuid, Bakhuid, riewkhuid ki iaroh,",
          "Baroh ki pangsngiat ksiar, ki loit ban nguh ïa Me;",
          "Kherub bad ki Seraph ki mane dem baroh,",
          "Ia Me ba junom U Juh Me iaineh.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Bakhuid, Bakhuid, Bakhuid, b’la tap da u lyoh;",
          "U briew ba pop ban peit ban i ïa Me um lah;",
          "Ma Me bad tang Ma Me, Bakhuid ba dei iaroh,",
          "Ka bor, jingieit, jingkhuid, ha Me ki sah.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Bakhuid, Bakhuid, Bakhuid, Bakhrawbor, Ah Blei!,",
          "Pyrthei, byneng, baroh ki kyntiew nam ïa Me;",
          "Bakhuid, Bakhuid, Bakhuid, khlaiñ bad dap jingisnei,",
          "Lai ngut ba tang Wei long U Trai ba neh!",
        ],
      },
    ],
  },
  {
    id: "song-004",
    title: "Ka Jingdon U Blei Ha Ki Jaka Baroh",
    metadata: {
      number: 4,
      language: "khasi",
      composer: "MARY (Iambic) O.C.H 34",
      syllables: "87.87",
      songId: "song-004",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Shano ngan leit, shano ngan im,",
          "Na U Mynsiem U jong Me?",
          "Shano ngan phet, shano ngan rieh,",
          "Na khymat shaiñ ka jong Me?",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "La sha byneng nga ïoh ban kiew,",
          "Ah Trai ki paid! Me hangta;",
          "La thiah ruh ha dujok hi,",
          "Ha khymih Me don hangta.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "La kum u sim ngan her noh stet,",
          "Ngan phet sha kut ka duriaw;",
          "U Trai Un lam wat hangta hi,",
          "Un ri ruh ïoh ngan mynsaw.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Lada nga ong, “Ka jingdum tliw,",
          "Ïa nga u briew, kan buhrieh;",
          "Ka miet kan tyngshaiñ kum mynsngi,”",
          "U khymih U Blei jong ngi.",
        ],
      },
    ],
  },
  {
    id: "song-005",
    title: "Ka Jingsumar Sukher U Blei",
    metadata: {
      number: 5,
      language: "khasi",
      composer: "Morgannwg (Iambic) N.W. 112",
      songId: "song-005",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah Trai, ka dohnud Me tip bha,",
          "Ïa nga ruh Me la tynjuh;",
          "Kaba nga shong, kaba nga khih,",
          "Ka jingmut hi Me sngewthuh.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ka jingiaid jong nga Me ïit bha,",
          "Dei Me ba da jingthiah;",
          "Ki lynti jong nga baroh ruh,",
          "Ithuh ma Me da shisha.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ha khymih, Trai, Me tip ma Me,",
          "Ki jingleh jong nga baroh;",
          "Ki jingpyrkhat ym lah buhrieh,",
          "Na Me hi lano lano.",
        ],
      },
    ],
  },
  {
    id: "song-006",
    title: "Ka Jingïaroh Ïa U Blei",
    metadata: {
      number: 6,
      language: "khasi",
      composer: "Paradwys (Iambic) O.W. 109",
      syllables: "87.87",
      songId: "song-006",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "To ïaroh jam sngewbha ïa U Trai,",
          "Ma phi ka pyrthei baroh;",
          "To shakri ruh ïa U Trai, to wan,",
          "Hajan da ka jingïaroh.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "To tip b'U Trai long Blei ba khraw,",
          "Uba la thaw ngi kumne;",
          "Ngi long ki langbrot jong U hi,",
          "Ïa ngi, U ri ïa lade.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Sha khyrdop jong U leit da nguh,",
          "Sha ïing jong U da kyrmen;",
          "Ï'U Trai jong ngi to wan ainguh,",
          "To kyrkhu ïa ka kyrteng.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Namar U Trai U long ba bha,",
          "Kam kylla ka jingisnei;",
          "Jingshisha jong U kan ïaisah,",
          "Ïa baroh pateng bynriew.",
        ],
      },
    ],
  },
  {
    id: "song-007",
    title: "Ka Jingshaniah ha U Trai",
    metadata: {
      number: 7,
      language: "khasi",
      syllables: "87.87",
      composer: "Glanceri (Iambic) N.W. 11",
      songId: "song-007",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ngan khymih sha ki lum ngan ap,",
          "Ka jingïarap na shatei;",
          "Ka jingïarap ïa nga Un ai,",
          "U Trai ba la thaw ka pyrthei.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Um shah ka kyjat ban syntuid,",
          "Ngan ïaid laitluit khlem bakla;",
          "U sumar bha ki Israel hi,",
          "Ha khymih Um samthiah.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ha kti kamon jong me, long Blei,",
          "U Trai ba dei nongsumar;",
          "Ka sngi, u bnai, Um shah ban shoh,",
          "Men lait baroh jingjynjar.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "U Trai Un sumar hi ïa me,",
          "Na jong ki jingleh bymman;",
          "Un ri Un pyndap ka mynsiem,",
          "U Nongïarap ba hajan.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Haba me shong haba me khih,",
          "U Trai Un ri da shisha;",
          "Bad naduh mynta long ma U,",
          "Nongsumar ha la ka rta.",
        ],
      },
    ],
  },
  {
    id: "song-008",
    title: "U Blei U Nongthaw",
    metadata: {
      number: 8,
      language: "khasi",
      author: "J. R.",
      composer: "Hursley",
      syllables: "L.M. (Long Metre)",
      songId: "song-008",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "To ïaroh ïa U Syiem byneng,",
          "U long U Trai ki trai kylleng;",
          "Ha U ka jingim lut ka shong,",
          "Na bymjukut, U ju ïai long.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ka sahit byneng U la tei,",
          "Kaba sydien ha neng pyrthei;",
          "Ka sngi, u bnai, ki khlur jingshai,",
          "Ba ïaid ha neng ki nguh ï'U Trai.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "U Trai, ïa baroh long U Blei,",
          "Ha suiñ, ha um, bad ha pyrthei;",
          "Ki jingthaw phar, bad rit bad khraw,",
          "Ki long ki jong U Trai Nongthaw.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "U khymih thuh ïa ngi ki briew,",
          "U ïit ka jylliew dohnud sniew;",
          "Shaneng shapoh ym lah ban rieh,",
          "Ka jingmut shapoh U ïohi.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Ka burom jong U kan sa paw,",
          "Na kiei kiei b'U la thaw;",
          "Jingïaroh kaba khraw kan mih,",
          "Ї'U Blei Uba la thaw ïa ngi.",
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          "Ki lum, ki duriaw, sawa shai,",
          "Ka bor bad ka jingstad U Trai;",
          "Ki jingthaw baroh ha pyrthei,",
          "Ki ong ba Uba khraw U Blei.",
        ],
      },
    ],
  },
  {
    id: "song-009",
    title: "Lai Ngut ha Uwei U Blei",
    metadata: {
      number: 9,
      language: "khasi",
      tune: "Winchester New",
      syllables: "L.M. (Long Metre)",
      songId: "song-009",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ї'U Blei U Kpa to ngin ïa-ai,",
          "Ka burom, bad ï'U Khun, U Trai;",
          "Ї'U Blei Mynsiem ba ai jingkhuid,",
          "Sha lynti sniew ba ngim syntuid.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "U Kpa, U Khun bad U Mynsiem,",
          "Na bymjukut ki long syriem;",
          "Na junom junom Uwei Lai,",
          "Jingmaïan hi bym lah shem trai.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "To ai ka jingaiei U Khun,",
          "Ka jingieit jong U Kpa sybun;",
          "Bad jingïasyllok U Mynsiem,",
          "Kin ïai long lem ba ngin ïoh im.",
        ],
      },
    ],
  },
  {
    id: "song-010",
    title: "Ka Jingsumar sukher U Blei",
    metadata: {
      number: 10,
      language: "khasi",
      author: "T.J.J.",
      syllables: "77.77",
      songId: "song-010",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ai ba da ka mynsiem hun,",
          "Ngin ïaroh ï'U Trai sybun;",
          "Namar ki jingisnei jong U,",
          "Kin neh skhem, kin ym ju duh.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ai ba ngin da pynphriang,",
          "Kylleng ïa la ka kyrteng;",
          "Namar ki jingisnei jong U,",
          "Kin neh skhem, kin ym ju duh.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Te ka burom Blei kan paw,",
          "Ha ki byneng b'U la thaw;",
          "Namar ki jingisnei jong U,",
          "Kin neh skhem, kin ym ju duh.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "U pynshai ïa ka pyrthei,",
          "Da ka bor ka jingaiei;",
          "Namar ki jingisnei jong U,",
          "Kin neh skhem, kin ym ju duh.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "La ka kti dap lin U plie,",
          "Bad U synshar marwei hi;",
          "Namar ki jingisnei jong U,",
          "Kin neh skhem, kin ym ju duh.",
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          "Da la khmat isnei U khmih,",
          "Ha ngi haba long rangli;",
          "Namar ki jingisnei jong U,",
          "Kin neh skhem, kin ym ju duh.",
        ],
      },
      {
        id: "verse-7",
        order: 7,
        type: "VERSE",
        lines: [
          "Ai te ba ka nam jong U,",
          "Ngin ïaroh da kaba nguh;",
          "Namar ki jingisnei jong U,",
          "Kin neh skhem, kin ym ju duh.",
        ],
      },
    ],
  },
  {
    id: "song-011",
    title: "U Blei U Nongiarap",
    metadata: {
      number: 11,
      language: "khasi",
      syllables: "L.M. (Long Metre)",
      songId: "song-011",
      tune: "WARRINGTON",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "To wat buhrieh, Ah Trai ba bha,",
          "Їa lade na u khñiang kat nga,",
          "Ba khia ka pop, jingpang nga shah,",
          "To wan ma Me, ïarap ïa nga.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Me ju pyndap byneng ba khraw,",
          "Sawdong pyrthei Me long ba paw;",
          "Pyni ka khmat isnei, Ko Pa,",
          "Tang kata lah pynshngaiñ ïa nga.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka khmat jong Me, ha pulit rieh,",
          "Bunsien mynshuwa la ïohi;",
          "Nga sliang mynta bad nga swai,",
          "To kren sngewbha ha nga, Ah Trai.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Ah ban ïohi ka khmat jong Me,",
          "Ah ban ïoh mad ka bor ba neh;",
          "Ka bor jingsuk, ka bor jingmap,",
          "Khlem ïoh ïa ki, nga duh, nga ïap.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Te lano ka jingdum kan jah?",
          "Ki lyoh bym kyrmen kiba kah?",
          "Lano kan mih ka sngi ba bha,",
          "Ba pynshai na ka ïing I Pa?",
        ],
      },
    ],
  },
  {
    id: "song-012",
    title: "Kaba kyrmen ha U Blei",
    metadata: {
      number: 12,
      language: "khasi",
      author: "J.C.E.",
      syllables: "C.M. (Common Metre)",
      songId: "song-012",
      tune: "ST. ANNE",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah Blei ba ju iarap ïa ngi,",
          "Ngi kyrmen ruh ha Me;",
          "Ha eriong bah long jakarieh,",
          "Bad jaka shong ba neh.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ha syrngiew jong ka khet jong Me,",
          "Riewkhuid ki la ju shong;",
          "Ka khlain ka ksangkti khraw jong Me,",
          "Ka jingiada ka long.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Mynba ki lum Mem pat shym sei,",
          "Pyrthei Mem pat pynlong;",
          "Na bymjukut Me ju long Blei,",
          "Bad junom Men iai long.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Shihajar snem ha khmat jong Me,",
          "Ki long kum shisngi hi;",
          "Kum jingapmiet ba khatduh eh,",
          "Ha bym pat mih ka sngi.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Ka por ba kum ka wah ba shlei,",
          "Ki khun ka kit noh hi;",
          `Ki her b'la klet kum jingphohsniew,`,
          "Ba jah tang mih ka sngi.",
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          "Ah Blei ba ju iarap ïa ngi,",
          "Ngi kyrmen ruh ha Me;",
          "Ha shitom baroh long ka stieh,",
          "Long jaka shong ba neh.",
        ],
      },
    ],
  },
  {
    id: "song-013",
    title: "Ka Jingmap-ei U Blei",
    metadata: {
      number: 13,
      language: "khasi",
      author: "J.J. & Ed.W.",
      syllables: "88.88.88",
      songId: "song-013",
      tune: "HUDDERSFIELD, MELITA",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah Blei ba khraw, ba phylla eh,",
          "Ha baroh phar ba Me la leh;",
          "Te ïa ki kam jong Me, Ah Blei,",
          "Kham phylla long ka jingaiei.",
          "Ma Me, ko Blei, tang marwei hi,",
          "Me ju map ei ki pop jong ngi.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Jingpalat jong ngi map, Ah Blei,",
          "Ngi rem ngi swai, to pynim ei;",
          "Nalor jong Me, ym don ba lah,",
          "Їa ngi ba pop. ban map ban shna.",
          "Ma Me, ko Blei, tang marwei hi,",
          "Me ju map ei ki pop jong ngi.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ai ba ki soh ka jingaiei,",
          "Ki kam ba bha jingieit U Blei,",
          "Kin nang pynkhraw ka nam jong U,",
          "Ha pyrthei bah ha byneng ruh.",
          "Ma Me, ko Blei, tang marwei hi,",
          "Me ju map ei ki pop jong ngi.",
        ],
      },
    ],
  },
  {
    id: "song-014",
    title: "Ka Jingthmu U Blei",
    metadata: {
      number: 14,
      language: "khasi",
      syllables: "10.10.10.10",
      songId: "song-014",
      tune: "NAVARRE",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Pyrthei, byneng,ïakine ym pat thaw,",
          "Ka sngi, u bnai, ki khlur ruh ym pat paw;",
          "Myn ha ka jingiasyllok Uwei-Lai,",
          "Iakut bun im u briew ba rem, ba swai.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Hu Jisu Khrist la kynshew jingaiei,",
          "Bym lah ban thew, ba khraw ka jingisnei;",
          "La jyntia lut ka pyrthei kylleng bah,",
          "Ba tuid ki um jingthymu ieit I Pa.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "La pynbna mynta ka jinglaitim ïa ngi,",
          "Ka snam U Khun la mih ha Kalbari;",
          "To iaroh jam, ka ktien pynkylluid war,",
          "IU diengphyna, ka snam ba pyllait phar.",
        ],
      },
    ],
  },
  {
    id: "song-015",
    title: "Ka Jutang U Blei",
    metadata: {
      number: 15,
      language: "khasi",
      syllables: "10.10.10.10",
      songId: "song-015",
      tune: "HOLLEY",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Jutang jingsuk, jutang ba skhem U Blei,",
          "Bym kynriah noh, la kad nongrim pyrthei;",
          "Jutang ba shisha, bym lah kylla shuh,",
          "La jur ka pop, ka jingim ngim ju duh.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Jutang aiei, b'la thaw da Uwei-Lai,",
          "Ka spah ïa ngi, ka skhem ka ktien jingsmai;",
          "Ka long ba lah ban kyntiew lin ïa ngi,",
          "Ka bor jong ka, ka bor jong U Blei hi.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Jutang ba dap, ba ai jinghun ï'U Blei,",
          "Shuwa ba thaw ki lum bah ka pyrthei;",
          "Ka jor jong ka, bun byllien kan pyllait.",
          "Ka snam U Khun ka ram jong ki ka sait.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Jutang donbor. bym lah pyntor ïa ka,",
          "Pyrthei, jingïap, kim lah pynduh ïa ka,",
          "Ka dang neh skhem jingthymu slem U Blei,",
          "Kam khih kum kiba tlot ki jong pyrthei.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "La hap sha pop, la ngop ki khun U Blei,",
          "Jutang dang don, ïa ki ban ïoh isnei;",
          "Ban sait ïa ki, jingpalat ruh pynduh,",
          "Ban pynmihpat na jingtep khlem pop shuh.",
        ],
      },
    ],
  },
  {
    id: "song-016",
    title: "Ka jaka rieh ha U Blei",
    metadata: {
      number: 16,
      language: "khasi",
      author: "J. R.",
      syllables: "888. D.",
      songId: "song-016",
      tune: "NASHVILLE",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "U Blei ka bor bad jakarieh,",
          "Ha khim bad ha jingshipa hi,",
          "Haba ngi kyrpad, U la jan;",
          "Ki lum sha duriaw ai kin hap,",
          "Kan pra pyrthei bad ka jingdap,",
          "Ha nga jingtieng mynsiem kam wan.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ki duriaw halor ka pyrthei,",
          "Kin jyntia lut da ka jingshlei,",
          "Kin ngop ki lum kum mynbarim;",
          "Ka wah ba sngur ka tuid kyrhai,",
          "Sha nongbah U Blei khlem da wai,",
          "Ki khun U Blei junom kin im.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "U Blei U don bad ki, ban da,",
          "Ia kiba tlot U kyrshan bha,",
          "Jingiarap lypa U la khreh,",
          "Ki jingbanbein to ai kin wan,",
          "Jingshitom mynsiem ai kin ban,",
          "Ka bor U Blei sha ki la theh.",
        ],
      },
    ],
  },
  {
    id: "song-017",
    title: "Ka Spah Ha U Blei",
    metadata: {
      number: 17,
      language: "khasi",
      author: "J.R.",
      composer: "Waterstock (S.S. 490.)",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ka spah ba ngi la ioh,",
          "Kat ka ban shem ym lah;",
          "Ka jingioh suk ba ei,",
          "Ha ri seisoh I Pa.",
          "Ym don ba lah ïa nga te shuh,",
          "Na U pynkhlad da lei lei ruh.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ka jerong bym lah khein,",
          "Ka jylliew bym lah ong;",
          "Ka jingim kaba kor,",
          "Ka dor bym lah pynshong,",
          "Phi lah ban ong phi Seraph khuid,",
          "Ka dor ka spah sha ngi b'la tuid?",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka jingpah ka pyrthei,",
          "Te baroh phar ka duh;",
          "Jingpynshoi kiba jur,",
          "Ki dam, kim donbor shuh;",
          "Ka duh ka rong ki tiew pyrthei,",
          "Nga shem itynnad tang U Blei.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Ka sngi, ki khlur, byneng,",
          "Ki hap ki noh arsut,",
          "Ka jingdum tliw ka tap,",
          "Ka jingsngewbha la lut;",
          "Itynnad eh tang U Blei hi,",
          "Bad tang na U ka suk ka mih.",
        ],
      },
    ],
  },
  {
    id: "song-018",
    title: "Uwei-Lai Bakhuid",
    metadata: {
      number: 18,
      language: "khasi",
      author: "H.L.",
      composer: "Sanctus",
      syllables: "87.87. D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Sawdong ka burom jong U Trai,",
          "Kherub bad Seraph ki ieng;",
          "Ki jingiaroh ba ki iarwai,",
          "Ki pynsawa ïa ki bneng.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Ka bneng bad ka khyndew ka shlei,",
          "Da ka burom jong U Trai,",
          "Sha Me ban ai burom ka dei,",
          "Bakhuid Bakhuid Bakhuid, Trai.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka la khynwin ka bneng hajrong,",
          "Pyrthei ruh ka iaroh jam;",
          "“Bakhuid, Bakhuid, Bakhuid,” ka ong,",
          "Trai ki paid, ba ha khlieh tam.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Lem bad Seraph baroh ha bneng,",
          "Lem bad ka Balang hangne,",
          "Ia U ngin mane dem kylleng,",
          "Ia U ngin rwai iaroh de.",
        ],
      },
    ],
  },
  {
    id: "song-019",
    title: "Ka Jakarieh U Khristan (Salm xlvi)",
    metadata: {
      number: 19,
      language: "khasi",
      composer: "St. Trond (Iambic)",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "To wan ma phi, to khymih de,",
          "Ki jingleh U Trai jong ngi;",
          "Kumno pynduh, kumno pynmih,",
          "Ki hima jong ka pyrthei.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ka jingiapom Un sa pynduh,",
          "Na mihngi haduh sepngi;",
          "Ka ryntieh, jingsum, bad u khnam,",
          "Un pynduh U Trai jong ngi.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Sngap jar, to tip ba nga long Blei,",
          "Uba ka dei ban iaroh;",
          "Ki Jentil kin pynkhraw ïa Nga,",
          "Ka pyrthei bah ruh baroh.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "U Trai da lade long bad ngi,",
          "U Trai ki paidbah angel;",
          "Ka bor bad jakarieh U long,",
          "U Blei U jong ki Israel.",
        ],
      },
    ],
  },
  {
    id: "song-020",
    title: "Ka Jingshlur Ha U Blei",
    metadata: {
      number: 20,
      language: "khasi",
      composer: "Mary (Iambic)",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "U Trai U long jingshai jong nga,",
          "Jingkhiah, ngan tieng iano?",
          "U Trai U long ka bor jingim,",
          "Pynkhim ïa nga lah mano?",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Nga shaniah lut ha Me U Blei,",
          "Ngan lehraiñ lei ban ialap?",
          "Ah Blei, da la ka hok pynim,",
          "Ban im mynsiem to iarap.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Haneng ka jaka jong Me toi,",
          "Me kloi la shkor ban pynshah;",
          "Ia nga ban pynim long mawsiang,",
          "Ka synrang kaba shisha.",
        ],
      },
    ],
  },
  {
    id: "song-021",
    title: "Salm Cxxxix",
    metadata: {
      number: 21,
      language: "khasi",
      author: "J.R.",
      composer: "Oldenburgh (Iambic)",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "I'u bymman, Trai Me pyniap duh,",
          "Mem ju riej shuh kum kita;",
          "To kynriah phi ki riew bitsnam,",
          "Ioh ngam lem nga ruh hangta.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ki kren ‘tien sniew pyrshah ïa Me,",
          "Ba meh jingbitar hapoh;",
          "Ki kynnoh bein ka nam jong Me,",
          "‘Riewsniew kim treh ban iaroh.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ki nongshun jong Me, Trai, nga shun,",
          "Bad ki, kam hun ka mynsiem;",
          "Kat kiba ieng ialeh ïa Me,",
          "Kim neh, kan ngat ka jingtim.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "To iit ïa nga, Ah Blei, ithuh,",
          "To tynjuh dohnud jong nga;",
          "To tip ki jingmut tynrai hi,",
          "Ioh ka dang sap jingbakla.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Shapoh jong nga to khymih thuh,",
          "Ioh nga dang buh jingbymman;",
          "Ha lynti bymjukut to lam,",
          "Nga iam ha Me, to kyrshan.",
        ],
      },
    ],
  },
  {
    id: "song-022",
    title: "Ka Salm Xxvii",
    metadata: {
      number: 22,
      language: "khasi",
      author: "J.R.",
      composer: "Oldenburgh",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "U Trai ka jingshai nga U long,",
          "U Nongpynim ïa baroh;",
          "Ka bor jingim hangne U ai,",
          "Trai, ngan sheptieng iano?",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "La shet, la sylla, byllien bah,",
          "Kam ma ka mynsiem jong nga;",
          "La mih kynhun nongshun ban thap,",
          "Kam duh jingshlur ‘riew shisha.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Tang kane kawei ngan iai pan,",
          "Ban wan ïa im shi-ryta;",
          "Ha iing U Trai, ban i b'U shong,",
          "BU long itynnad hangta.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Ha ka sngi jynjar Un sa mih,",
          "Ban rieh ha iing sngewtyngen;",
          "Ha u mawbah Un kyntiew bha,",
          "Um shah ban duh jingkyrmen.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "To sngew, Ah Trai, l'u khun ba kyang,",
          "To nang iashah, isynei;",
          "Me ong ma Me, “To wad ïa nga,”",
          "Kumta nga wad, Ah U Blei.",
        ],
      },
    ],
  },
  {
    id: "song-023",
    title: "Ka Jakarieh U Khristan (Salm xlvi)",
    metadata: {
      number: 23,
      language: "khasi",
      composer: "Dymuniad (Iambic)",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "U Blei U long ka jakarieh,",
          "Ka bor ïa ngi ban kyrshan;",
          "Ha ki jingkhuslai katba lap,",
          "U nongiarap ba hajan.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Te namarkata ngin ym tieng,",
          "La don jingjynjar ba khraw;",
          "La khih pyrthei la noh ki lum,",
          "Ha pydeng ki um duriaw.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "La ki um jong ka ki kyrhuh,",
          "Ki lum ruh ki ishyrkhei;",
          "Ka don ka wah, ki um jong ka,",
          "Ki pynkmen ka shnong U Blei.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "U Blei ha pdeng jong ka U long,",
          "U shong, kan ym khih; hynrei,",
          "U Blei Un kyrshan dang step hi,",
          "Un pyni la jingisnei.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "La dom nongmane ki bleithaw,",
          "La ki bakhraw ki bitar;",
          "U Trai u kren ki briew ki sngap,",
          "Ka pyrthei ka jar jar.",
        ],
      },
    ],
  },
  {
    id: "song-024",
    title: "Ka Jingiada U Blei Ïa La Ki Briew (Salm xlvi)",
    metadata: {
      number: 24,
      language: "khasi",
      composer: "Ely (Iambic)",
      syllables: "87.81",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "U Blei U long ka jakarieh,",
          "Ka bor ïa ngi ban kyrshan;",
          "Ha ki jingkhuslai baroh phar,",
          "U Nongiarap ba hajan.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "La khih pyrthei ngin tieng ruh lei?",
          "U Blei sha khlieh ka jynjar;",
          "La noh ki lum sha duriaw bah,",
          "U lah ma U ban synshar.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "La at la kyrhuh lang ka um,",
          "La win ki lum na kata;",
          "Ka wah ka tuid sha shnong U Blei,",
          "Sngew shngain ha Seion shisha.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Ha iing ba khuid U Trai U shong,",
          "U long ma U ban kyrshan;",
          "U kloi ban wan iarap, ban ri,",
          "Kam khih, la ban u bymman.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "La win ki hima kylleng ruh,",
          "La bitar ki riewthala,",
          "Te tang shu lap ba kren U Trai,",
          "La wai jingsniew riewsylla.",
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          "U Trai ki paidbah U ialam,",
          "Ka lah ka waitlam jong ngi;",
          "Ai kin iakyntur ki nongpop,",
          "Ngin jop ruh ha la ka sngi.",
        ],
      },
    ],
  },
  {
    id: "song-025",
    title: "Ka Jingkhraw Ka Jingisynei (Salm xxxvi)",
    metadata: {
      number: 25,
      language: "khasi",
      author: "J.R.",
      composer: "Morganwg",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Katno ba kor ki jingisnei,",
          "U Blei U bymjukylla;",
          "Te namarkata ngi ki briew,",
          "Ha syrngiew Me ngi shaniah.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ha iing jong Me don bam kyrhai,",
          "Ban ai ha kiba thyngan;",
          "Na wah jong Me kin dih sngewbha,",
          "Na ka kin ioh jingkyrshan.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Me long ma Me ka tynrai hi,",
          "Na Me ka mih ka jingim;",
          "Ha jingshai khymat jong Me, Trai,",
          "Ka shai kydar ka mynsiem.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Jingisnei jong Me Trai, wat khang,",
          "Na kiba thrang ka mynsiem;",
          "Nang ai sngewbha ka hok jong Me,",
          "Ia kiba beh ka jingim.",
        ],
      },
    ],
  },
];
