import { SongT } from "@repo/types";

export const shaphangKaJingiapKibaNgeit: SongT[] = [
  {
    id: "song-457",
    title: "Kaba ïohi ïa ka ri",
    metadata: {
      number: 457,
      language: "khasi",
      author: "J.C.E.",
      composer: "S.S. 1029",
      syllables: "87.87.D",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Nga nga long u nongwei shane,",
          "Shatai long ka ri jong nga;",
          "Shatai hi sha shiliang duriaw,",
          "Shapoh Kanaan, ri ba bha.",
          "Erïong bah jong ki jingpynshoi,",
          "Shane ki la shop ïa nga;",
          "Ko lyer shathie ba sngewpyngngad,",
          "Rah ïa nga sha ïing I Pa.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "La ki jur ki jingatphyllung,",
          "Sha kadiang sha kamon;",
          "Lyngba erïong, erlangthari,",
          `Ngan sa poi b'U Blei U don.`,
          "Ktien U Blei kan jop ka duriaw,",
          "Ktien U Blei kan jop ka lyer;",
          "Ha ka kular Blei ngan shaniah,",
          "Shatei shaneng ngan sa her.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Nga ïohi ka kut ka jingleit,",
          "Ha ka duriaw ngam sah slem;",
          "Ki jingkular bad ki hukum,",
          "Baroh ki ïa kyrshan lem.",
          "Ka jingjylliew jong ka duriaw,",
          "Kan ym long ka jaka shong;",
          "Hynrei ngan sa poi sha shiliang,",
          "Bad U Trai te ngan ïai long.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Nga sngew lypa mynta kumne,",
          "Jingiwbih na ri U Blei;",
          "Ba la kit ki lyer ba pyngngad,",
          "Nga la jan, la um ka shlei.",
          "Khublei pha, ka ri sngewtynnad,",
          "Ri ba suk ka bym ju blad;",
          "Jingsngewbha jong pha har rukom,",
          "Mynta hi to ai ngan mad.",
        ],
      },
    ],
  },
  {
    id: "song-458",
    title: "Kaba kut ka Jingim",
    metadata: {
      number: 458,
      language: "khasi",
      composer: "RHYDDID",
      syllables: "76.76.D",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Na ïing ngan mih sa khyndiat,",
          "Ba mynta nga dang shong;",
          "Kin pra jingkyrshan jong ka,",
          "Ban kyllon la jan long.",
          "Kan her ka jingpang baroh,",
          "U nongjop nga la mih;",
          "Nga riwai haba kynmaw,",
          "Їa ka sngi, ngan sa lieh.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ban i ïa nga riewbymman,",
          `B'la kut la jingleit bha;`,
          "Sngewphylla long ban riwai,",
          "Ka ktien kan pher shata.",
          "Ka jingjop ngan sa risa,",
          "Jingsiewspah Nongpynim;",
          "Khlem tieng ban lah ka bymman,",
          "Sha khlieh, na sniew nga im.",
        ],
      },
    ],
  },
  {
    id: "song-459",
    title: "Ka wah Jingïap",
    metadata: {
      number: 459,
      language: "khasi",
      composer: "ALED (65.65.6665)",
      syllables: "65.65.6665",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Harud wah jingïap ïong,",
          "Nga lyngngoh shibun;",
          "Shu kwah ban hiar, shu tieng,",
          "Ki um ba jylliew;",
          "Ah! ban da shem ka lad,",
          "Ban ryngkang, khlem da mad;",
          "Ka jingïap triem ba kad,",
          "Mynsiem ki bynriew.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ban pyrkhat ïa ka um,",
          "Bad jingat jong ka;",
          "Ba hangne bun la khum,",
          "La ngam ruh hangta!",
          "Nga tieng ïoh nga ngan ngam,",
          "Їoh ïap khlem Nongïalam;",
          "Ba ban ka pop ka ram,",
          "Ha kaba kynjah.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ban poi ha tyngkhap lum,",
          "Ba dum, ba kynsha;",
          "Ha kaba i ka um,",
          "Ba jur eh shisha!",
          "Ah! lymda wan ban tan,",
          "Ban marwei leit ngam shlan;",
          "Ah Trai! to nang kyrshan,",
          "Ba ïoh ngam hangta.",
        ],
      },
    ],
  },
  {
    id: "song-460",
    title: "Ka Jingïap bad ka Jingsuk",
    metadata: {
      number: 460,
      language: "khasi",
      composer: "LLEF",
      syllables: "L.M",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ki lok baieit jong nga kim lah,",
          "Tang sharud jingtep wan ban rah;",
          "Nangta ki phai, ka sngi kan long,",
          `Kin ieh ïa nga h'u maw ban shong.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Te shisien ka sngi ngan sa mih,",
          "Ngan kiew sha Seïon lum sha khlieh;",
          "Ka dewmet jong nga kan ïalang,",
          "Ban shem ka dur U Trai khlem pang.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ngan ïoh ïaid shatei ha jinghun,",
          `La jop ka jingïap, ï'u nongshun;`,
          "Jingswai ei ei kam khang ïa nga,",
          "Ban 'roh ï'U Khun, ki nar b'la shah.",
        ],
      },
    ],
  },
  {
    id: "song-461",
    title: "Ka Jingjahthait ha ka Jingïap",
    metadata: {
      number: 461,
      language: "khasi",
      composer: "ST. AMBROSE",
      syllables: "C.M",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah! katno suk ban ïap da ngeit,",
          "Ha Jisu Nongpynim;",
          "Ka nam jong ki long jingiwbih,",
          "Ki ïap ïa ka ban im.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Hadien jingkhuslai shitom sat,",
          "Ka pyrthei bad jingshun;",
          "Jyngai na ki ha jingtep hi,",
          "Ki shongthait ha jinghun.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka ktien nongban beiñ kam lah dung,",
          "Їa ki kam pynïam shuh;",
          "Jingpynshoi kthang lymne jingpang,",
          "Kim lah pynsngewsih ruh.",
        ],
      },
    ],
  },
  {
    id: "song-462",
    title: "Ka Jingïap ki riewblei",
    metadata: {
      number: 462,
      language: "khasi",
      author: "T.J.",
      composer: "DINIWEIDRWYDD",
      syllables: "87.87.D",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ki lok jong nga ki la leit noh,",
          "Shatei byllien mynshuwa;",
          "Ha them Baka ki la ju ïaid,",
          "Sha shnong Salem lem bad nga.",
          "Ha ka them ba dum ba kynsha,",
          "Ka jingngeit ïa ki ka shan;",
          "Ka jingkular don ïa nga ruh,",
          "Peit sha jingïap hi nga shlan.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Kumno'n lait sha shiliang Jordan,",
          "Lymda wan ma Me ban shaw;",
          "Ban pynjem ki jingatphyllung,",
          "Sni ka jingïap ruh ban law!",
          "Rah ka khlieh, shaneng to kyntiew,",
          "Їoh ha jingshlei ngan sa ngop;",
          "To ïa kyrshan ha ka jingïap,",
          "Їoh ïa nga ba tlot kan jop.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Khublei phi ba nga ju ieit,",
          "Ban ïasyllok ju sngewbha;",
          "Jingieit dohnud ban kot palat,",
          "Їa ka jingtep dum kam lah.",
          "Haba wan jingïap ngin khlad noh,",
          "Bha ïa nga ba nga don Blei;",
          "Lok ba synran ha ka jingïap,",
          "Ї'U ta, mynba im nga dei.",
        ],
      },
    ],
  },
  {
    id: "song-463",
    title: "Ka Jingïap ka la jan",
    metadata: {
      number: 463,
      language: "khasi",
      composer: "ST. OSWALD",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah! mynsiem, ki um ba pyjah,",
          "Jordan jylliew, ki la jan;",
          "Hynrei haba i ka Salem,",
          "Ryngkat shato hi nga shlan.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Hangto don ki lok ki jong me,",
          "Na ki jingpang ki la lait;",
          "Ki dang ap ïa me ha shiliang,",
          "Ban ïa kymen, riwai shait.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Wat sngew sheptieng, kam long jyngai,",
          "Rangbah Lyngdoh hi U ïeng;",
          "Ha ki um ba ïong, ba jylliew,",
          "Ban ïalam beit sha byneng.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Sngap jingriwai jam ki angel!",
          "Sngap! ka wan na Seïon lum;",
          "I ba plie ki khyrdop ksiar,",
          "Lyngba ïa u lyoh jingdum!",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Khublei pyrthei! khublei jingïaid,",
          "Ha ri khlaw ba kynsha shuh!",
          "Khublei doh! khublei jingtyngit!",
          "Khublei pang bad jynjar ruh!",
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          "Ha ka jingdum ka la phyngaiñ,",
          "I sa khyndiat ka la shai!",
          "I ki ïing shongneh ruh lypa,",
          "Ha ka shnong ba khuid U Trai.",
        ],
      },
    ],
  },
  {
    id: "song-464",
    title: "Ka Jingleit noh ki lok",
    metadata: {
      number: 464,
      language: "khasi",
      author: "J.C.E.",
      composer: "SHARON",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ki lok jong nga ki nang leit noh,",
          "Shuwa jong nga wei-pa-wei;",
          "Ki da ïehnoh ïa nga marwei,",
          "Kum u pilgrim ha pyrthei.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ynda ngi la ju ïaid ryngkat,",
          "Ha ka ri jingjynjar bah;",
          "Sngewsih ba ngi dei ban khlad noh,",
          "Ba jan poi sha ïing I Pa.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ki la lait sha khlieh ki nongshun,",
          "Lait na shitom bad khuslai;",
          "Mynta ki la phong la pansngiat,",
          "Ki da rah ruh ki diengtlai.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Nga ju tharai ba ha Salem,",
          "Nga ïohi ba ki ïaid lang;",
          "Bad ba ïohsngew hateng hateng,",
          "Їa ki sur byneng ba bang,",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Hynrei lajan poi te ka sngi,",
          "Ba ngan ïoh ïalang bad ki;",
          "Ban ïai ïaroh khlem da wai shuh,",
          "Bym lah pynïakhlad ïa ngi.",
        ],
      },
    ],
  },
  {
    id: "song-465",
    title: "Ka Jingsuk kiba la ïap",
    metadata: {
      number: 465,
      language: "khasi",
      composer: "GWLADYS; LOVELY",
      syllables: "66.66.88",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Yn isnei lei ïa ki,",
          "Shikur b'la suk kynjai?",
          "Na jynjar ki la mih,",
          "Na pyrthei sha U Trai.",
          "Sha khlieh la poi ban shem sngewbha,",
          "Ban shong bad Jisu suk shisha.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "La kynriah sha jyngai,",
          "Sha khlieh jingkhuslai ruh;",
          "Ka jingpang ka la wai,",
          "Їa ki kam lah ktah shuh.",
          "La lait shaneng, jingud la jah,",
          "Ban shong bad Jisu suk shisha.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Yn ym ïohi ïa ki,",
          "Ban ïam ba don ba ban;",
          "Kim khuslai shuh sha khlieh,",
          "Ka shitom kam lah wan.",
          "La iehnoh phar, wan phai kim kwah,",
          "Ban shong bad Jisu suk shisha.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Jingkordit ka la duh,",
          "Jingkyrmen ka la long;",
          "Ha syndah Nongpynim,",
          "Te junom kin ïashong.",
          "La ïoh jahthait na ki jingma,",
          "Ban shong bad Jisu suk shisha.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Ha ri ba shong jingsuk,",
          "Ki ïaroh khlem da wai;",
          "Ka jingpynim ba khraw,",
          "Jingsiewspah jong U Trai.",
          "Ka khmat U Trai kin i khlem kah,",
          "Ban shong bad Jisu suk shisha.",
        ],
      },
    ],
  },
  {
    id: "song-466",
    title: "Suk ha ki kti U Jisu",
    metadata: {
      number: 466,
      language: "khasi",
      author: "E.H.W.",
      composer: "S.S. 57",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Suk ha ki kti U Jisu,",
          "Ha shadem jong U, suk;",
          "Da ka jingieit Un sumar,",
          "Junom ïa nga ba duk.",
          "Sngap! dei ka ktien ki angel,",
          "Ba ki pynher sha nga;",
          "Na la ka ri ba tyngshaiñ,",
          "Nalor ki duriaw bah.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Suk ha ki kti U Jisu,",
          "Ha shadem jong U, suk;",
          "Da ka jingieit Un sumar,",
          "Junom ïa nga ba duk.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Suk ha ki kti U Jisu,",
          "Suk na ki jingkhuslai;",
          "Suk na ki bun jingpynshoi,",
          "Pop Un nang beh sha jngai.",
          "La lait na ki jingshitom,",
          "La lait na ki jingma;",
          "La lait na ki jingtynjuh,",
          "Ki ummat ruh la jah.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Jisu ba ieit, Nongpynim,",
          "B'la ïap ïapli ïa nga;",
          "Skhem kum u mawsiang junom,",
          "Tang ha Me ngan shaniah.",
          "Hangne nga kwah ban ïai ap,",
          "Ap ba kan wai ka miet;",
          "Ap ba kan mih ka jingshai,",
          "Na Seïon lum ba ieit.",
        ],
      },
    ],
  },
  {
    id: "song-467",
    title: "Ngin ïashem lang ha byneng",
    metadata: {
      number: 467,
      language: "khasi",
      author: "W.M.J.",
      composer: "S.S. 381",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ngin ïashem lang ha byneng,",
          "Ngin ïashem bad l'U Nongthaw;",
          "Ngin ïohlait na ki jingshitom,",
          "Ba la shah ha ka ri khlaw.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Ngin ïashem lang,",
          "Ngin ïashem lang,",
          "Ngin ïashem lang ha byneng.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ngin ïashem lang ha byneng,",
          "Ka jingkhuslai kan sa duh;",
          "Jingïap triem kam lah kiew hangtei,",
          "Junom junom ngim khlad shuh.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "La don bun ba ngi ju ieit,",
          "Ki la ryngkang ïa ka wah;",
          "Ngim bynnud, ngi don jingkyrmen,",
          "Ban ïashem ha ïing I Pa.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Ngin ïashem lang ha byneng,",
          "Ngin ïa syllok bad l'U Trai;",
          "Bad u paidbah khuid ki angel,",
          "Ї'U ngin ïaroh khlem da wai.",
        ],
      },
    ],
  },
  {
    id: "song-468",
    title: "Bym lah ñiew kum u shyiap ka duriaw",
    metadata: {
      number: 468,
      language: "khasi",
      author: "W.A.S.",
      composer: "S.S. 998",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ynda ngin poi sha shiliang wah Jordan,",
          "Їa ki riewkhuid ha burom ngin i;",
          "Bym lah ñiew kum u shyiap ka rud duriaw,",
          "Ah! katno ka jingphylla ïa ngi.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Bym lah ñiew kum u shyiap ka rud duriaw;",
          "Bym lah ñiew kum u shyiap rud duriaw;",
          `Shisha ngi i phylla ï'u paidbah riewkhuid hangta,`,
          "Bym lah ñiew shuh kum u shyiap ka rud duriaw.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ynda ngin i riewkhuid na mynbarim,",
          "Ummat sngewsih la ñiad noh na ki;",
          "Ngin ïashem lang baroh da ka jingkmen,",
          "Ah! katno ka jingphylla ïa ngi.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Ynda ngin peit hangta ï'U Nongsiewspah,",
          "Ha ka burom phyrnai jong U hi;",
          "Kum U Syiem ha ka khet Un ïai synshar,",
          "Ah! katno ka jingphylla ïa ngi.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Ynda ngin ïeng harud wah itynnad,",
          "Hapoh syrngiew u dieng ka jingim;",
          "Їa ka ri jingkular ngin sa ïohi,",
          "Ah! katno ka jingphylla ïa ngi.",
        ],
      },
    ],
  },
  {
    id: "song-469",
    title: "Ngi ïa ong, 'KHUBLEI'",
    metadata: {
      number: 469,
      language: "khasi",
      composer: "Choral Treasury 427",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ki sngi kiba bha ngi la ïoh,",
          "Ban sngap ïa ki ktien U Blei;",
          `B'la kyntu ïa ngi ban beh baroh,`,
          "Sha ka ri sngewtynnad shatei.",
          "Ngin ïakhlad da ka jingsngewieit,",
          "Ngin ïa duwai bad nguh ï'U Blei;",
          "Ba sa khyndiat hi ngin ïashem sngewbha,",
          "Da jingieit ngi ïa-ong, 'Khublei'.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Khublei! Khublei!",
          "La ym hangne ha ka pyrthei;",
          "Sa tang khyndiat hi ngin ïashem haneng,",
          "Te mynta ngi ïa ong, 'Khublei'.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ki jingïaseng lang ha pyrthei,",
          "Ki la wai tang shibit hi;",
          "Da jingïaieit bad jingduwai,",
          "Ngi ïa ong khublei lang ïa phi.",
          "La ym hangne ha ka pyrthei,",
          "Ngin ïashem ha khmat U Blei;",
          "Ynda poi shaneng bad riewkhuid baroh,",
          "Hangta ngin ym ong shuh, 'Khublei'.",
        ],
      },
      {
        id: "chorus-2",
        order: 4,
        type: "CHORUS",
        lines: [
          "Khublei! Khublei!",
          "La hangne ngi ïa ong, 'Khublei';",
          "Ynda poi shaneng bad riewkhuid baroh,",
          "Hangta ngin ym ong shuh, 'Khublei'.",
        ],
      },
    ],
  },
  {
    id: "song-470",
    title: "Thiah suk, lok ba ieit",
    metadata: {
      number: 470,
      language: "khasi",
      composer: "S.S. 1041",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Thiah suk, lok ba ieit, thiah bad to jahthait,",
          "Ha shadem Nongpynim la khlieh to dem;",
          "Ngi ieit ïa phi, h'U jingieit tam phin shem,",
          "Khublei! Khublei! Khublei!",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Kum i khunlung, ka jingthiah ba lyngngai,",
          "Phin ym khie shuh ha pyrthei jingkhuslai;",
          "Ka jingshongthait ba shisha, ba janai,",
          "Khublei! Khublei! Khublei!",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Tad haduh ba step jingmihpat kan shai,",
          "Tad da nongïap h'U Jisu kin mih paw;",
          "Bad ha ka burom ïa phi Un wan shaw,",
          "Khublei! Khublei! Khublei!",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Ha dur ka burom U Blei phin phyrnai,",
          "Ynda la pynphuh da jingieit U Trai;",
          "Pansngait ka burom jong ka bneng Un ai,",
          "Khublei! Khublei! Khublei!",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Khublei shipor, lok, ngim ïakhublei duh,",
          "Shen riewkhuid baroh kin sa ïakynduh;",
          "Ha jingïasoh ba khuid bym ïakhlad shuh,",
          "Khublei! Khublei! Khublei!",
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          "Ha ban da ïa shem pat ha khmat ka khet,",
          "Da jaiñ ba lieh ka hok Un ai ban phong;",
          "Bad ki angel ïaroh i'U Trai junom,",
          "Khublei! Khublei! Khublei!",
        ],
      },
    ],
  },
  {
    id: "song-471",
    title: "Ha lyndet wah badum",
    metadata: {
      number: 471,
      language: "khasi",
      author: "T.R.",
      composer: "S.S. 915",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ha jaiñkup khuid lieh ba phyrnai,",
          "B'la sait khuid ha snam Kalbari;",
          "Ngin ïoh jingsyllok ba janai,",
          "Hangta junom bad Jisu hi;",
          "Ha lyndet wah ba dum.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Ha lyndet wah ba dum,",
          "Ha lyndet wah ba dum;",
          "Ha lyndet wah ba dum,",
          "Ngin ïashem lang hangta.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Balei ngin tieng jingeh jingma,",
          "La ïing shongneh mynta ngi i;",
          "Ha sngap ba thiang jingkhot sngewbha,",
          "Ki angel neng ki ap ban plie;",
          "Ha lyndet wah ba dum.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Ynda ngin poi jingïaseng bah,",
          "Hangta bad riewkhuid suk kynjai;",
          "Jingpang, jingsngewsih lut kin jah,",
          "Ki ummat Un ñiad noh U Trai;",
          "Ha lyndet wah ba dum.",
        ],
      },
    ],
  },

  {
    id: "song-472",
    title: "Sha ïing ngan leit",
    metadata: {
      number: 472,
      language: "khasi",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ka ïing shongneh jong nga ha bneng,`,
          `Ha kaba riewkhuid ki ïaseng;`,
          `Hangta ka kordit bad pangsuh,`,
          `Kim lah pynshitom ïa nga shuh.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Sha ïing ngan leit,`,
          `Sha ïing ngan leit ban ym ïap shuh,`,
          `Sha ïing ngan leit,`,
          `Sha ïing ngan leit ban ym ïap shuh.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Ki kynroh jong ka ïing I Pa,`,
          `La tei da ksiar ba nylla;`,
          `Ynda ka met mynsiem kam phong,`,
          `Ka ïing I Pa, jong nga kan long.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Ki ïing ha pyrthei baroh ruh,`,
          `Kiba ka ding kan sa bam duh;`,
          `Hynrei ka ïing I Pa jong nga,`,
          `Kaba ïaineh ha la ka rta.`,
        ],
      },
    ],
  },
  {
    id: "song-473",
    title: "Don ri basuk janai",
    metadata: {
      number: 473,
      language: "khasi",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Don ri ba suk janai,`,
          `Shajyngai bah;`,
          `Riewkhuid, kum sngi phyrnai,`,
          `Hangta ki sah.`,
          `Da sur ba thiang ki rwai -`,
          `Їaroh ïa U Khrist U Trai;`,
          `Junom, junom khlem wai,`,
          `Ki yrta bah.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `To wan sha ri basuk,`,
          `Ah! to wan noh;`,
          `U khot ïa phi ba duk,`,
          `Wat ïeng lyngngoh.`,
          `Phin ïoh jingsuk janai,`,
          `Jisu Khrist ïa phi Un ai;`,
          `Phin lait na jingkhuslai,`,
          `To wan baroh`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ha ri ba suk janai,`,
          `Junom ngin shong;`,
          `Lem bad U Khrist U Trai,`,
          `Ngin ïoh ïai long.`,
          `Sha burom, Ah! to phet,`,
          `Їoh ka hima bad ka khet;`,
          `Їa jingkhot wat lyndet,`,
          `Pansngait phin phong.`,
        ],
      },
    ],
  },
  {
    id: "song-474",
    title: "Ka Jingïap ki riewblei",
    metadata: {
      number: 474,
      language: "khasi",
      composer: "S.S. 971",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Jngai, jngai sha lyndet jingkhih erïong,`,
          `Ba beh ha ngi;`,
          `Tang jingtyngshaiñ suda hangta long,`,
          `Phyrnai shai kat ka sngi.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Hangta jingïap, pang bad khuslai,`,
          `Kim pynsngewsih shuh;`,
          `Shen, shen, ngin sa ïashem lang hangta,`,
          `Ryngkat bad Jisu ruh.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Jngai, jngai sha lyndet um ba jylliew,`,
          `Ngan her noh hi;`,
          `Da thapniang jingngeit ngan lait na sniew,`,
          `Shatei sha la ka ri.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Jngai, jngai sha lyndet ka them ba dum,`,
          `Jisu U ïeng;`,
          `U khot ïa ngi sha ka Ri jinghun,`,
          `Ban shong bad U ha bneng.`,
        ],
      },
    ],
  },
  {
    id: "song-475",
    title: "Ngin sa ïeng ha khmat U Trai",
    metadata: {
      number: 475,
      language: "khasi",
      composer: "S.S. 966",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ngin sa ïeng ha khmat U Trai,`,
          `Bad ki angel ngin ïarwai;`,
          `Ynda poi, ynda poi,`,
          `Ngin sa ïaid ha ri jingshai;`,
          `Dap da jingïaroh ï'U Trai,`,
          `Ynda poi, ynda poi.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Ngin sa ïeng ha khmat U Trai,`,
          `Bad ki angel ngin ïarwai;`,
          `Burom, burom, ïa U Trai,`,
          `Haleluïa ! Haleluïa!`,
          `Ngin sa ïeng ha khmat U Trai.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Ngin sa ïeng ha khmat U Trai,`,
          `Ha Jerusalem thymmai;`,
          `Ynda poi, ynda poi,`,
          `Hangta jingsngewsih la wai;`,
          `Hangta ngin ïanguh ï'U Trai,`,
          `Ynda poi, ynda poi.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Ngin sa ïeng ha khmat U Trai,`,
          `Bad u paid byneng kyrhai;`,
          `Ynda poi, ynda poi.`,
          `Hangta sawdong khet U Blei;`,
          `La ki jingïaroh ngin sei,`,
          `Ynda poi, ynda poi.`,
        ],
      },
    ],
  },
  {
    id: "song-476",
    title: "Ka Jinglyngkot ka Jingim",
    metadata: {
      number: 476,
      language: "khasi",
      composer: "JABEZ",
      syllables: "76.76.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ka jingïaid jong nga hangne,`,
          `Sa khyndiat kan sa wai;`,
          `Ka jingkha bad ka jingïap,`,
          `Їakynduh ym jyngai;`,
          `Kan lap ka jingjot shisha,`,
          `Ha kiba sniew ka kam;`,
          `Na kaba thala shane,`,
          `Sha kordit kin sa ngam.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ka jingsngewtynnad mynta,`,
          `Lashai ka sngewsih long;`,
          `Bad kaba nga kheiñ shisha,`,
          `Ka jingïap kan sa rong;`,
          `Ka jingiwbih u syntiew,`,
          `Їa nga bunsien ka phon;`,
          `Shapoh u mih u shiah,`,
          `Khlem shiah ym ju don.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Nga ba ju ïaid sakyma,`,
          `Ha khlaw sharum shaneng;`,
          `Ka mynsiem ka la matlah,`,
          `Ha tymier nga la ïeng;`,
          `Ah Blei! ai bor ban kynriah,`,
          `Narud ka liewlong bah,`,
          `Їoh hangta ngan sa kyllon,`,
          `Nangta ban im ym lah.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Ha jingbishar ba khadduh,`,
          `Ka pyrthei ka la ing;`,
          `Їa nga, kum ka diengtyllaw,`,
          `Na jynjar mynta khring;`,
          `Ah! hangta ei ban kyrshan,`,
          `Ha kaba ding ka meh?`,
          `Kin lynñiar lang ki bymman,`,
          `Na U Blei yn sa beh.`,
        ],
      },
    ],
  },
  {
    id: "song-477",
    title: "U Khrist -- ka Jingmihpat",
    metadata: {
      number: 477,
      language: "khasi",
      composer: "ALL FOR JESUS (Iambic)",
      syllables: "87.87.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Nga long ka jingmihpat ba khraw,`,
          `Ha Nga la paw ka jingim;`,
          `Ha Nga, ba ngeit U Trai U Blei,`,
          `L'u ïap, lawei Ngan pynim.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Da shisha shisha hi, Nga ong,`,
          `Ba long jinglait na jingtim;`,
          `Ї'u briew ba ngeit b'U Blei U phah,`,
          `Їa nga ban ai ka jingim.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ban ngeit ban nguh, sngewbha mynsiem,`,
          `Ban im h'U Jisu Kynrad;`,
          `Na sniew la sait, na ïap la lait,`,
          `Nga shait, nga shem jingpyngngad.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Kat kiba im da ka jingngeit,`,
          `Bad ba ïaid beit khlem bakla;`,
          `Ka jingïap hi kam lah pynsniew,`,
          `Junom ki briew kum kita.`,
        ],
      },
    ],
  },
  {
    id: "song-478",
    title: "Ka sngi khatduh",
    metadata: {
      number: 478,
      language: "khasi",
      composer: "JABEZ",
      syllables: "76.76.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ka jingwan ka sngi khatduh,`,
          `Ka kyrhuh na jyngai;`,
          `Ka pyrta, 'Wad ka tynrai',`,
          `B'Un ïeng bishar U Trai;`,
          `Yn khang ka lad jingisnei,`,
          `Ha ka sngi wan U Blei;`,
          `Ko mynsiem, 'Wad ka tynrai',`,
          `Katta men lyngngoh lei?`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Men bishar ïa ki bynriew,`,
          `Bad im bad ïap kumjuh;`,
          `Naduh ba kut ka pyrthei,`,
          `Kin wan ha sngi khatduh;`,
          `Їa Me ka jem ban isnei,`,
          `Їa nga - Ka jingmap ei;`,
          `Bun hajar sien kham myntoi,`,
          `Їa baroh ka pyrthei.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ha khmat ka khet ngin ïeng,`,
          `Ngin ïeng sa khyndiat sngi;`,
          `Ym don ban kyrshan hangta,`,
          `La'm mih ka hok jong ngi,`,
          `Mynta nga shlan ban kyrpad,`,
          `Ngan beh la im la ïap;`,
          `Ban shem ka hok U Jisu,`,
          `Shuwa bishar la lap.`,
        ],
      },
    ],
  },
  {
    id: "song-479",
    title: "Ka Sngi Bishar",
    metadata: {
      number: 479,
      language: "khasi",
      composer: "BABEL",
      syllables: "76.76.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Kan wan ka sngi ban tynjuh,`,
          `Sa khyndiat ïa u briew,`,
          `Ha uno don ka tynrai,`,
          `Bad jongno dohnud sniew;`,
          `Ah Blei! to ai ban sngewthuh`,
          `Ka bor mynsiem jong Me,`,
          `Ban pynlong hapoh jong nga`,
          `Ka tynrai ba ïaineh.`,
        ],
      },
    ],
  },
  {
    id: "song-480",
    title: "Ka Sngi Bishar",
    metadata: {
      number: 480,
      language: "khasi",
      composer: "GALILEE (Iambic)",
      syllables: "87.87.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Bishar sa long sa khyndiat hi,`,
          `Їa, ngin ïakynmaw kata;`,
          `Haba ki bynriew sha U Trai,`,
          `Kin ai ka jingkheiñ hangta.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Shato kin ïeng lyngngoh lang,`,
          `Ban pydiang la ka bainong;`,
          `Riewrit, riewkhraw, riewduk, riewspah,`,
          `Їoh kumba sah ka jinglong.`,
        ],
      },
    ],
  },
  {
    id: "song-481",
    title: "Ha ka sngi bishar U Khrist",
    metadata: {
      number: 481,
      language: "khasi",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [`Ka sngi bishar ka nang wan poi,`, `Ka stet ka sngi ka ïaid.`],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [`Ah! kan long ka jingïam bah,`, `Ha ka sngi bishar U Khrist.`],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [`Ki nongpop baroh kin mih paw,`, `Ha khmat ka khet U Khrist.`],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `“To khie noh na Nga,”Khrist Un ong,`,
          `‘Sha ding ka bym ju lip.’`,
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [`Ka jinglynñiar bad jingdaitbniat,`, `Junom kan long hangta.`],
      },
      {
        id: "verse-5",
        order: 6,
        type: "VERSE",
        lines: [
          `Ki riewkhuid ruh kin ïa mihpaw,`,
          `Ha khmat ka khet U Khrist.`,
        ],
      },
      {
        id: "chorus-2",
        order: 7,
        type: "CHORUS",
        lines: [`Ah! kan long ka jingkmen bah,`, `Ha ka sngi bishar U Khrist.`],
      },
      {
        id: "verse-6",
        order: 8,
        type: "VERSE",
        lines: [`‘To wan,’ ïa ki, U Khrist Un ong,`, `Ban shong bad U Junom.`],
      },
    ],
  },
  {
    id: "song-482",
    title: "Ka Sngi Bishar",
    metadata: {
      number: 482,
      language: "khasi",
      composer: "DIES IRAE",
      syllables: "87.87.887.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `K'ei nga ïohi, Ah Blei ba khraw!`,
          `Jingpynjot pyrthei la wai;`,
          `Nga i Nongbishar U wan paw,`,
          `Ha ki lyoh ding ba phyrnai.`,
          `(Ka turoi khraw na bneng ka riew,) x 2`,
          `Ki jingtep ki ai la ki briew,`,
          `Sha jingkordit ne jingsuk.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ban lait na jingbitar ba triem,`,
          `Dei da bor ka jingaiei;`,
          `Jaka dang don h'U Nongpynim,`,
          `Ban ïoh jingsuk bad U Blei,`,
          `(Sh'U Blei jingsuk, ka burom ai,) x 2`,
          `Ryngkat bad U ngin im khlem wai,`,
          `Pynkloi ban ïashem bad U.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ko Blei ba hok, to sngew ïa ngi,`,
          `Kiba la ngop ha jynjar;`,
          `Da jingaiei jong Me to ri,`,
          `Na jingshitom pyllait phar.`,
          `(To ai ngin shem ka jakarieh,) x 2`,
          `Kaba la plie h'U Lum Kal'bri,`,
          `Shuwa sngi bitar ka lap.`,
        ],
      },
    ],
  },
  {
    id: "song-483",
    title: "Ban shong bad Jisu junom",
    metadata: {
      number: 483,
      language: "khasi",
      composer: "HEAVEN",
      syllables: "87.88.7.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Haba nga ïeng hangne Ah Trai,`,
          `Nga i ba jingim la wai;`,
          `Da jingngeit nga ïohi na jngai,`,
          `Ka ïing ba la khreh jong Me Trai;`,
          `Ban shong bad Jisu junom.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ha pyrthei dap da jingjynjar,`,
          `Jingtynjuh ruh la lait phar;`,
          `Mynta la mad ka jingsuk jai,`,
          `Ha ïing ba la khreh Jisu Trai;`,
          `Ban shong bad Jisu junom.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Katba nga dang im ha pyrthei,`,
          `Ah Trai theh la jingisnei;`,
          `Ban ïaid bad Me ha la ka sngi,`,
          `Haduh ban poi sha la ka ri;`,
          `Ban shong bad Jisu junom.`,
        ],
      },
    ],
  },
  {
    id: "song-484",
    title: "Ngan don pansngiat ne em?",
    metadata: {
      number: 484,
      language: "khasi",
      composer: "S.S. 787",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ha ka ri itynnad ba U synshar U Trai,`,
          `Ngan leit poi ynda jingtrei la wai;`,
          `Da jingaiei phylla bad Nongpynim ngan long,`,
          `Ngan don pansngiat ne em ba ngan phong?`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Ngan don pansngiat ne em? (2)`,
          `Ba la pyndait da khlur ba phyrnai;`,
          `Ynda jingleit la wai,`,
          `Ha ïing shongneh ngan poi,`,
          `Don ne em ka pansngiat ba phyrnai?`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Katba jingim dang sah ngan shakri la U Trai,`,
          `Ki mynsiem na jingjot ban pynphai;`,
          `Bad ka burom na U ha ka sngi kaba khraw,`,
          `Da ki ktien jemnud tam Un pynpaw.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Ah! jingkmen bym lah ong ynda ïa U ngan shem,`,
          `Ban aiti ki paila ba kordor;`,
          `Jingsuk kata ka ri kan nang bang nang janai,`,
          `Bad ka pansngiat burom ba phyrnai.`,
        ],
      },
    ],
  },
  {
    id: "song-485",
    title: "Ka Jingshongthait ba Bneng",
    metadata: {
      number: 485,
      language: "khasi",
      composer: "S.S. 989 ",
      syllables: "C.M.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ha lynti khlaw, ha ki jingma,`,
          `Sngewbha ban kynmaw teng;`,
          `Ki khuslai baroh kin sa duh,`,
          `Ngin ïoh shongthait haneng.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ynda la mong na bun ki khnam,`,
          `Ki nongshun ba leh meng;`,
          `Shah kaba eh, ba shit ka sngi,`,
          `Ngin ïoh shongthait haneng.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Haba ki wan ki lyoh ban kah,`,
          `Ka khmat U Trai hateng;`,
          `Jingtyngen, haba kynmaw, shem,`,
          `Ngin ïoh shongthait haneng.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Da U Mynsiem Bakhuid jong Me,`,
          `Pynbit ïa ngi ba seng;`,
          `Ba ynda poi ka aïom ïap,`,
          `Ngin ïoh shongthait haneng.`,
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          `La jah ki lok ba ngi ju ieit,`,
          `Harud ka Jordan ïong;`,
          `Sngewbha ban pyrkhat jingïashem,`,
          `Ha Seïon lum kan long.`,
        ],
      },
    ],
  },
  {
    id: "song-486",
    title: "Kaba beh ïa ka Bneng",
    metadata: {
      number: 486,
      language: "khasi",
      composer: "MAELOR",
      syllables: "66.66.88.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ka shnong Kaersalem hun,`,
          `Ah ban da im shatei;`,
          `Khlem wai ïohi ki khun,`,
          `Ka khmat ka jong U Blei.`,
          `Hateng ka dum mynta shisha,`,
          `Ka sngi junom kam sep hangta.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Jyngai nga i ka ri,`,
          `Ba suk, ba bha ka dur;`,
          `U soh kyrhai ba mih,`,
          `Ba shyngiam eh, ba sngur.`,
          `Ah ri ba bha! sha khlieh jingud,`,
          `Їa pha nga beh, ki lok ngan bud.`,
        ],
      },
    ],
  },
  {
    id: "song-487",
    title: "Sa shibit kan sa rang",
    metadata: {
      number: 487,
      language: "khasi",
      composer: "MAELOR",
      syllables: "66.66.88.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `U her u lyoh ba ïong,`,
          `Te mynta la kham shai;`,
          `Ka lyer ba jur ba rong,`,
          `Ka la jan beh ban phai.`,
          `Tang jah ka lyer mynsiem kan ïoh,`,
          `Ka sngi ba rang, khlem slap, khlem lyoh.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Kan ym sah miet te slem,`,
          `Ka dum, ka lyer, ban shah;`,
          `Ngi don tang khyndiat snem,`,
          `Ban bah ka diengphyna.`,
          `Na mihngi ka la sdang ban shai,`,
          `Ka sngi ka jingsuk kam jyngai.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Jingshai ka sngi ka paw,`,
          `Ha ranab lum U Blei;`,
          `Ha ka nga i ka daw,`,
          `B'la pynim ïa nga ei.`,
          `Bad kiba im la thoh ïa nga,`,
          `La shon pynskhem ha ïing I Pa.`,
        ],
      },
    ],
  },
  {
    id: "song-488",
    title: "Wat sheptieng, ko mynsiem",
    metadata: {
      number: 488,
      language: "khasi",
      composer: "WATERSTOCK",
      syllables: "66.66.88.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ko mynsiem, wat shu sah,`,
          `Pyneh, nang ïaid la thait;`,
          `Ka dujok kan ym lah,`,
          `Kan jop ka bor jingsait.`,
          `Ka snam, ka snam, na U b'la jaw,`,
          `Ha khet U Blei ka jur ka daw.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ka khet ba lieh ka lait,`,
          `Ka Magdalen ka nud;`,
          `Manasseh ïong la sait,`,
          `Haneng u nang kynud.`,
          `Nga sngew sur bang jong ki riewkhuid,`,
          `Ki ïaroh ïa ka snam b'la tuid.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ki byllai ki riewngeit,`,
          `B'la poi sha Salem sngur;`,
          `Sha shuwa ki la leit,`,
          `Їa ïaid ka thiep ka jur.`,
          `Ngin bud ka dien u paid U Blei,`,
          `La khang ka ding, la um ka shlei.`,
        ],
      },
    ],
  },
  {
    id: "song-489",
    title: "Ka Ïing i Pa",
    metadata: {
      number: 489,
      language: "khasi",
      composer: "HARLECH",
      syllables: "73.73.7773.73.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ha neng don bun ki pulit,`,
          `Їing I Pa;`,
          `Te hangta lait jingkordit,`,
          `Їing I Pa.`,
          `Ka dohnud ka ïoh pyngngad,`,
          `Ha shadem Jisu Kynrad;`,
          `Ha wah jingim bym ryngad,`,
          `Їing I Pa;`,
          `Bad ki riewkhuid itynnad,`,
          `Їing I Pa.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Khublei! ka ri jingtyngen,`,
          `Їing I Pa;`,
          `Ka ri ban buh jingkyrmen,`,
          `Їing I Pa.`,
          `Ka ri long soh ba thiang,`,
          `Ka ri sha khlieh ka jingpang;`,
          `Shato shu poi la biang,`,
          `Їing I Pa;`,
          `Ah Jisu! lam sha shiliang,`,
          `Їing I Pa.`,
        ],
      },
    ],
  },
  {
    id: "song-490",
    title: "Ka Bneng",
    metadata: {
      number: 490,
      language: "khasi",
      composer: "MERIONYDD",
      syllables: "76.76.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Sha pha ka ri ba ieit,`,
          `Ka khymat ka ïai peit;`,
          `Tang lap ba shem ka kyrteng,`,
          `Mynsiem shato ka leit.`,
          `Shu kynmaw ïa ka burom,`,
          `Ka dohnud ka la hun;`,
          `Ka dawai ïa ka jingpang,`,
          `Jingieit khlem jingshun.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ha kper ka jingsuk janai,`,
          `Ka ri jingkymen hi;`,
          `Junom ummat la ryngad,`,
          `Ka sngewsih kam ju mih.`,
          `U Khun U tyngshaiñ hangta-`,
          `Khunlangbrot jong U Blei;`,
          `Ki paidbah ruh ba kyrkhu,`,
          `Nongsiewspah ka pyrthei.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Їa ka jingphyrnai jong ka,`,
          `Ym don ba lah ïalap;`,
          `Sha shnong U Kynrad jong nga,`,
          `Ban poi ei ban ïarap?`,
          `Їa ei na jong ka khyndew,`,
          `Їa pha ngan nujor te;`,
          `Ї'u Jasper ne ï'u Paila,`,
          `Mawlynnai kordor eh?`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Ka shnong ba tyngshaiñ suda,`,
          `Ka shnong ka ksiar hi;`,
          `Ki lynti ruh la siang,`,
          `La pun mawleiñ ba lieh.`,
          `Ki kynroh ker ka byneng,`,
          `Naduh ki yrta bah;`,
          `Bad ïa ki nongrim khadar,`,
          `Ki phyrnai eh shisha.`,
        ],
      },
    ],
  },

  {
    id: "song-491",
    title: "Ka Jerusalem ba thymmai",
    metadata: {
      number: 491,
      language: "khasi",
      composer: "EWING",
      syllables: "76.76.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Jerusalem ba thymmai,`,
          `Shato sha neng ka shngaiñ;`,
          `La ïong, la tyngit hangne,`,
          `Sha shnong ngin ïoh tyngshaiñ;`,
          `Sngewtynnad her ban kynmaw,`,
          `Ka jinglong ynda wai;`,
          `Ban kyrmen ha ka jynjar,`,
          `Ban ïoh long sriem ï'U Trai.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ha Lum Seïon ngin ïaïeng,`,
          `Ngin ïakmen baroh lang;`,
          `Ryngkat kin long ki angel,`,
          `Їa kajuh kin ïanang.`,
          `Ka tynrai ka jingïaroh,`,
          `U angel bad u briew;`,
          `Ban im ma nga u bymman,`,
          `Ka dor ka snam la siew.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ka ri sngewpyngngad suda,`,
          `Ka shnong U Khun U Blei;`,
          `Ka ri jingkyrkhu shisha,`,
          `Ban wad ngin lyngngoh lei?`,
          `Ah isnei, Jisu Kynrad,`,
          `Shaneng sha suk ïalam;`,
          `Sha khlaw la'n ïehnoh marwei,`,
          `Ha jynjar ngan sa ngam.`,
        ],
      },
    ],
  },
  {
    id: "song-492",
    title: "Ka Jingkyrmen ïa ka Bneng",
    metadata: {
      number: 492,
      language: "khasi",
      composer: "KILMOREY",
      syllables: "76.76.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Nga hangne ha ka jynjar,`,
          `Їai ud ïa la jingsniew;`,
          `L'U Jisu ngam ïoh khymih,`,
          `U Ksiang jong u briew.`,
          `Sa khyndiat ngan sa jyngi,`,
          `Ban shem ka jingsuk jai;`,
          `Їohi l'U Jisu junom,`,
          `Sha shiliang, khlem da wai.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Nym tip ka pop ha byneng,`,
          `La khuid ka jinglong phar;`,
          `Junom junom shu kymen,`,
          `La khlaw ka dohnud nar;`,
          `Ka met ka jong ka jingïap,`,
          `Ka pop kam ïeng shuh;`,
          `La ïuh ha trai Lum Seïon,`,
          `Ngin khawai junom duh.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ha ka sngi lap ka jingïap,`,
          `Ban khawai dang sydang;`,
          `Bad katba roi u paidlang,`,
          `Ka kymen ka nang bang.`,
          `Na jingtep ynda kyrsiew,`,
          `Їa ki riewkhuid sha lait;`,
          `Ka jingshad kymen jong ki,`,
          `Sha bymjukut kan shait.`,
        ],
      },
    ],
  },
  {
    id: "song-493",
    title: "Ka Jingkmen ha Bneng",
    metadata: {
      number: 493,
      language: "khasi",
      composer: "JOYFUL",
      syllables: "776.667.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Hangne shah ka pang ka sat,`,
          `Hangne shem ban khlad noh pat,`,
          `Ha bneng ngin ym khlad shuh.`,
          `Ah! kata ban sngewbha,`,
          `Ah! kata ban sngewbha,`,
          `Ngin ïashem ban ym khlad shuh.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Hangne jar ba ieit ï'U Blei,`,
          `Haba ïap, ha khlieh pyrthei,`,
          `Kin riwai ha byneng`,
          `Ah! kata ban sngewbha.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Khynnah khuid ba duwai Blei,`,
          `Ha Skul Pynpaw kiba trei,`,
          `Kin poi suk ha byneng.`,
          `Ah! kata ban sngewbha.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Ha ïing U Blei ruh ngin shem,`,
          `Ki Apostol ba ki dem,`,
          `Ї'U Jisu Khrist U Trai`,
          `Ah! kata ban sngewbha.`,
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          `Ah! suk katno ngin ïoh im,`,
          `Tang ban peit sh'U Nongpynim,`,
          `B'U dap ka burom Blei.`,
          `Ah! kata ban sngewbha.`,
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          `Ynda poi ha khlieh ki lyoh,`,
          `Hangta junom ngin ïaroh,`,
          `Ї'U Jisu? Syiem jingim.`,
          `Ah! kata ban sngewbha.`,
        ],
      },
    ],
  },
  {
    id: "song-494",
    title: "Ka Jingsngewbha ha Bneng",
    metadata: {
      number: 494,
      language: "khasi",
      author: "H. R.",
      syllables: "87.87.D.",
      songId: "song-494",
      tune: "ESTHER",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "K'ei ka jingim jong u bynriew?",
          "Shibit shen, kan kynran noh;",
          "K'ei ka jingim? tang ka syrngiew,",
          "Ynda kynran pat ym ïoh.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Her, ko mynsiem, her sha jerong,",
          "Lei men ieit ïa ka pyrthei?",
          "Her noh nangne, wad ïa la shnong,",
          "Ka shnong khuid jong ki riewblei.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ah ka burom! Ah ba tyngshaiñ!",
          "Ban ïalap ruh hi ym lah;",
          "Hangta ha ka jinglong U Blei,",
          "I ï'U Jisu shai khlem kah.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Sawdong jong U ki nongïaroh,",
          "Bun bah byllien ki ïashad;",
          "Ba pynher la ki jingkynud,",
          "Na l'U Kynrad kim ju khlad.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Nga pynbeit la ka duitara,",
          "Ban ïoh riwai ynda poi;",
          "Nga pynpyiar la ki thapniang,",
          "Ban her nangne nga la kloi.",
        ],
      },
      {
        id: "chorus-2",
        order: 6,
        type: "CHORUS",
        lines: [
          "Her, ko mynsiem, her noh mynta,",
          "Ka pyrthei ïa nga ynnai;",
          "Her noh nangne, wad ïa la shnong,",
          "Ka shnong khuid ba shong U Trai.",
        ],
      },
    ],
  },
  {
    id: "song-495",
    title: "Tem Duitara",
    metadata: {
      number: 495,
      language: "khasi",
      composer: "KA DUITARA KSIAR",
      syllables: "87.87.47.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ha ka shadem khuid jong U Blei,`,
          `Khun ka jingïap kin shongthait;`,
          `Hangto kin sngewphylla junom,`,
          `Ba ka dujok ki la lait.`,
          `Їaroh ï'U Blei,`,
          `Ha byneng kan ym kut shuh.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Yn ïai riwai, yn ïai ïaroh,`,
          `Ynda lait ki yrta bah;`,
          `Їa U Jisu, U Nongpynim,`,
          `B'U la ïap ha diengphyna.`,
          `Tem duitara,`,
          `Ha byneng kan ym kut shuh.`,
        ],
      },
    ],
  },
  {
    id: "song-496",
    title: "Ka Jingkwah ïa ka Bneng",
    metadata: {
      number: 496,
      language: "khasi",
      composer: "S.S. 335",
      syllables: "88.88.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ki thapniang u sim ban da ïoh,`,
          `Sha kliar lum Nebo ngan her;`,
          `Te hangta ha lyndet ki lyoh,`,
          `Sha ri ba kham bha ngan kyner.`,
          `Te ki sngi ka jingim kin leit,`,
          `Ban khymih sha lyndet ka um;`,
          `Da ïaroh ï'U Jisu ba ieit,`,
          `B'la ïap da ki nar ha u lum.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Nga sngew ka rud wah ka la jan,`,
          `Ka khlaw ruh sa khyndiat la wai;`,
          `Ka kyrmen ka jong nga ka wan,`,
          `Na kaba U ryngkang U Trai,`,
          `U khyllie ï’u maw b'la shon shab,`,
          `Na jingtep U mih, U Bakhlaiñ;`,
          `Nga ieit la im ruh la ïap,`,
          `Jingmong jong u rangli U spaiñ.`,
        ],
      },
    ],
  },
  {
    id: "song-497",
    title: "Ka jingshad kmen ki Riewkhuid",
    metadata: {
      number: 497,
      language: "khasi",
      composer: "OLD DERBY",
      syllables: "98.98.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ki wah bah jingkymen ki kyrsoi,`,
          `Na shapoh khet ksiar U Blei;`,
          `Te hangta la kyntiew ï'U Jisu,`,
          `Bad hangta U ïeng ïasaid ei.`,
          `Ka snam b'la pynhun ïa ka hukum,`,
          `B'la synreit ruh halor ka khet;`,
          `Ka hangta ka kyrpad sngewsynei,`,
          `Ka synrang ba skhem ba ngin phet.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ngin kiew noh na ka khlaw ba kynsha,`,
          `Ngin ïoh ïa ka jingsuk ba skhem;`,
          `Ka mynsiem ba lywait ka kynjai,`,
          `Ha shadem jong U Blei kan shem.`,
          `Jinglait ngin ïoh junom te hangta,`,
          `Ka pop bad jingjynjar la wai;`,
          `Ngin khawai ki yrta bymjukut,`,
          `Jingieit U Jisu U Trai.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Na kliar lum jerong Kaersalem`,
          `Ka jingieit ri khlaw ngin ïohi;`,
          `Hangta ki jingkyllaiñ ka lynti,`,
          `Jingbang ka mynsiem kin pynmih.`,
          `Ngin khymih ki erïong, jingsheptieng,`,
          `Jingïap ba itriem, ka jingtep;`,
          `Te hangta ngin lait na ki baroh,`,
          `Ka sngi jong ka jingsuk kam sep.`,
        ],
      },
    ],
  },
  {
    id: "song-498",
    title: "Ka Salem shaneng",
    metadata: {
      number: 498,
      language: "khasi",
      composer: "CRUGYBAR",
      syllables: "98.98.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ah Salem! ka shnong kaba ieit,`,
          `Ka kyrteng jong pha nga sngewbha;`,
          `Te lano kan wai noh jingshitom,`,
          `Da kymen bad ïaroh ha pha?`,
          `Te lano ki khmat kin ïoh khymih.`,
          `Ki khyrdop mawlynnai ba rem;`,
          `Ki lynti ka ksiar ba tyngshaiñ,`,
          `Ki kynroh ruh kiba sah skhem?`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ah Salem! ka shnong U Trai jong nga,`,
          `Te lano ngan ïoh poi sha pha?`,
          `Ha kaba kam wai jingïasyllok,`,
          `Jinghun ruh te junom kan sah.`,
          `Ka jingsuk ba khuid ka don hangta,`,
          `Їa jingsuk ka Eden kham brai;`,
          `Ka jingshai kham tyngshaiñ ïa ka sngi,`,
          `Ka jingshai na khmat jong U Trai.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ah! jaka itynnad ba suk ruh,`,
          `Ban poi hapoh hangta nga kwah;`,
          `Shen shen ngan ïoh lait na jingshitom,`,
          `Ki erïong ki hadien, dang sah.`,
          `Te balei ka pang lane shitom,`,
          `Jingïap ki pynsheptieng, ki ban?`,
          `Ka ri ka jingkular nga ïohi,`,
          `Ka Kanaan bymjukut ka jan.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Don hangta nongriwai ba tyngshaiñ,`,
          `Ki riwai ï'U Jisu U Trai;`,
          `Don hangne ki lok ki ban kiew ruh,`,
          `Ban ïaroh bad kita khlem wai.`,
          `Ah Salem! ïing jong nga ba ieit,`,
          `Ka dohnud ka kwah ban ïohi;`,
          `Te hangta jingshitorn kan kylla,`,
          `Ka jingsuk ba kynjai ha khlieh.`,
        ],
      },
    ],
  },
  {
    id: "song-499",
    title: "Ka ri ba sngewtynnad",
    metadata: {
      number: 499,
      language: "khasi",
      composer: "S.S. 964",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Don ka ri ba sngewtynnad hir hir,`,
          `Kiba ngeit kin ïohi na jyngai;`,
          `Ba I Pa I dang ap harud um,`,
          `I la thaw ka ïing hun bad U Trai.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Ah jinghun! sha byneng!`,
          `Ngin sa shem ka jinghun sha byneng.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Ki jingkynud ba bang ki riewblei,`,
          `Ngin ïoh riwai ha kata ka ri;`,
          `Ka mynsiem kan ym khuslai ei ei,`,
          `Ka la her ban suk kynjai ha khlieh.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `To ïakhymih sha kata ka ri,`,
          `Ngin ïabeh la i nangne ba jngai;`,
          `Ngin ïabam ka lyer pyngngad iwbih,`,
          `Ka jingkyrmen U Kpa U la ai.`,
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          `Da ka snam ïa ka lynti la thaw,`,
          `Ba ngin poi sha ri hun da jingmap;`,
          `Riew Hosanna ï’U Kpa ba sybun,`,
          `B’U la ai la U Khun ban shah ïap.`,
        ],
      },
      {
        id: "verse-5",
        order: 6,
        type: "VERSE",
        lines: [
          `Ї’U Nongpynim ba ieit, ba khraw,`,
          `Ka jingnguh ngin ïa-ai, ngin ïaroh;`,
          `Ba sha lyndet ka jingïap la thaw,`,
          `Їa u bynriew ka jingsuk ban ïoh.`,
        ],
      },
    ],
  },
  {
    id: "song-500",
    title: "Ka Byneng",
    metadata: {
      number: 500,
      language: "khasi",
      composer: "HEAVEN",
      syllables: "87.88.7.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ynda la wai jingleit pyrthei,`,
          `Jingjynjar bun ruh kylleng,`,
          `Ka long ka dawai ba pynhun;`,
          `Їa ka shadem ba tlot ba ñuin,`,
          `Ban ïoh shongthait ha byneng.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ah! haba khih ki erïong bah,`,
          `Sngewbang ban kynmaw hateng,`,
          `La ki lyer khraw ki beh jyndei;`,
          `Katba ngi ïaid duriaw pyrthei,`,
          `Ka jingsuk jai ha byneng.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `La hangne don ki nongshun bun,`,
          `Ba pynsaja ba leh meng,`,
          `Ha lyndet wah jingïap ba shlei;`,
          `Ha duriaw bah jinghun U Blei,`,
          `Ngin ïoh jingsuk, ha byneng.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Te mynta don ki lok ba ieit,`,
          `Ha ri ka jingsuk shaneng,`,
          `Kim sngew ei ei ba pynkhuslai;`,
          `Jingshitom baroh ka la wai,`,
          `Ki riwai hin ha byneng.`,
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          `La ïaid ha them jingsngewsih slem,`,
          `Da bud riewkhuid bun pateng,`,
          `Ki ummat Un ñiad noh U Trai;`,
          `Jingud kin kylla jingriwai,`,
          `Junom junom ha byneng.`,
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          `Mynsiem jong nga ka kwah ban i.`,
          `Ka shnong na Me b'la kyrteng,`,
          `Ko Blei, ko Jisu, ko I Pa;`,
          `To ai ngan wan sha ri ba bha,`,
          `Ban ïaroh jam ha byneng.`,
        ],
      },
    ],
  },
  {
    id: "song-501",
    title: "Ka ri sngewbha sha khlieh",
    metadata: {
      number: 501,
      language: "khasi",
      composer: "S.S. 67",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Don ka ri ba sngewbha sha khlieh,`,
          `Ha ka burom ka ai ngan mih;`,
          `Ha ka sngewsih nga shong, pansngiat kwah phong,`,
          `Ha ka ri ba sngewbha sha khlieh.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Ngan ïoh ri itynnad U Trai,`,
          `Ka khuslai pyrthei la wai;`,
          `U Jisu, ha ka, U leit ban ïashna,`,
          `Ka jaka ba ngan suk jai.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Don ka ri ba sngewbha sha khlieh,`,
          `Bad ki lok ha ka, suk ki rieh;`,
          `Nga sngew kumba i ba ki ap te ïa ngi,`,
          `Ha ka ri ba sngewbha sha khlieh.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Don ka ri ba sngewbha sha khlieh,`,
          `Bad la hangne ka ïam ka mih;`,
          `N'U Jisu ka paw ba ki ummat kim jaw,`,
          `Ha ka ri ba sngewbha sha khlieh.`,
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          `Don ka ri ba sngewbha sha khlieh,`,
          `Ktien ‘Khublei’ ban ïa khlad kam mih;`,
          `Sha shiliang ka wah ngi la lait ka jingma,`,
          `Ha ka ri ba sngewbha sha khlieh.`,
        ],
      },
    ],
  },
  {
    id: "song-502",
    title: "Junom bad la U Trai",
    metadata: {
      number: 502,
      language: "khasi",
      syllables: "66.86.66.86.6.6",
      songId: "song-502",
      tune: "NEARER HOME",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah! junom bad U Trai,",
          "Shaneng to shah ngan shong;",
          "Ha kane im mynsiem khlem wai,",
          "Ka ktien ba im ka long.",
          "Shane ha ruh la set,",
          "Bad jngai na u ka ring;",
          "Te ha la ka sngi nang ïaphet,",
          "Kham hajan sha la ïing.",
          "Sha la ïing, sha la ïing,",
          "Kham hajan sha la ïing.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ka ïing I Pa sha khlieh,",
          "Sha shnong ruh nga la jan;",
          "Hateng ka jingngeit ka ïohi,",
          "Ban shaw b'Um pep ban wan.",
          "Ban poi ha shnong U Syiem,",
          "Nga thrang mynsiem hateng;",
          "Ka jingïoh bynta ki baim,",
          "Ka Salem sha byneng,",
          "Sha byneng, sha byneng.",
          "Ka Salem sha byneng.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Artatien ka wan lap,",
          "Jingtyngen ruh ka her;",
          "Kum ïa ka paro jong u Noah,",
          "Ba ban ka um ka lyer,",
          "La ryngaw shibit sngi,",
          "La pei la paw byneng;",
          "La hun ban i ka rud ka ri,",
          "Ba shato ngin ïashem.",
          "Ngin ïashem, ngin ïashem,",
          "Ba shato ngin ïashem.",
        ],
      },
    ],
  },
  {
    id: "song-503",
    title: "Ka ri basuk",
    metadata: {
      number: 503,
      language: "khasi",
      composer: "HAPPY LAND (R.S. 680)",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Don ri ba suk janai, jyngai, jyngai,`,
          `Hangta riewkhuid tyngshaiñ, shai kat ka sngi.`,
          `Ah katno ki ïarwai,`,
          `Їaroh ï'U Nongpynim Syiem!`,
          `Kin ïaroh jam sngewbha, - Їaroh junom.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `To wan sha ri ba suk, - Ah to wan kloi,`,
          `Phin ïaïeng lyngngoh lei, phin tud lei, lok!`,
          `Jingsuk ngin ïoh pakai,`,
          `Ynda pop bad sngewsih lait,`,
          `Ngin ïoh im bad U Trai, - Suk, suk, junom.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Suk, shngaiñ ngin long hangta, tyngshaiñ ki khmat,`,
          `Da kti U Kpa la ri - jingieit kam ïap.`,
          `Ah phet sha burom te,`,
          `Wan long syiem bad lyngdoh Blei,`,
          `Tyngshaiñ, neng bad sngi de, -- Ngin suk junom.`,
        ],
      },
    ],
  },
  {
    id: "song-504",
    title: "Ynda ngin poi lang ha Bneng",
    metadata: {
      number: 504,
      language: "khasi",
      composer: "R.S. 400",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `To rwai ïaroh ïa U Jisu,`,
          `Bad ïa jingieit ba phylla;`,
          `Ha ki ïing shongneh ba phyrnai,`,
          `U la leit ban khreh jaka.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Ynda ngin poi lang ha bneng,`,
          `Ka jingkmen bah hangta kan long ïa ngi;`,
          `Haba i ï'U Jisu,`,
          `Ngin ïaroh jingjop Kalbari.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Haba ngi ïaid lynti pilgrim,`,
          `Ki lyoh ba dum kin sa shai;`,
          `Ynda ki sngi jingleit la wai,`,
          `Junom ngin shong bad U Trai.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Long ba shisha bad ba ngeit skhem,`,
          `Ha jingshakri ïa U Trai;`,
          `Tang shu peit ïa U ha burom,`,
          `Jingkhuslai baroh la wai.`,
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          `Nang ïaid shaphrang pansngiat Un ai,`,
          `Їeng skhem bad shaniah ha U;`,
          `Shen ki plie ki khyrdop phyrnai,`,
          `Bad ngin ïohi l'U Jisu.`,
        ],
      },
    ],
  },
  {
    id: "song-505",
    title: "Riewhok u shong ha Bneng",
    metadata: {
      number: 505,
      language: "khasi",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Riewhok u shong ha byneng,`,
          `Bad U Blei bad Khun;`,
          `U ïai ïaroh, u ïai ïaroh,`,
          `Ї'U Blei Uba la ieit bad isynei.`,
          `Ki la poi suk ha ïing I Pa,`,
          `Bad riewkhuid ki tem jingkynud;`,
          `Jingriew bneng, ïaroh ï'U Blei,`,
          `B'u ri pynim ei.`,
        ],
      },
    ],
  },
  {
    id: "song-506",
    title: "Ka Bneng ba thymmai",
    metadata: {
      number: 506,
      language: "khasi",
      composer: "S.S. 819",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Don ka Ri nga ïohi ha lyndet jong ki lyoh;`,
          `Itynnad bad phyrnai kum ka sngi,`,
          `Lyer ba iwbih ki ïai beh ruh junom hangta,`,
          `Ah! jingkmen jingsuk phin ïoh shisha.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `Ah! Jingkmen, Ah! jingsuk`,
          `Ka pyndap ïa mynsiem`,
          `Dei hangta nga ïoh mad ïa jinghun ba kynjai`,
          `Ha kata ka ri hun bad, U Trai.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Ka nongbah ba la shna da ka ksiar nylla,`,
          `Bad pyndait ruh da maw bakordor.`,
          `Don khadar ki khyrdop ba phin ïoh rung hangta,`,
          `Ї'u b'la sait ha ka snam khunlangbrot.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Nongbah ba dap jingsuk, lano ngan ïoh ïa pha;`,
          `Jingpang, jingïap bad khuslai la wai`,
          `Ngin ïarwai, ngin ïabam na u dieng ka jingim`,
          `Bad junom, ngin ïaroh ïa, u Syiem.`,
        ],
      },
    ],
  },
];
