import { SongT } from "@repo/types";

export const shaphangUMynsiemBakhuid = [
  {
    id: "song-115",
    title: "Shaphang U Mynsiem Bakhuid",
    metadata: {
      number: 115,
      language: "khasi",
      author: "J.C.E.",
      composer: "Alexander",
      syllables: "87.87.D",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Shuwa ba Un leit sha byneng,`,
          `Jisu U la kular ei;`,
          `Ba Un phah ha ngi l'U Mynsiem,`,
          `Ha ka Balang ban ïai trei;`,
          `Ïa ki synran, ka la biang,`,
          `Ka jingaiei U Mynsiem.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `La jingkular U la pyndep,`,
          `Ynda sha byneng U kiew;`,
          `Te U Mynsiem U la hiar,`,
          `La pynim ki hajar briew;`,
          `Ha ka Pentekost la burom,`,
          `Ïa ka kyrteng Jisu Khrist.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ka jingkular rim jong U Blei,`,
          `Ka dang biang eh ïa ngi;`,
          `Mynta te ngi lah ban duwai,`,
          `Ba Un wan U Mynsiem hi;`,
          `Ah Trai Jisu, ïa ngi kynmaw,`,
          `Theh noh shibun U Mynsiem.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Ah Mynsiem Bakhuid jingkular,`,
          `Wan da jingai jong Me hi;`,
          `Me ba isnei bymju kylla,`,
          `Da ka bor to trei ha ngi;`,
          `Pynim, pynshai ïa ki bymman,`,
          `Pynlong smat ïa la ki briew.`,
        ],
      },
    ],
  },
  {
    id: "song-116",
    title: "To Khie, Ko Ksangti U Trai",
    metadata: {
      number: 116,
      language: "khasi",
      author: "J.R.",
      composer: "Dymuniad",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `To khie, to khie, kup la ka bor,`,
          `Ko ksangti kor U Kynrad;`,
          `Kumba Me leh ha mynbarim,`,
          `Pynim, pynshait, ngi kyrpad.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ban meh ka ding byneng, Ah Blei,`,
          `To trei, to phah l'U Mynsiem;`,
          `Lem bad ki ktien bakhuid, Ah Trai,`,
          `To ai ka bor ban pynim.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ah Trai, ha ngi ai kylluid War,`,
          `Ka kular jong U Kypa;`,
          `U Mynsiem hi ha la jingtrei,`,
          `To pyndei ha ngi mynta.`,
        ],
      },
    ],
  },
  {
    id: "song-117",
    title: "Ka Kam U Mynsiem",
    metadata: {
      number: 117,
      language: "khasi",

      composer: "Dyfrdwy",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `To hiar Mynsiem Bakhuid ha ngi,`,
          `To pynshai ha ki dohnud;`,
          `Mynsiem U Khrist Me long ma Me,`,
          `Ale, ïa ngi ban pynkhuid.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Jingim, jingkyrmen bad jingshai,`,
          `Ki long jingai ki jong Me;`,
          `Ki khymat jong ngi to pynsleh,`,
          `Da jingsleh kordor jong Me.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Nongshun jong ngi baroh to beh,`,
          `Ka jingsuk de ai hapoh;`,
          `U Nongïalam jong ngi U Blei,`,
          `Ban bha kin ïatrei baroh.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Hikai ithuh ï'U Blei U Kpa,`,
          `U Khun ba bha bad ïa Me;`,
          `Uwei U Blei na bymjukut,`,
          `Uba long Laingut ruh de.`,
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          `Ban ïaroh ï'U Blei ba isnei,`,
          `Ha pateng bynriew baroh;`,
          `U Kpa, U Khun bad U Mynsiem,`,
          `Laingut syriem ban ïaroh.`,
        ],
      },
    ],
  },
  {
    id: "song-118",
    title: "U Mynsiem U Khrist",
    metadata: {
      number: 118,
      language: "khasi",

      composer: "Dymuniad",
      syllables: "87.87",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Mynsiem ba bha sha ngi to wan,`,
          `Da lam ka jingshai byneng;`,
          `Me long Mynsiem U Khrist ba nang,`,
          `Ka sniew ban wiang kylleng.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ka dohnud jong ngi to pynshai,`,
          `Ah Trai, to ai jingshisha;`,
          `Ba ngin ïa ing jingrhem ba im,`,
          `Ka mynsiem ha la ka rta.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Jingieit, jingkyrmen, jingim hi,`,
          `Dei ki jingai ki jong Me;`,
          `Da kine shem b'U Blei U trei,`,
          `B'U sei ka bymman shane.`,
        ],
      },
    ],
  },
  {
    id: "song-119",
    title: "Ka Bor U Mynsiem Bakhuid",
    metadata: {
      number: 119,
      language: "khasi",
      composer: "Blackbourn",
      syllables: "C.M",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ko lyer byneng ïa mynta beh,`,
          `Ba ka sngi kan sa noh;`,
          `Namar ka kyrteng jong Me theh,`,
          `Mynsiem, jingshait ngin ïoh.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ah bor byneng bym ju shah jop,`,
          `Pynpaw ïa Uba ïap;`,
          `Ka jor ka snam ï'u briew b'la ngop,`,
          `Sha jingjot ban sa hap.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ah Nongpyntyngen ka Balang,`,
          `Ha pydeng jong ngi shong;`,
          `To nang ïalam ba ngin ïanang,`,
          `Nongbeh jingkhuid ban long.`,
        ],
      },
    ],
  },
  {
    id: "song-120",
    title: "Ka Jingduwai Ban IohÏa U Mynsiem",
    metadata: {
      number: 120,
      language: "khasi",
      author: "H.R.",
      composer: "Bangor",
      syllables: "C.M",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `To phah ma Me ïa U Mynsiem,`,
          `Ba dawa Jisu hi;`,
          `Ka jingtrei jong U kum ka ding,`,
          `Ah phah ïa U sha ngi.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Kat kum ka kular kaba kor,`,
          `Shah ba yn theh na neng,`,
          `Ïa U Mynsiem Bakhuid ka bor,`,
          `U Blei, ha ngi ba seng.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Kat kum ka mon jong Me, Un wan,`,
          `Pynkynduh ïa ki briew;`,
          `Ïa ki nongïoh byneng ban tan,`,
          `Ba shatei kin ïoh kiew.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Kumba Me kular, Trai ba khraw,`,
          `Shah ba Un hiar kloi;`,
          `U Nongpyntyngen sha ri khlaw,`,
          `Ha ngi ka dei b'Un poi.`,
        ],
      },
    ],
  },
  {
    id: "song-121",
    title: "Ka Jingialam U Mynsiem",
    metadata: {
      number: 121,
      language: "khasi",
      composer: "S.S. 493",
      syllables: "Irregular",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `To wan Mynsiem, to Men pynkhleiñ,`,
          `Ki kyjat thait jong nga;`,
          `Ai ngan ïohi da ka jingngeit,`,
          `Kata ka ri ba bha.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ba ngan iehnoh ïa ka ri khlaw,`,
          `Ri shitom bad jingpang;`,
          `Ïaid ruh sha ri ki jingsngewbha,`,
          `Jong ka ki ïaisah bang.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Nga sah ha kynroh kum nongap,`,
          `Ba ap jingshai ka sngi;`,
          `Nga kwah kan mih ka sngi ba khraw,`,
          `Ka jingjop Kalbari.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Ki jingsngewbha pyrthei la jah,`,
          `Jingbang jong ki la duh,`,
          `Ym don ba sah ka jingsngewbha,`,
          `Tang ïaroh Jisu shuh.`,
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          `Mynsiem ba bha, Me la ïalam,`,
          `Riewkhuid ruh mynbarim;`,
          `Ïa nga ruh to bytin ma Me,`,
          `Ha lynti kaba im.`,
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          `Bun jingpynpep, jingjynjar ruh,`,
          `Pynbakla ha ri khlaw;`,
          `Me, Nongpyntyngen kiba tlot,`,
          `Me, Nongïalam ba khraw.`,
        ],
      },
      {
        id: "verse-7",
        order: 7,
        type: "VERSE",
        lines: [
          `Kat kiba la ïalam ma Me,`,
          `Ki long ki khun U Blei;`,
          `Ïalam ïa nga ha ki jingeh,`,
          `Da bor ka jingaiei.`,
        ],
      },
    ],
  },
  {
    id: "song-122",
    title: "U Mynsiem Ha Ka Ri Them",
    metadata: {
      number: 122,
      language: "khasi",
      composer: "Bryngwyn",
      syllables: "L.M",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ko Nongpynim ki nongïap hi,`,
          `Wan da l'U Mynsiem ban pynkhih;`,
          `To pyrsad jur ha ka ri them,`,
          `Ban im ki shyieng b'la ïap la slem.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Mynsiem Bakhuid jong Me na neng,`,
          `To phah kyrhai ha ngi kylleng;`,
          `Ki dohnud jong ngi Un pyndap,`,
          `Ïing Blei ngin long, b'Un shong ïarap.`,
        ],
      },
    ],
  },
  {
    id: "song-123",
    title: "Ka Jingkha Arsien",
    metadata: {
      number: 123,
      language: "khasi",
      composer: "Old Hundredth",
      syllables: "L.M",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Baroh ki rukom niam blei,`,
          `Kat kiba don ha ka pyrthei;`,
          `Ka snam, lymne ka mon u briew,`,
          `Kim lah pynkylla dohnud sniew.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ka bor U Blei tang kata hi,`,
          `Ba lah pynim mynsiem jong ngi,`,
          `Pynkha ïa ngi ha dur U Khun;`,
          `To pynlong lok ïa ki nongshun.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `U Mynsiem, kum ka lyer ha them,`,
          `U pyrsad ha ki khun jingrem;`,
          `U pynkha arsien ruh ïa ki,`,
          `U sait ka pop ka dohnud hi.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Ki mynsiem jong ngi to pynkhih,`,
          `Na kaba thiah ïap jong ki;`,
          `To pynim pat, ba ngin ïoh ïeng,`,
          `Ban ïaid ka lynti sha byneng.`,
        ],
      },
    ],
  },
  {
    id: "song-124",
    title: "Ka Bor U Mynsiem Ha Ka Doh nud",
    metadata: {
      number: 124,
      language: "khasi",
      composer: "Calfari",
      syllables: "87.87.47",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Bor ki jong Mynsiem Bymjukut,`,
          `Ha ka jor ka kuna Blei;`,
          `Ki ban pynlong dohnud runar,`,
          `Ïa ki soh ba bha ban sei;`,
          `Ah ki jingthung,`,
          `Soh jingaiei U Mynsiem.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ki mawsiang Salem bymman,`,
          `Ki b'la pyrta ban pynduh,`,
          `Ïa U Khun ka burom —‘shim noh,`,
          `To sahnarphyna ïa U!’`,
          `Me la dung ngak,`,
          `Kita ki la jem la ïam.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Lada'n wan Mynsiem ba jemnud,`,
          `Ha ki dohnud kum jong ngi,`,
          `Pynitynnad ïa ki baroh,`,
          `Da ka snam U Jisu hi,`,
          `Ka jingïaroh,`,
          `Ha byneng kan sawa jam.`,
        ],
      },
    ],
  },
  {
    id: "song-125",
    title: "Ka Jingpyntgen U Mynsiem",
    metadata: {
      number: 125,
      language: "khasi",
      composer: "Rhyddid",
      syllables: "76.76.D",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ah Mynsiem khuid ka byneng,`,
          `Mynshuwa ba ngan ïap,`,
          `Da jinghikai sngewtyngen,`,
          `Shah ba ngan shem jingmap.`,
          `Ka jingmap, Ah ka jingmap!`,
          `Ka jingmap phar ba-ei,`,
          `Long shuwa eh ba nga wad,`,
          `Ha snam U Khun U Blei.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Don ha U bor bymjukut,`,
          `Jingstad ba khraw ba-ei;`,
          `Bun phew klur ki jor ba bha,`,
          `Ha snam jong U ki shlei;`,
          `Ha U ki kynja baroh,`,
          `Ba uba pop u kwah,`,
          `Napoh bun jingartatien,`,
          `Sha neng un lait im bha.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Ka dei ïa nga ban ïap thai,`,
          `Ba thrang ka um ba sngur;`,
          `La jan iapler leit jingleit,`,
          `Ha khlaw bymnud nga tur;`,
          `Sha jaka phlang to ïalam,`,
          `Harud um iaid ba jem,`,
          `Te hangta kiba sngewthait,`,
          `Ki buh ki khlieh ban dem.`,
        ],
      },
    ],
  },
  {
    id: "song-126",
    title: "Mynsiem Bakhuid To Wan",
    metadata: {
      number: 126,
      language: "khasi",
      author: "R.J.",
      composer: "Cambridge; St. Michael's",
      syllables: "S.M",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Mynsiem Bakhuid to wan,`,
          `Ka jingdum to pynpra;`,
          `Pynpeit, pynshai ïa la ki briew,`,
          `Nang trei Mynsiem ba bha.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Pynkhlaiñ ka jingngeit tlot,`,
          `Ka ding byneng pynmeh;`,
          `Jingsngew artatien to pynduh,`,
          `Pynjem ki dohnud eh.`,
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          `Pynkynduh ïa ki briew,`,
          `Ïalam sha diengphyna;`,
          `Ha lynti beit bytin ma Me,`,
          `Ha ri khlaw bah to da.`,
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          `Pynpaw ï'U Jisu Khrist,`,
          `Nongpynim ka pyrthei;`,
          `U Trai ki paid, U Blei donbor,`,
          `U Syiem ka jingaiei.`,
        ],
      },
    ],
  },
  {
    id: "song-127",
    title: "U Mynsiem Ka Jingpynthymmai",
    metadata: {
      number: 127,
      language: "khasi",
      author: "S.E.",
      composer: "Taking the Cross",
      syllables: "87.87.D",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Ko Mynsiem ka jingpynthymmai,`,
          `Ah hiar da ka bor ba khraw;`,
          `Pynduh ruh ka buit u soitan,`,
          `Ka jingsniew na ngi to law;`,
          `Ïa ka lyer bneng, Ah Trai to phah,`,
          `Ïa ki nongpop ban pynim;`,
          `Ai ngin sngew ka ktien ka jong Me,`,
          `Isnei Kynrad, ai ngin im.`,
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          `Ryngkat bad ki shakri jong Me,`,
          `Phah l'U Mynsiem ban ïatrei;`,
          `To pynkynduh ïa ki nongpop,`,
          `Pynpaw la ka jingaiei;`,
          `Ïa ki mynsiem jong ngi mynta`,
          `To pynshai, Ah Trai ba bha;`,
          `Ai ngin mad ka jingieit jong Me,`,
          `Lam ïa ngi sha ka diengphna.`,
        ],
      },
    ],
  },
  {
    id: "song-128",
    title: "Ka Jingthrang Ban IohÏa U Mynsiem Bakhuid",
    metadata: {
      number: 128,
      language: "khasi",
      author: "L.D.",
      syllables: "Irregular",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          `Mynsiem Bakhuid U Blei,`,
          `Ba dap da jingaiei;`,
          `Pynkynduh nga bapop`,
          `Ïoh ngan hap sha jingjot.`,
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          `To pynim, pynthymmai,`,
          `Ha dohnud jong nga shong,`,
          `Ta ïalam, nang hikai`,
          `Khun U Blei ngan ïoh long.`,
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          `Mynsiem Bakhuid na neng,`,
          `Wan hiar ha nga ba rem;`,
          `Pynkhuid pynkyntang noh,`,
          `Tang ï'U Blei ngan ïaroh.`,
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          `Mynsiem Bakhuid to wan,`,
          `Diengphna pynpaw hajan;`,
          `Pynkhuid kloi kum ïa nga,`,
          `Pynkup bor da shisha.`,
        ],
      },
    ],
  },
];
