import { type SongT } from "@repo/types";

export const kaJingrwaiShaphangKaRi = [
  {
    id: "song-578",
    title: "Ka Jingduwai na ka bynta ka Ri Khasi",
    metadata: {
      number: 578,
      language: "khasi",

      syllables: "87.87.67.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Kynmaw, Trai ïa ka Ri Khasi,",
          "Kynti u barim bajah",
          "Shon ka muhor U Jehobah",
          "Ha ka pateng ba dang sah;",
          "Trai ba bha, ïeng ban da",
          "Їa ka Ri na ka jingma.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Kynmaw ïa ki rympei Khristan,",
          "Hapoh ïing poh sem nang trei;",
          "Ai ha kine ki per sara",
          "Ka umjer ka jingaiei",
          "Trai nang trei, ba ngin sei,",
          "Їa ka sap tipbriew tipblei.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ha ki pateng bynriew baroh,",
          "Me la long ka jakarieh",
          "Ngin ym syier la dum ka lawei,",
          "Lada Me, Men long ka stieh;",
          "Trai ba bha, ïeng ban da",
          "Їa ka ri na ka jingma.",
        ],
      },
    ],
  },
  {
    id: "song-579",
    title: "Ah Trai kynmaw",
    metadata: {
      number: 579,
      language: "khasi",
      composer: "H.M.P.",
      syllables: "ALEX - III No. 4",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah Trai kynmaw ka Ri jongngi,",
          "Ka Ri b'la siewspah U Trai;",
          "Ha jingieit Blei ngi ïoh ban jngi,",
          "Da bor phylla ka jingshai.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "To kyntiew nam kyrteng U Trai,",
          "Jingïaroh burom ngin ai;",
          "Ai Gospel Blei kan ïai phyrnai,",
          "Tad haduh pyrthei kan wai.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ah Trai to sei ki nongïalam,",
          "Kiba sngew jingkhot jong Me;",
          "Spah, nam, burom kan duh kan dam,",
          "Hukum jong Me kin rakhe.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Rympei Khristan Trai to wan-i,",
          "Shlem jingieit U Trai Nongthaw;",
          "Jingriewblei kan ïoh kam kynti,",
          "Dur bha briew U Khrist kan paw.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Shon shap ha pateng ba dangsah,",
          "Pynshlei ki Anthem thymmai;",
          "Pyrthei satlak la kti kin rah,",
          "‘Long b'la kyrkhu ïa U Trai’.",
        ],
      },
    ],
  },
  {
    id: "song-580",
    title: "Ka Jingduwai na ka bynta ka Ri",
    metadata: {
      number: 580,
      language: "khasi",

      syllables: "76.76.D",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah Blei, Me U Trai Kynrad,",
          "Me U Nongbuh-Nongthaw;",
          "Ha Me ngi dem ngi kyrpad,",
          "Ha Me ngi wan ban paw;",
          "Namar la ka jong ka Ri,",
          "Ngi nguh ngi ïai duwai;",
          "Їa ka ban sumar ban ri,",
          "Isnei ma Me Ah Trai.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "To sei ïa ki nongïalam,",
          "Kiba shaniah ha Me;",
          "Shuwa ban sdang la ki kam,",
          "Ki khmat kin khmied sha Me;",
          "Ka Ri, ban saiñdur thymmai,",
          "To sei da la ki jong;",
          "Lawei ka Ri kan phyrnai,",
          "Ka hok kan ïeng rasong.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ki nongsynshar to pynmih,",
          "Kiba Me, Me la jied;",
          "Ban ïalam ha jingryntih,",
          "Ki khmat sha Me kin khmied;",
          "To ai ha ki ka jingstad,",
          "Jingshisha kin ïohi;",
          "Ai bor ma Me ko Kynrad,",
          "Kin ïalam la ka Ri.",
        ],
      },
    ],
  },
  {
    id: "song-581",
    title: "Ri India ba ïar",
    metadata: {
      number: 581,
      language: "khasi",
      composer: "H.M.S.",
      syllables: "ALEX - III No. 433",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Kynmaw Trai Ri India jong ngi kaba heh bad ïar,",
          "Burom jong ka Trai ma Me to ri;",
          "Da, ma Me, na ki nongshun ba ker sawdong jong ka,",
          "Ka bor jong Me Trai, to pyni.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Ri India baïar, ri jongngi,",
          "Kyrkhu ïa ka Trai man ka sngi;",
          "Kyrteng jong Me ha kane ka ri kan paw,",
          "Burom jong Me ruh kan nang khraw.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Jingstad jong Me Trai ai ha ki nongïalam jongngi,",
          "Buit bad jingshemphang ha ki to ai;",
          "Wat la nongshun ker sawdong jong ka ban ïoh pynpra,",
          "Da bor jong Me kan nang phyrnai.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "La bun phew snem mynta ka ri ka la ïoh laitluid,",
          "Jingroi jong ka ruh ka nang ïai paw;",
          "Jingkyrkhu jong Me Trai da shisha ai kan ïai tuid,",
          "Jingdum jingbieit ban nang ïai law.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Ko ri India baieit jongngi to nang ïaid shaphrang,",
          "Jinglong kawei ai pyrthei kan i;",
          "Ha ki kam babha baroh ba pha don to pyrshang,",
          "Ban pynpaw burom jong ka ri.",
        ],
      },
    ],
  },
  {
    id: "song-582",
    title: "Ah Trai to wan ban synshar",
    metadata: {
      number: 582,
      language: "khasi",
      composer: "O.S.M.",
      syllables: "76.76.D",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah Trai ki trai, Syiem ki syiem",
          "Wan ma Me ban synshar",
          "Ri tip briew tip Blei ngin im",
          "Thapniang jingsuk kan pyiar.",
          "Katba Balang ka dang sah",
          "Ban tbeh jingshai h'la ri,",
          "Khun jong Me Gospel kin rah",
          "Їa jingieit Blei sakhi.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Hapdeng ki jingeh ba bun",
          "Ba ri ka ïa kynduh,",
          "Khristan kum shipai babha",
          "Jingim ngin ïa kheiñ duh.",
          "U Trai don ha liang jong ngi,",
          "Ban ïeng pyrshah u ei?",
          "Nongshun la ki wan ïaleh",
          "Ngin jop ba don U Blei.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ah Trai to wan ban synshar",
          "Їa dohnud khun jong Me",
          "Hangno hangno ba ki don",
          "Tang ïa Me kin mane.",
          "Їarap ïa ki nongïalam",
          "Ban ieit, sheptieng ïa Me",
          "Ba ka ri shaphrang kan jam",
          "Jingbha kan roi kyrhai.",
        ],
      },
    ],
  },
  {
    id: "song-583",
    title: "Trai to kyrkhu ka Ri jong ngi",
    metadata: {
      number: 583,
      language: "khasi",
      composer: "B.C.L.",
      syllables: "S.S. 650",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah Trai, to kyrkhu ka ri baieit jong ngi,",
          "To da ïa ka da la kti donbor;",
          "To synshar ïa ka da jingsuk jong Me hi,",
          "Ba jingmanbha kan roi man ka por.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "To long, Ah Trai, ma Me ka jingshai",
          "Burom jong Me ban ïai paw to ai;",
          "Їalam ma Me hapdeng ki bun ki jingeh,",
          "Ka ri jong ngi tang bad Me kan neh.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "To kynmaw ki nongïalam bad nongsynshar,",
          "Ai bor kin ïaid ha ki aiñ jong Me;",
          "Da ka hok bad jingstad ai kin kieng atiar,",
          "Ba kin ïeng ha jingtip briew tip Blei.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Pynduh, Ah Trai, ki bor ba pynpait pynpra,",
          "Teh skhem ïa ka da jinglong kawei;",
          "Ai kan kup ka jinglaitluid bad jingshisha,",
          "Jingieit ba dap jong Me kan ïai shlei.",
        ],
      },
    ],
  },
];
