import { SongT } from "@repo/types";

export const kiJingrwaiIalap = [
  {
    id: "song-525",
    title: "Ka Jingmap U Blei",
    metadata: {
      number: 525,
      language: "khasi",
      composer: "OLD WINCHESTER ",
      syllables: "C.M.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "La ñiew ki khlur la ñiew u shyiap,",
          "Ka pop jong nga ka tam;",
          "Ka jingisnei jingmap U Blei,",
          "Kat kine ka pyndam.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Manasseh, Paul bad Magdalen,",
          "Ki la ïoh map na Me;",
          "Me kular ruh ban map ïa nga,",
          "Ah Trai ba isnei eh.",
        ],
      },
    ],
  },
  {
    id: "song-526",
    title: "Ka Jingkhot ka Gospel",
    metadata: {
      number: 526,
      language: "khasi",
      composer: "PEN-YR-YRFA",
      syllables: "76.76.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah Trai, to khot ï'u paidbah",
          "Ba bun ban bud ïa Me;",
          "Bythat ki saikhum baroh",
          "Ba teh ki dohnud eh;",
          "To khot ïa ki na mihngi,",
          "To khot na sepngi ruh,",
          "Ban pyndap la ka Balang,",
          "Jaka ka dang don shuh.",
        ],
      },
    ],
  },
  {
    id: "song-527",
    title: "Ka lad ban ïoh jingmap",
    metadata: {
      number: 527,
      language: "khasi",
      composer: "TWRGWYN",
      syllables: "73.73.7773.73.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "La shem ka lynti jingmap,",
          "Ha U Khun;",
          "Ka lynti lait ka jingïap,",
          "Ha U Khun;",
          "Ka hukum ka ïoh burom,",
          "Na kaba U shah shitom;",
          "La hun U Kypa junom,",
          "Ha U Khun;",
          "Kan nguh ka Seïon junom,",
          "Їa U Khun.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "La jop, la ïuh ka dujok,",
          "Ha U Khun;",
          "Bad U Blei ïoh ïasyllok,",
          "Ha U Khun;",
          "U Syiem ba khraw ka jingim;",
          "Ka lad ban lait ka jingtim,",
          "Ї'u briew ba sniew ka mynsiem,",
          "Ha U Khun,",
          "Їa ngin ïa nguh Nongpynim,",
          "Їa U Khun.",
        ],
      },
    ],
  },
  {
    id: "song-528",
    title: "Ka Jingïalap ïa U Khrist",
    metadata: {
      number: 528,
      language: "khasi",
      composer: "LLANFAIR",
      syllables: "74.74.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Kin ïalap ï'U Jisu Khrist,",
          "Haleluïa!",
          "Ha dykhar ha Khasi ruh,",
          "Haleluïa!",
          "Gospel ka la wan ha ngi,",
          "Haleluïa!",
          "Ruh kan leit haduh sepngi,",
          "Haleluïa!",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Kan sa long ba kin ïa seng,",
          "Haleluïa!",
          "Ban pynkhraw ï'U Syiem byneng,",
          "Haleluïa!",
          "Jingïap kordor kin ïalap,",
          "Haleluïa!",
          "Ha pyrthei baroh satlak,",
          "Haleluïa!",
        ],
      },
    ],
  },
  {
    id: "song-529",
    title: "Ei ban leit?",
    metadata: {
      number: 529,
      language: "khasi",
      composer: "OH! SO BRIGHT",
      syllables: "83.83.8883.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ki lok, sha kiba leh palat,",
          "Ei ban leit?",
          "Ban ong b'U Khrist U la mihpat,",
          "Ei ban leit?",
          "Ban pynpaw jingaiei jong U,",
          "Ba jaka rieh U long Jisu;",
          "Ha ki bynriew naduh haduh,",
          "Ei ban leit?",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ban ong b'U Khrist U long ba lah,",
          "Ei ban leit?",
          "Ї'u briew ba pop pynkylla bha,",
          "Ei ban leit?",
          "Da jingput rupa ban pynpaw,",
          "Ba don jingisnei kum duriaw;",
          "Ї'u ïong ï'u lieh, ï'u rit ï'u khraw,",
          "Ei ban leit?",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ko lok ba ieit, mynta uei?",
          "Ei ban leit?",
          "Sha kaba mon Jisu ban trei,",
          "Ei ban leit?",
          "Kat kum ka jingkwah jong U Blei,",
          "Sha ri ba dum, ri khlaw pyrthei;",
          "U ban ym pyrta jam, uei?",
          "Nga ngan leit.",
        ],
      },
    ],
  },
  {
    id: "song-530",
    title: "Ka Jingjop ka Ktien",
    metadata: {
      number: 530,
      language: "khasi",
      composer: "CHICAGO",
      syllables: "87.87.67.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ale Jisu sha ki bynriew,",
          "Ha ka jingdum ba dang sah;",
          "H'ei ruh h'ei wat ai kan duna,",
          "Jingtip shaphang diengphyna;",
          "Lei yn long, bun ba shong,",
          "Khlem da tip ï'U Trai b'la mong?",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Her sha mihngi, her sha sepngi,",
          "Her noh kylleng ka pyrthei;",
          "Pynbna ïa ki nar bad jingsum,",
          "Ha ka met jong U ba pei;",
          "Ale lang, haba nang,",
          "Їoh lashai ka lad la khang.",
        ],
      },
    ],
  },
  {
    id: "song-531",
    title: "Ka Jingwanphai ki nongwei",
    metadata: {
      number: 531,
      language: "khasi",
      composer: "GRAFENBERG",
      syllables: "76.76.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Bun hajar kiba tyngit",
          "Kin wan ïawad ka snam,",
          "B'la mih h'u lum Kalbari,",
          "Ban sait ka pop ka ram;",
          "La sait ki hajar bynriew -",
          "Ki don ha ïing I Pa;",
          "Ka sngur ka pukri pynban,",
          "Ha ri jingjynjar bah.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Kin wan nongpop na kylleng,",
          "Nongkyndong na jyngai;",
          "Kin dem kin nguh ï'U Jisu,",
          "Na ki bleithaw kin phai;",
          "Ah! hangta kin ïa kynmaw",
          "Ka jingïap Kalbari;",
          "Kin um ki dohnud jong ki,",
          "Sha U kin phet kin rieh.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka kuna ka diengphyna",
          "Ka dap ba ngin ïohlait,",
          "Ka snam U Jisu Kynrad;",
          "Ka biang hi ban sait;",
          "Te kumta wan u bynriew",
          "Na satlak ka pyrthei,",
          "Wan phai sha ïing U Kypa,",
          "U dap da jingaiei.",
        ],
      },
    ],
  },
  {
    id: "song-532",
    title: "Wat kyntait ïa nga",
    metadata: {
      number: 532,
      language: "khasi",
      composer: "S.S. 488",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Wat kyntait, ko Jisu jemnud,",
          "Sngew ka ïam jong nga;",
          "Haba Me dang khot ïa kiwei,",
          "Wat kyntait ïa nga.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Jisu, Jisu,",
          "Sngew ka ïam jong nga;",
          "Haba Me dang khot ïa kiwei,",
          "Wat kyntait ïa nga.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Shah ngan wan sha khet jingisnei,",
          "Jingsngewhun ban shem;",
          "Haba dem ha ka jingsngewsih,",
          "Jingngeit tlot pynskhem.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Ngam don hok, ko Trai, ban dawa,",
          "Tang ba Me la shah;",
          "Їa ka dohnud sniew pynkylla,",
          "Namar diengphyna.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Me U Tynrai khraw ka jingim,",
          "Bad ka jingsuk jai;",
          "Ngam don shuh, ha neng, ha khyndew,",
          "Tang ma Me, Ko Trai.",
        ],
      },
    ],
  },
  {
    id: "song-533",
    title: "Ka Jingkylla kaba mut",
    metadata: {
      number: 533,
      language: "khasi",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ngan da ïeng joit,",
          "Ngan leit sha la I Pa;",
          "Ngan da ong ruh shisha,",
          "Ko Pa! nga la leh pop;",
          "Pyrshah ïa ka byneng bad ïa Me ruh.",
          "Ngam dei long shuh",
          "Ban khot ïa nga u khun jong Me;",
          "Ngan da ïeng joit, ngan leit sha la I Pa.",
        ],
      },
    ],
  },
  {
    id: "song-534",
    title: "Ah Trai, nga wan phai",
    metadata: {
      number: 534,
      language: "khasi",
      composer: "S.S. 471",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Nga la ïaid sakma jngai n'U Blei,",
          "Mynta nga wan phai;",
          "Hapoh ka pop ngam hun, hynrei,",
          "Ah Trai, nga wan phai.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Nga wan phai, nga wan phai,",
          "Їaid mon shuh ngan nai;",
          "Shan ïa nga da bor jong Me,",
          "Ah Trai, nga wan phai.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "La kham slem ha jingsniew nga ngop,",
          "Mynta nga wan phai;",
          "Nga sngewsih kthang ïa la ka pop,",
          "Ah Trai, nga wan phai.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Ban ïaid wir nga la ngiah, Ah Trai,",
          "Mynta nga wan phai;",
          "Ha ktien jong Me ngan im khlem wai,",
          "Ah Trai, nga wan phai.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Dohnud jong nga ka pang shibun,",
          "Mynta nga wan phai;",
          "Ai bor ïa nga ban shem jinghun,",
          "Ah Trai, nga wan phai.",
        ],
      },
      {
        id: "verse-5",
        order: 6,
        type: "VERSE",
        lines: [
          "Ka jingkyrmen jong nga ka skhem,",
          "Mynta nga wan phai;",
          "H'U Jisu U b'la ïap la slem,",
          "Ah Trai, nga wan phai.",
        ],
      },
      {
        id: "verse-6",
        order: 7,
        type: "VERSE",
        lines: [
          "To sait ïa nga da snam ba kor,",
          "Mynta nga wan phai;",
          "Ba ngan kham lieh ban ïa ka ïor,",
          "Ah Trai, nga wan phai.",
        ],
      },
    ],
  },
  {
    id: "song-535",
    title: "Ka khyrdop ba rynghang sah",
    metadata: {
      number: 535,
      language: "khasi",
      composer: "S.S. 372",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ka khyrdop don ba rynghang sah,",
          "Na kata i ka jingshai;",
          "Ba tyngshaiñ eh na diengphyna,",
          "Jingieit U Blei ba janai.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Jingisnei jylliew katno'n ong!",
          "Їa nga ka khyrdop lait ka long!",
          "Ka long, ka long, ka khyrdop lait ka long.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka lait ka khyrdop, baroh wan,",
          "Da kaba wad ka jingim;",
          "Riewduk, riewspah, riewrit, riewsan,",
          "Wan lut, ban im ka mynsiem.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Nang beh shaphrang, la bun ba beiñ,",
          "Dang lait, dang lait, ka khyrdop;",
          "Ї'U Jisu nguh, bad U ïakheiñ,",
          "Їoh shisien lap ka jyllop.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Sha lyndet wah, sharud ngin buh,",
          "Ї'u dieng ba ban slem shane;",
          "Ngin ïoh pansngiat jingim ruh,",
          "Jingieit kan jur ha byneng!",
        ],
      },
    ],
  },
  {
    id: "song-536",
    title: "Ka Jingwan ka Hima",
    metadata: {
      number: 536,
      language: "khasi",
      composer: "S.S. 168",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Don ka hima ba phyrnai, ka ap ha lyndet jong ki lyoh,",
          "Ki riewkhuid na kylleng sawdong ki ïalang;",
          "Bad ki sngi ki ïaid stet thir thir ban pynjan jingwan jong ka,",
          "Namar jingwan ka hima ka la nang jan.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Oh! ka jingwan ka hima ka la nang jan, (2)",
          "Mynsiem jong nga to pynkloi;",
          "Namar turoi kan sa riew,",
          "Ba U Syiem ha ka burom Un sa paw.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka hima hangtei da ka burom ka la nang ïai pynkhreh,",
          "Ka kwah hir hir ba Un wan U Nongpynim;",
          "Ban pyllait ïa ngi na jinglong mraw ba ngi la shah shitom,",
          "Namar jingwan ka hima ka la nang jan.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Ha jingwan kata ka hima ngin ïohi ïa la U Trai,",
          "Namar U Trai hima hi U dei ban paw;",
          "Jingsiewspah jong U da ka snam ngin ïaroh Haleluïa,",
          "Oh! ka jingwan ka hima ka la nang jan.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Ka pyrthei ka nang ring swai da kaba ap jingwan jong ka,",
          "Dohnud jong ki ki noh ïan da jingsheptieng;",
          "To ngin ïalap ïa ka hima, to ngin pyntngen da jingrwai,",
          "Ba ka jingwan ka hima ka la nang jan.",
        ],
      },
    ],
  },
  {
    id: "song-537",
    title: "Wan sha Jisu",
    metadata: {
      number: 537,
      language: "khasi",
      composer: "OLD SANKEY 544 (56.65.)",
      syllables: "56.65.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Wan, wan sha Jisu,",
          "U ap ban pydiang ei;",
          "Nongwir men lyngngoh lei?",
          "Wan, wan sha Jisu.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Wan, wan sha Jisu,",
          "U ap ban pyllait ei;",
          "Na jinglong mraw pyrthei,",
          "Wan, wan sha Jisu.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Wan, wan sha Jisu,",
          "U ap, to wan sngewbha;",
          "Jingkit pynsting U lah,",
          "Wan, wan sha Jisu.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Wan, wan sha Jisu,",
          "U ap ïa me ban ai;",
          "Ki khymat ba la shai,",
          "Wan, wan sha Jisu.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Wan, wan sha Jisu,",
          "U ap ban da ïa me,",
          "Jingshongthait U la khreh,",
          "Wan, wan sha Jisu.",
        ],
      },
      {
        id: "verse-6",
        order: 6,
        type: "VERSE",
        lines: [
          "Wan, wan sha Jisu,",
          "U ap ban bah ïa me;",
          "Їa kane, Ah, to leh,",
          "Wan, wan sha Jisu.",
        ],
      },
    ],
  },
  {
    id: "song-538",
    title: "Ki Nongtong Briew",
    metadata: {
      number: 538,
      language: "khasi",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ngan pynlong ïa phi ki nongtong briew,",
          "Ki nongtong briew, ki nongtong briew;",
          "Ngan pynlong ïa phi ki nongtong briew,",
          "Lada phin bud ïa nga.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "To khie leit to da pynlong synran,",
          "Pynlong synran, pynlong synran;",
          "To khie leit to da pynlong synran,",
          "Їa ki bynriew baroh.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "To leit khring ïa ki na ri jingdum,",
          "Na ri jingdum, na ri jingdum;",
          "To leit khring ïa ki na ri jingdum,",
          "Sha ka ri ka jingshai.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "To khie leit da pynbaptis ïa ki,",
          "Pynbaptis ïa ki, pynbaptis ïa ki;",
          "To khie leit da pynbaptis ïa ki,",
          "Ha ka kyrteng jong Nga.",
        ],
      },
    ],
  },
  {
    id: "song-539",
    title: "U Jisu Khrist U dang ïaid lait",
    metadata: {
      number: 539,
      language: "khasi",
      composer: "HENDON",
      syllables: "77.77.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Jisu Khrist U dang ïaid lait,",
          "Peit sha U, Un ym kyntait;",
          "Pyrta kloi ban sngew dang lah,",
          "‘Ah to isnei, Trai, ïa nga!’",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Jisu Khrist U dang ïaid lait,",
          "Me ba swai Un nang pynshait;",
          "Ka sngi pydiang hun la poi,",
          "Wad jingkhiah, to wad kloi.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Peit! U ïeng, U kren ha me,",
          "‘Kaei me kwah ïa nga ban leh?’",
          "Pynpaw lut la ki jingkwah,",
          "Ban pynim U ju sngewbha.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Trai, ïa ngi to isnei eh,",
          "Ai kan paw ka ieit jong Me;",
          "Sha ka mynsiem ai kan pei,",
          "Nangta la ki soh kan sei.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Ah sngewbha! ka bor la wan,",
          "Por ka jingpynim ka jan;",
          "Ha U Jisu Khrist ngi lait,",
          "Їa ka dohnud sniew la sait.",
        ],
      },
    ],
  },
  {
    id: "song-540",
    title: "Ka Jingkhot ïa ki nongpop",
    metadata: {
      number: 540,
      language: "khasi",
      composer: "TRUMPET",
      syllables: "66.66.88.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Phi bynriew ba la ngop,",
          "Ha pop bad ha kordit;",
          "Їa Gospel phin ïasngap,",
          "B'U Jisu U dang khot.",
          "Phi kiba jot ba rem, to wan,",
          "Ha kti, U Jisu, bym pat dap.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Wat pynslem mynta shuh,",
          "Wat kren dong thala ruh;",
          "B'U khot ïa phi, ba duk,",
          "Ba matlah, ba dykoh.",
          "La khreh baroh, nongpop to wan,",
          "Ka jaka dang don ï'u ba mon.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka ktien byneng to ngeit,",
          "Ba phah ïalap U Trai;",
          "U long ïaineh, ba beit,",
          "Un isnei ei, Un ai.",
          "La phi la lyndet, wan pat lem,",
          "Ka jaka dang don, phin ym rem.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "B'la mih U Nongïalam,",
          "Їa phi ba bakla lad;",
          "Ka Ktien jong U to ngeit,",
          "B'U Khrist U khot, U wad,",
          "Te jar ba mon, ba wan ba lap,",
          "Ha jong jingisnei, bym pat dap.",
        ],
      },
    ],
  },
  {
    id: "song-541",
    title: "Ka Jingkhot ïa u nongphai dien",
    metadata: {
      number: 541,
      language: "khasi",
      composer: "S.S. 490",
      syllables: "66.66.88.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Bad rit bad khraw to wan,",
          "Sha Jisu ba la slem;",
          "Ah! katno U la shah,",
          "U Blei la katta'm shem.",
          "Ka sngi la noh, la syit, la dum,",
          "Ka jingkhang te dang lait ban rung.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Me nongphai-dien to wan,",
          "Da wad ï'U Jisu pat;",
          "Ka kti U nang kyner,",
          "Sha me, b'U kwah ban bat.",
          "U Blei U sybun ban ïa-ai,",
          "Jingisnei ïa u briew ba phai.",
        ],
      },
    ],
  },
  {
    id: "song-542",
    title: "Ka pyrthei lut ïa U Jisu",
    metadata: {
      number: 542,
      language: "khasi",
      composer: "R.S. 640",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ka pyrthei lut ï'U Jisu,",
          "Ngin thew tang kane hi;",
          "Ban khot ki bynriew baroh,",
          "Ban wan ha U ban rieh.",
          "Ka pyrthei lut ï’U Jisu,",
          "Ha U ki briew kin dem;",
          "Ki mihngi bad ki sepngi,",
          "Ha U jingim kin shem.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Ka pyrthei lut, ka pyrthei lut,",
          "Pynbna ka ktien ka jingim ha ki bynriew lut;",
          "To kyntiew nam ï'U Jisu ka lama khraw to rah,",
          "Tad da u thylliej baroh ïa U Trai un phla.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka pyrthei lut ï'U Jisu,",
          "Їa ka la siewspah duh;",
          "Ki khun ki ksiew u Adam,",
          "Kim bit ban long mraw shuh.",
          "Ka pyrthei lut ï'U Jisu,",
          "Wat ai ba ngin ïa swai;",
          "La kular skhem da U Blei,",
          "B'Un synshar shuh khlem wai.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Ka pyrthei lut ï'U Jisu,",
          "Khie leit, ka bor Un ai;",
          "Ban ïalap ïa ka Gospel,",
          "‘Wat sheptieng,’ ong U Trai.",
          "Ka pyrthei lut ï'U Jisu,",
          "Їa ngin ïamih ïatrei;",
          "‘Ha khymih Nga don ryngkat!’",
          "Ngin tieng ki nongshun 'lei?",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Ka pyrthei lut ï'U Jisu,",
          "Ha ïing U Kpa ha neng;",
          "Ki bynriew ba la siewspah,",
          "Bun byllien kin ïaseng.",
          "Ka pyrthei lut ï'U Jisu,",
          "Ah Trai ki trai, to mih;",
          "Ban ïalam sha ka burom,",
          "L'u paid b'la sait khuid lieh.",
        ],
      },
    ],
  },
  {
    id: "song-543",
    title: "Peit ban im!",
    metadata: {
      number: 543,
      language: "khasi",
      composer: "S.S. 371",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Peit sha Jisu, la me thait,",
          "Peit ban im!",
          "Peit sha U, te men ïohlait,",
          "Peit ban im!",
          "U la shah ha diengphyna,",
          "Peit ban im!",
          "Sngap, U ong,“To peit sha nga”",
          "Peit ban im!",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Peit! U Trai la kiew sha khlieh,",
          "Peit! U hajan eh ïa ngi;",
          "Peit ban im! nongpop ba pli,",
          "Peit ban im!",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "La me long khlem hok ban da,",
          "Peit ban im!",
          "Mynta phai sha diengphyna,",
          "Peit ban im!",
          "Mraw u soitan la me long,",
          "Peit ban im!",
          "Ha ka burom men ïoh shong,",
          "Peit ban im!",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "La sha jyngai me la phet,",
          "Peit ban im!",
          "La ïa U Blei me la klet,",
          "Peit ban im!",
          "Da I Pa ïa me la khot,",
          "Peit ban im!",
          "Phai noh mynta na jingjot,",
          "Peit ban im!",
        ],
      },
    ],
  },
  {
    id: "song-544",
    title: "Ale, ngin leit sha Kanaan",
    metadata: {
      number: 544,
      language: "khasi",
      composer: "KANAAN (87.87.D.& REFRAIN)",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "U Jisu U la ieit ïa nga,",
          "U wan na ka ri Kanaan;",
          "U ud U ïap ha diengphyna,",
          "Ba ngan ïoh poi sha Kanaan,",
          "Pansngiat burom ngan ïoh phong,",
          "Ha ri tyngshaiñ ka Kanaan;",
          "Bad Jisu junom ngan ïoh shong,",
          "Ale, ngin leit sha Kanaan.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Kanaan! Ri phyrnai!",
          "Lano ngin poi sha Kanaan!",
          "Ha Kanaan jingsuk la janai,",
          "Ale, ngin leit sha Kanaan.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ynda poi sha jingïaseng bah,",
          "Ki riewkhuid ha ri Kanaan;",
          "Bad ki shaphang l'U Nongsiewspah,",
          "Ngan riwai ha ri Kanaan.",
          "U Jisu b'la burom, ha khet,",
          "U shong hangta ha Kanaan;",
          "Ki khun U Blei sha ïing U khot,",
          "Ban shong hangta ha Kanaan.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "To wan sh'U Jisu, lok, to wan,",
          "U ap ïa phi ha Kanaan;",
          "Ki angel khuid kin wan ban tan,",
          "Ban shaw ïa phi sha Kanaan.",
          "To wan ban dih ki um ba im,",
          "Ba tuid jem jai ha Kanaan;",
          "Ha Kanaan jingsuk la janai,",
          "Ale, ngin leit sha Kanaan.",
        ],
      },
    ],
  },
  {
    id: "song-545",
    title: "Ki Sngi sngewtynnad",
    metadata: {
      number: 545,
      language: "khasi",
      composer: "KI SNGI SNGEWTYNNAD",
      syllables: "74.74.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ki sngi, khymih, ki nang poi,",
          "Sngi sngewkymen;",
          "Ba kin burom Khun U Blei,",
          "Pyrthei kylleng.",
          "Jingïap shitom Kalbari",
          "Yn sa byna;",
          "Ki riewkyndong ruh'n ïohi,",
          "Haleluïa!",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ka jingieit ba khraw U Trai,",
          "Yn ïoh ïalap;",
          "Kynrup, byllien, la jyngai,",
          "Na ka jingïap.",
          "Ka jingput ka Gospel Blei",
          "Ka nang sawa;",
          "Mihngi sepngi kan sa pei,",
          "Haleluïa!",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Jisu kham itynnad tam,",
          "Ki lok baroh;",
          "Jor bad jingai Blei U lam,",
          "Ї'U ngin ïaroh,",
          "Kat U Kynrad ym lah shem,",
          "Ha ki yrta;",
          "Byllien bah ïa U kin dem,",
          "Haleluïa!",
        ],
      },
    ],
  },
  {
    id: "song-546",
    title: "Katno ki pop ba U map ei!",
    metadata: {
      number: 546,
      language: "khasi",
      composer: "EVENING HYMN",
      syllables: "L.M.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ka pop ka jur, ka ram ka khraw,",
          "Ki saikhum jong ka ym lah law;",
          "Ym don ka lad ba ngin ïoh lait?",
          "Ym don ka snam ba ngin ïoh sait?",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ka khubor na byneng ka phla,",
          "Ka ram la siew h'u diengphyna;",
          "U nongpop mynta u la lait,",
          "Ka pop bun byllien la ïoh sait.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "U Jisu baroh U la siew,",
          "La pyllait phar ïa ngi ki briew;",
          "‘Ka Jingthoh pyrshah kam don shuh,’",
          "Їa U ngin ïaroh junom duh.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Katno ki pop ba U map ei!",
          "Katno ba khraw ka jingisnei!",
          "Ka met bad mynsiem ngin ïa ai,",
          "Ї'U Jisu Khrist, b'U long U Trai.",
        ],
      },
    ],
  },
  {
    id: "song-547",
    title: "Ngam sngewlehraiñ ban phla ï'U Trai",
    metadata: {
      number: 547,
      language: "khasi",
      composer: "S.S. 883",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ngam sngewlehraiñ ban phla ï'U Trai,",
          "Uba la map ïa nga;",
          "Ban burom ïa ka Ktien b'U ai,",
          "Bad ïa ka diengphyna.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Ha U Khrist, ha U Khrist, nga la lait na ka pop,",
          "Bad ka jingkit jong nga phar ka la duh;",
          "Ha ka diengphyna nga la ïeng nga la jop,",
          "Te mynta ngan kymen junom shuh.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Jisu U Trai nga ithuh bha,",
          "Ha U nga shaniah ruh;",
          "B'Un ym pynlehraiñ kum ïa nga,",
          "Ba kyrmen skhem ha U.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Kum la ka khet, ka Ktien ka skhem,",
          "Їa kaba U la smai;",
          "Te nga la ngeit ba ngan ym rem,",
          "Ha ka sngi jong U Trai.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "U Trai U'n phla ïa nga, Un ong,",
          "Ha khmat jong U Kypa;",
          "Ba ha ka Salem ngan ïoh shong,",
          "Ha ïing b'la khreh ïa nga.",
        ],
      },
    ],
  },
  {
    id: "song-548",
    title: "To wan sait ha ka snam U Khunlangbrot",
    metadata: {
      number: 548,
      language: "khasi",
      composer: "S.S. 379",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Lok, lada phi kwah ban sait khuid la ki pop,",
          "To wan sait ha ka snam Khunlangbrot;",
          "Wan da shaniah lut ha jingaiei jong U,",
          "To wan sait ha ka snam Khunlangbrot.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "To wan sait, to wan sait,",
          "To wan sait ha ka snam Khunlangbrot;",
          "La pop la tap ïa phi baroh shirynïeng,",
          "To wan sait ha ka snam khunlangbrot.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Lada phi kohnguh jingkhot U Khrist U Trai,",
          "Ban wan sait ha ka snam Khunlangbrot;",
          "Jingsuk mynsiem phin shem shilynter jingim,",
          "Ba la sait ha ka snam Khunlangbrot.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Haba sngi bishar kan poi, phin sa shadkmen,",
          "Ba la sait ha ka snam Khunlangbrot;",
          "Namar ba phi lah ban shong suk ha byneng,",
          "Da jingsait ha ka snam Khunlangbrot.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Kumta, lok, phim donkam ban dang pynslem shuh,",
          "To wan sait ha ka snam Khunlangbrot;",
          "Їoh ba poi ka por ba lad jingkhot kan wai,",
          "To wan sait ha ka snam Khunlangbrot.",
        ],
      },
    ],
  },
  {
    id: "song-549",
    title: "Don jingmap ï'u nongpop",
    metadata: {
      number: 549,
      language: "khasi",
      composer: "S.S. 780",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ale nongpop mynta to ïam,",
          "Namar ki pop ba khraw;",
          "Hangta ha Kal'bri lum ka don,",
          "Ka jingmap ï'u nongpop.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Don jingmap! h'oid, don jingmap!",
          "Bad jingkhuid ruh, jingsuk kynjai;",
          "Kine baroh h'U Khrist ki don,",
          "Un ai ha kito baroh kiba ngeit.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Namar ki pop ba phi la leh,",
          "Ka jingmap ei Un ai;",
          "Da pdiang te ha la ka dohnud,",
          "Їa phi shisha Un kdup.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Ka bor u nongjop ruh Un ai,",
          "Un ai khlem da tyngkai;",
          "Mynsiem Bakhuid shapoh Un trei,",
          "Na pop ba phin ïoh khuid.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Ah lok nongpop, phim mon ban im,",
          "Ha bneng ban im junom?",
          "Hangta ha burom ba phyrnai,",
          "Baroh ngin phyrnai lang.",
        ],
      },
      {
        id: "verse-5",
        order: 6,
        type: "VERSE",
        lines: [
          "Phi pynslem lei? Ah lok nongpop,",
          "To tip ki sngi ki stet;",
          "Sha bymjukut ki her noh lin,",
          "Wan phai shuh te kim mon.",
        ],
      },
    ],
  },
  {
    id: "song-550",
    title: "Ka Jingwer ïa ki Nongtrei",
    metadata: {
      number: 550,
      language: "khasi",
      composer: "S.S. 749",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ah, shaei ki nongtrei, ki ban ïalum,",
          "Ї'u kew uba don ha ri thor ri lum?",
          "Ba bat la ki rashi - ka jingshisha,",
          "Ba mon ban sa shongthait ynda dep bha.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Shaei ki nongtrei? Ah ei ban wan,",
          "Ban ot ïa u kew shuwa ba un tlor?",
          "Ah, ei ban ïarap, ban lum, ban tan,",
          "Ї'u kew uba don ha ri lum ri thor?",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Khie wad man ki lad bad man la ki dong,",
          "Phin shem ïa u kew ha ki ñiut ba jrong;",
          "Iwei ruh ban iehnoh, ban klet wat ai,",
          "To lum ïa ki baroh ha thiar U Trai.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Ki lyngkha ki byrlieh ki la ih bha,",
          "Sa tang ïa ki nongtrei ki ap mynta;",
          "Ki nongtrei ki khyndiat ka kam ka bun,",
          "Ka jingduh ka jingsep kan long shibun.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Te mynta, to wan rah la ki rashi,",
          "Ban lum lang i'u kew jong U Trai jong ngi;",
          "Ban trei ruh haduh ban da khot U Trai,",
          "Ban shong lem ban khawai junom khlem wai.",
        ],
      },
    ],
  },
  {
    id: "song-551",
    title: "Ka bor ka Snam",
    metadata: {
      number: 551,
      language: "khasi",
      composer: "S.S. 145",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Lada phi kwah ban ïoh lait na ka pop,",
          "Don bor ha ka snam, bor ha ka snam;",
          "Lada phi wad bor jingpynshoi ban jop,",
          "Don bor ba phylla ha ka snam.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Don ka bor, bor,",
          "Bor ba trei phylla;",
          "Ha ka snam, Kalbari,",
          "Don ka bor, bor;",
          "Bor ba trei phylla,",
          "Ha ka snam kordor, Kalbari.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ban lait na jingmeng bad jingkwah pyrthei,",
          "Don bor ha ka snam, bor ha ka snam;",
          "Wan ban sait khuid ha ka wah Kalbari,",
          "Don bor ba phylla ha ka snam.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Lada phi kwah ban kham lieh ïa ka ïor,",
          "Don bor ha ka snam, bor ha ka snam;",
          "Ban khuid ki thohbria ha wah ba kordor,",
          "Don bor ba phylla ha ka snam.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Shakri ï'U Jisu, U Syiem bymjukut,",
          "Don bor ha ka snam, bor ha ka snam;",
          "Pynleit ka jingim ban shakri ï'U Trai,",
          "Don bor ba phylla ha ka snam.",
        ],
      },
    ],
  },
  {
    id: "song-552",
    title: "Hangno phin shong ha bymjukut?",
    metadata: {
      number: 552,
      language: "khasi",
      composer: "S.S. 430",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Hangno phin shong ha bymjukut,",
          "To pyrkhat kloi kumno phi mut;",
          "To ïathuh shai kumno phin kut,",
          "Hangno phin shong ha bymjukut?",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: ["Ha bymjukut, ba bymjukut,", "Hangno phin shong ha bymjukut?"],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Bun kiba jied ï'U Khrist mynta,",
          "Na la ki pop ki phai shisha;",
          "Jingsuk byneng kin ïoh khlem kut,",
          "Hangno phin shong ha bymjukut?",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Haba la phai na lynti khim,",
          "Bad phi nang phet ha lad jingtim;",
          "Kumno kan long ka jingrai kut,",
          "Hangno phin shong ha bymjukut?",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "To phai, to ngeit mynta kumne,",
          "Peit sha U Jisu, wat sangeh;",
          "Phin sa nang phai ktien hun jingmut,",
          "‘Nga la lait im ha bymjukut’!",
        ],
      },
      {
        id: "chorus-2",
        order: 6,
        type: "CHORUS",
        lines: ["Ha bymjukut, ha bymjukut,", "Nga la lait im ha bymjukut!"],
      },
    ],
  },
  {
    id: "song-553",
    title: "Ka Jingkhot ban ïalap",
    metadata: {
      number: 553,
      language: "khasi",
      composer: "REX GLORIAE",
      syllables: "87.87.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Don bun hajar ha ka pyrthei,",
          "Don bun spah ha la ka ri;",
          "Bym tip jingieit bah jong U Blei,",
          "Bad jingsiewspah Kalbari.",
          "Sha kine ei ban leit ïalap,",
          "Jingpynim ei ban ïathuh?",
          "Jingknia ba tlem, ba khraw, ba dap,",
          "Ka dawa ba kin ym duh.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Sha khlaw sha btap ka pop ka lam,",
          "Ban mane blei ba kynsha;",
          "Mynsiem ba bha baroh ka dam,",
          "Hapoh jingdum ba thala.",
          "Їa kine mano ban leit wad,",
          "Mano ïa ki ban pyllait?",
          "Jingïap ïapli jingkah la kad,",
          "Lynti jingim ruh la lait.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Spah, nam, burom bad jingsngewbha,",
          "Ki jingpah shukor pyrthei;",
          "Dohnud u briew ki pynbyrngia,",
          "Ha jingthala ba shyrkhei.",
          "Їa kine mano ban kyrsiew,",
          "Mano ïa ki ban sngewlem?",
          "Ka biang jingshah U Khun U Briew,",
          "Ban pynksan ei ki barem.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Jisu, Jisu tang Me Me lah,",
          "Ban pynim na jingïap duh;",
          "Bun bun hajar ha pop ba thiah,",
          "Ban khie nangta bym lah shuh.",
          "Ah pynmih kyrhai ki nongtrei,",
          "Kiba sngew jingkhot U Trai,",
          "Ban leit ïalap khubor U Blei,",
          "Kylleng ka ri khlem tyngkai.",
        ],
      },
    ],
  },
  {
    id: "song-554",
    title: "U Nongpynkhiah ba khraw",
    metadata: {
      number: 554,
      language: "khasi",
      composer: "S.S. 89",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "U Nongpynkhiah ba khraw la shem,",
          "U Jisu, Uba sngewlem;",
          "Tien pyntngen U kren ï'u nongpang,",
          "To sngap ka sur U Jisu.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Sur ba thiang jingrwai angel,",
          "Kyrteng kor tam ha pyrthei;",
          "Jingrwai bang bym pat ju sngew,",
          "Jisu baieit, Jisu.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ki pop baroh Un map lut phar,",
          "To sngap 'tien sbun U Jisu;",
          "Jingdum ba kah kan phyrnai kdar,",
          "Phin shong ha burom jong U.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Jingpang mynsiem, jingpang bam pong,",
          "Kin shem jingkoit h'U Jisu;",
          "Jingshitom pyrthei har rukom,",
          "Kin her ha kyrteng Jisu.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Mynsiem ba lwait jinghun kan shem,",
          "Ha kyrteng ieit U Jisu;",
          "Jingdum ba kah, u lyoh ba rben,",
          "Kin pra lut phar h'U Jisu.",
        ],
      },
      {
        id: "verse-5",
        order: 6,
        type: "VERSE",
        lines: [
          "To wan, ko lok, shongsah hangne,",
          "Їaroh kyrteng U Jisu;",
          "Ka jingkhot ieit wat ñiew thala,",
          "To sngap bad wan kloi sha U.",
        ],
      },
      {
        id: "verse-6",
        order: 7,
        type: "VERSE",
        lines: [
          "Ynda ngin poi ha bneng lawei,",
          "Ngin ïohi ïa l'U Jisu;",
          "Sawdong ka khet ïaroh ngin sei,",
          "Ka kyrteng ieit U Jisu.",
        ],
      },
    ],
  },
  {
    id: "song-555",
    title: "Khyndai phew khyndai ki langbrot ha sem",
    metadata: {
      number: 555,
      language: "khasi",
      composer: "BRYANT (S.S. 97)",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Khyndaiphew khyndai ki dem sngewbha,",
          "Hapoh jingker ka sem;",
          "Iwei sha lum I ïaid sakma,",
          "Jngai bah na ki khyrdop ba skhem.",
          "Jngai bah sha ki lum ba riat ba ma,",
          "Sha lyndet ka khmat U Nongap ba bha.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Trai, hangne don khyndaiphew khyndai,",
          "Kine ki kim la biang ïa Me?",
          "‘Ine I maik,’ ong U bai,",
          "‘I la sakma na kine mai,",
          "Ba lyntieng ka sniew, a thiep ki jrong,",
          "Ngan kiew ïa ki lum, ngan wad la I jong’.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Hynrei ki b'la siewspah kim tip satia,",
          "Jingjylliew ki wah b'U jam;",
          "Ne jingdum ka miet b'U ïaid lyngba,",
          "Shuwa ïa I ba Un tam.",
          "Shapoh law baing U la ïohsngew I pah,",
          "I pang sa ban ïap, marwei I thiah.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Trai naei jaw snam katne katne,",
          "Artet lynti lum kynjah?",
          "Na krung U Nongap la jaw kane,",
          "Ha b'U wad ban shem iba jah.",
          "Trai balei ngi kieng ki mong katne?",
          "Ba trud ba tar shiah mynmiet hynne.",
        ],
      },
      {
        id: "verse-5",
        order: 5,
        type: "VERSE",
        lines: [
          "Hynrei lyngbaing ba shyrkhei,",
          "bad nalor ki ngiat ba jrong,",
          "Jingpyrta ka kiew sha duwar U Blei -",
          "“To kmen, Nga la shem la I jong”",
          "Bad ki angel bneng ki risa ki ong -",
          "“To kmen, U Trai U la shem la I jong!”",
        ],
      },
    ],
  },

  {
    id: "song-556",
    title: "Lok nongpop to wan",
    metadata: {
      number: 556,
      language: "khasi",
      composer: "S.B.",
      syllables: "L.M.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Lok nongpop, wan sha jingkhawai,",
          "B'U khot ieit U Jisu U Trai;",
          "Iwei ruh Un ym kyntait noh,",
          "Namar U khot ï'u briew baroh.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "To wan baroh phi ba sngewthait,",
          "Ha U phin shem ka jingjahthait;",
          "Phi kiba jynjar bad ba duk,",
          "Tang ha U hi phin shem jingsuk.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka jingieit bah jong U ka lah,",
          "Їa dohnud maw ba eh ban ktah;",
          "Te kan kylla long dohnud doh,",
          "Ї'U Blei ban ieit bad ban ïaroh.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "To wat pyntud, to wat bakla,",
          "Sngi jingpynim ka long mynta;",
          "Tang sngew jingkhot kloi lan wan noh,",
          "Ha U b'la ïap namar baroh.",
        ],
      },
    ],
  },
  {
    id: "song-557",
    title: "Khot ïa ki b'la sakma",
    metadata: {
      number: 557,
      language: "khasi",
      composer: "H.J.",
      syllables: "S.S. 752",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Sngap! dei ka ktien U Trai jong nga,",
          "B'U khot ki langbrot b'la sakma;",
          "Ba kin wan phai pat sha ka sem,",
          "Na kaba ki la jah la slem.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Khot ïa ki, khot ïa ki,",
          "Khot ïa ki ha kin don lem bad ngi;",
          "Khot ïa ki, khot ïa ki,",
          "Khot ïa ki ban wan sh'U Jisu.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ei ba la kloi ban rap ïa nga,",
          "Ban wad ki langbrot ba la jah;",
          "Sha ka jingker ban lam ïa ki,",
          "Ba kin lait im na ki suri?",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "To wad ïa ki sha lum sha them,",
          "To wad ïa ki ha ban da shem;",
          "Ki langbrot kiba la sakma,",
          "Ong U Jisu, Nongap ba bha.",
        ],
      },
    ],
  },
  {
    id: "song-558",
    title: "Ka Jingkhot ieit U Blei",
    metadata: {
      number: 558,
      language: "khasi",

      syllables: "11.11.11.11.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "To phai lok, Ah phai lok, balei phin ïap ei?",
          "U Blei  technik phi mynta U khot ieit isnei!",
          "U Jisu U khot, Mynsiem ruh U ong ‘Wan’,",
          "Ki angel ki ïa-ap ïa phi hi ban tan.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ka jingbuhteng wat ai ïa phi kan shukor,",
          "Ba phi phin sa ngeit ynda poi hi ka por;",
          "Wan rangli wan juki, wan kloi noh katba,",
          "Ki wah um ka jingim ki dang tuid sngur bha.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka spah bad ka sngewbha kim myntoi ei ei,",
          "Kim lah syrpai kordit ne pang da lei lei;",
          "Tang Jisu hi U long U Doktor mynsiem,",
          "To pdiang ïa U mynta, ïa phi Un pynim.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Balei phin shu phet, lok, sha riat ka jingtim,",
          "Haba ha U Jisu don lad ban laitim?",
          "Lada phi dang artatien, ale wan jngoh,",
          "Da lade phin shem hi, bad jingim phin ïoh.",
        ],
      },
    ],
  },
  {
    id: "song-559",
    title: "Ka Jingmap ei U Blei",
    metadata: {
      number: 559,
      language: "khasi",
      composer: "S.E.",
      syllables: "76.76.D.",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ka jingaiei ka jong Me,",
          " открыть ïa nga ban wan;",
          "Ban lait na ka pop ka tngit,",
          "La katne ki ïai ban.",
          "Bad la nga la ïaid jngai ruh,",
          "Da im khlem aiñ, khlem Blei;",
          "Їa nga, ko Jisu Kynrad,",
          "Men sait, Men pynim ei.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Ka khyrdop ka dang rynghang,",
          "Bad baroh kiba wan;",
          "Kin shem ka khmat ba sngewbha,",
          "U Kpa ba U wan tan.",
          "Un map ka palat baroh,",
          "Ka jingkmen ruh Un ai;",
          "Ka pansngiat ruh bad burom,",
          "Kim duh ha ri jingshai.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Ah jingisynei ba jylliew,",
          "Ka jingïaimap U Blei!",
          "L'ym ïoh ngan duh jingkyrmen,",
          "Ki ummat ruh kin shlei.",
          "Haba jingpynshoi ki lap,",
          "Ka jynjar ruh ka ban;",
          "Nga tip ba U Blei na bneng,",
          "Un ïarap, Un kyrshan.",
        ],
      },
    ],
  },
  {
    id: "song-560",
    title: "La ki pop ki saw haiñ haiñ",
    metadata: {
      number: 560,
      language: "khasi",
      composer: "W.R.",
      syllables: "S.S. 1173",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "La ki pop ki saw haiñ haiñ,",
          "Kin sa lieh phar kum ka ïor;",
          "La ki saw byrïong ruh,",
          "Kin khuid baroh phar;",
          "La ki pop ki saw haiñ haiñ,",
          "Kin sa lieh phar kum ka ïor.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Sngap ka ktien kaba khot ieit,",
          "Ah wan phai phi sha U Blei!",
          "U long ba dap jingisynei,",
          "Bad jingieit phylla;",
          "Sngap ka ktien kaba khot ieit,",
          "Ah wan phai phi sha U Blei!",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Pop ki jong phi Un map ei,",
          "Un ym kynmaw shuh ïa ki,",
          "‘Peit sha Nga, phi u paidlang,’",
          "Ong U Trai U Blei;",
          "Pop ki jong phi Un map ei,",
          "Un ym kynmaw shuh ïa ki.",
        ],
      },
    ],
  },
  {
    id: "song-561",
    title: "Phai, ko nongïaid wir",
    metadata: {
      number: 561,
      language: "khasi",
      composer: "S.R.M.",
      syllables: "S.S. 449",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Phai, ko nongïaid wir, b'la khuslai b'la thait,",
          "Sngap ka jingkhot ieit U Nongaplangbrot;",
          "Їa me Un pynim, ïa me Un sait phar,",
          "Їa U to pdiang kloi, wat pynslem ïoh jot.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Da ki ktien ba jem, da kaba shah slem,",
          "U Nongaplangbrot U khot ïa me;",
          "Da kaba shah slem, da ki ktien ha jem,",
          "Da jingieit U ong, to wan ha nga.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Mynta U dang khot, balei men jot sah?",
          "La me la jah slem katta na ka sem;",
          "Da la ka jingïap ïa me la siewspah,",
          "Da ka jingsngewlem shawei bym lah shem.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Sngap ka ktien jong U, pyrkhat jingisnei,",
          "Namar ki pop me U shah ka diengphna;",
          "Jingmap ba janai, jingim bymjukut,",
          "Їa me U tyrwa, la siew ka kuna.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Wan da ka lad rim, lynti ba shisha,",
          "Rung da U Jisu U long ka jingkhang;",
          "U Nongaplangbrot ïa me U dang khot,",
          "Wan la me la thait, sakma shuh wat shong.",
        ],
      },
    ],
  },
  {
    id: "song-562",
    title: "Jar kat kiba mon",
    metadata: {
      number: 562,
      language: "khasi",
      composer: "T.R.",
      syllables: "S.S. 389",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Jar kat kiba ïohsngew, pyrta, pyrta jam,",
          "Pynbna sawdong kylleng khubor ba bha [tam;",
          "Ai jingkhot kan sawa, ki dohnud kan ngam,",
          "‘Jar kat kiba mon to wan!’",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Jar kat kiba mon, jar kat kiba mon,",
          "Rit bad khraw, riewspah riewduk kat kiba [don;",
          "Sngap! Nongpynim ba ieit U khot kiba mon,",
          "‘Jar kat kiba mon to wan!’",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Jar kat kiba mon kim dei shuh ban buhteng,",
          "Ka jingkhang dang rynghang, ïeng joit [kloi, to ïeng;",
          "Jisu Khrist U long ka lynti jingim bneng,",
          "‘Jar kat kiba mon to wan!’",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "‘Jar kat kiba mon!’ Ha sngap ki ktien ba shai,",
          "‘Jar kat kiba mon!’ jingtyrwa kam pat wai;",
          "Jar kat kiba mon jingim kin ïoh kyrhai,",
          "‘Jar kat kiba mon to wan!’",
        ],
      },
    ],
  },
  {
    id: "song-563",
    title: "Ka khubor Blei la pynbna",
    metadata: {
      number: 563,
      language: "khasi",
      composer: "S.R.M.",
      syllables: "76.76.D. & REFRAIN",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Ka khubor Blei la pynbna,",
          "Ka por sngewbha la wan;",
          "Ha ki nongpop ka pyrta,",
          "Ale to wan hajan.",
          "Jingmap ki pop to pdiang ei,",
          "U Jisu U tyrwa;",
          "U Blei ba dap jingisnei,",
          "Baroh U khot mynta.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Baroh U khot mynta,",
          "Baroh U khot mynta;",
          "U Blei ba dap jingisnei,",
          "Baroh U khot mynta.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Phew hajar bun phew hajar,",
          "U paid shaphrang b'la ïaid;",
          "B'la ban ka pop, shem jynjar,",
          "Ka mynsiem ruh la thait,",
          "La ki la duh jingkyrmen,",
          "Bym don u nongïarap;",
          "H'U Jisu ki la shadkmen,",
          "Jingkit baroh la hap.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Ha lynti rim to sangeh,",
          "Da khmih ïoh ïaid bakla;",
          "La ki dohnud wat pyneh,",
          "To peit da bishar bha.",
          "Ha khmih ka lynti U Blei,",
          "Da U Jisu la thaw;",
          "B'la pei lyngba ka pyrthei,",
          "Ha ngi ruh ka la paw.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Masi kyrtong mynhyndai,",
          "U 'langkitpop ki briew,",
          "Ka kuna Blei kim lah ai,",
          "Ki long tang ki syrngiew,",
          "Da jingïap ba U la shah,",
          "U Jisu Khrist U Trai,",
          "Ki pop jong ngi U la bah,",
          "Ki jingkñia ki la wai.",
        ],
      },
      {
        id: "verse-5",
        order: 6,
        type: "VERSE",
        lines: [
          "Na jingpynrem ka hok Blei,",
          "Na jingtim ka hukum,",
          "Ngi la lait da jingisnei,",
          "B'la sei ruh na jingdum.",
          "Mynta h'U Jisu kynjai,",
          "Jingma jingtieng la duh;",
          "La ka jinglait ngin ïai rwai,",
          "Junom ïa U ngin nguh.",
        ],
      },
      {
        id: "chorus-2",
        order: 7,
        type: "CHORUS",
        lines: [
          "Junom ïa U ngin nguh,",
          "Junom ïa U ngin nguh,",
          "La ka jinglait ngin ïai rwai,",
          "Junom ïa U ngin nguh. Amen.",
        ],
      },
    ],
  },
  {
    id: "song-564",
    title: "Jisu nga wan",
    metadata: {
      number: 564,
      language: "khasi",
      composer: "S.G.N.",
      syllables: "S.S. 498",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Na jinglongmraw jingdum bad khuslai,",
          "Jisu nga wan, Jisu nga wan;",
          "Sha jinglaitluid, jingkmen bad jingshai,",
          "Jisu sha Me nga wan.",
          "Na jingtlot jong nga sha bor jong Me,",
          "Na jingduk jong nga sha spah jong Me,",
          "Na jingtngit jong nga sha khet jong Me,",
          "Jisu sha Me nga wan.",
        ],
      },
      {
        id: "verse-2",
        order: 2,
        type: "VERSE",
        lines: [
          "Na jingbymlah ba tlot bor jong nga,",
          "Jisu nga wan, Jisu nga wan;",
          "Sha ka burom bad bor ka diengphna,",
          "Jisu sha Me nga wan.",
          "Na shitom pyrthei sha jingsuk jai,",
          "Na sngi ba dum lyoh sha sngi phyrnai,",
          "Na jingsngewsih kthang sha ka jingrwai,",
          "Jisu sha Me nga wan.",
        ],
      },
      {
        id: "verse-3",
        order: 3,
        type: "VERSE",
        lines: [
          "Na jingsngewmeng, sngewsarong, sngewheh,",
          "Jisu nga wan, Jisu nga wan;",
          "Sha jingsngewrit, mon jong Me ban leh,",
          "Jisu sha Me nga wan.",
          "Ha jingieit jong Me ban shong nga brai,",
          "Jingduh jingkyrmen kan phet sha jngai,",
          "Shatei ban her da thapniang, ngam btai,",
          "Jisu sha Me nga wan.",
        ],
      },
      {
        id: "verse-4",
        order: 4,
        type: "VERSE",
        lines: [
          "Na jingsheptieng ba jingtep kan rong,",
          "Jisu nga wan, Jisu nga wan;",
          "Sha jingsngewbha ïingsyiem ban ïoh shong,",
          "Jisu sha Me nga wan,",
          "Na jingjot ba jynjar bym lah ong,",
          "Sha jakarieh, bneng ba suk ha jrong;",
          "Khmat tyngshaiñ jong Me junom kan long,",
          "Jisu sha Me nga wan.",
        ],
      },
    ],
  },
  {
    id: "song-565",
    title: "Long ki b'la ïasuk bad U Blei",
    metadata: {
      number: 565,
      language: "khasi",
      composer: "H.M.S.",
      syllables: "R.S. 75",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Tang ki nongwei ngi long ha kane ka pyrthei,",
          "Їing jong ngi long sha khlieh, hangta lem bad U Blei,",
          "Їa khubor jingshisha ngi ïa pynbna mynta,",
          "B'la phah ïa ngi da U Blei hi.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Kane ka khubor ngi wallam,",
          "Ba Angel ruh ki ïarwai jam;",
          "“To long ki b'la ïasuk,” U ong U Trai U Blei",
          "“Long ki b'la ïasuk bad U Blei.”",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Ka jingkwah jong U Blei, ka long baroh ngi dei,",
          "Ban ngeit bad phai sha U, Un ai ka jingaiei;",
          "Ba baroh kiba ngeit ha U kin ïoh jingim,",
          "Bad junom kin shong lem bad U.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Ha ïing baitynnad, hangta ngin shong kyrhai,",
          "Ngin ïoh im bymjukut, lada sha U ngi phai;",
          "Hangta jingïap kam don, baroh ngin shongsuk lang,",
          "Na shitom baroh ngin lait phar.",
        ],
      },
    ],
  },
  {
    id: "song-566",
    title: "Leit pynbna ïa ka Gospel",
    metadata: {
      number: 566,
      language: "khasi",
      composer: "C.J.",
      syllables: "S.S. 1082",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Jisu U khot mynta ïa nga bad ïaphi,",
          "Ka Gospel ngin pynbna;",
          "Ngin ïai kohnguh, ïa U Trai U Blei jongngi,",
          "Їa ngin tur sha ka thma.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Leit pynbna jingshai jong Ka Gospel,",
          "Sha pyrthei baroh kawei;",
          "Tad ynda ki lum bad ki them ruh,",
          "Kin pynkhraw jingieit U Blei.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Hei! ki lok baieit ïa ngin ïa leit pynbna,",
          "Їalap khubor babha;",
          "Da ka bor U Trai bad da ka bor jingngeit,",
          "Ngin ïoh jop, jop shisha.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Jisu u ong, ngan don ryngkat lem bad phi,",
          "Kohnguh jingkhot jong u;",
          "Mynsiem Bakhuid Un ïalam Un da ïaphi,",
          "Ha jingtrei man ka sngi.",
        ],
      },
    ],
  },
  {
    id: "song-567",
    title: "Hangno ka lawei jong phi?",
    metadata: {
      number: 567,
      language: "khasi",
    },
    paragraphs: [
      {
        id: "verse-1",
        order: 1,
        type: "VERSE",
        lines: [
          "Lok la jingim phi la ju pyrkhat ei ei,",
          "Kumno ban im jingim hok tipbriew tip-Blei;",
          "Lada jingim shu kut noh tang ha pyrthei,",
          "Jingim u briew long jingim ba lehnohei.",
        ],
      },
      {
        id: "chorus-1",
        order: 2,
        type: "CHORUS",
        lines: [
          "Hangno ka lawei jong phi ko lok to pyrkhat mynta hi,",
          "Wan sha Jisu Un ym kyntait ei ïa phi;",
          "Te Jisu U ong,",
          "“Nga Uba long ka Lynti bad ka jingshisha bad ka Jingim de,",
          "Ym don uba wan ha U Kpa hynrei tang da nga”.",
        ],
      },
      {
        id: "verse-2",
        order: 3,
        type: "VERSE",
        lines: [
          "Lok, ha pyrthei don bun byllien kiba ong,",
          "Ba ki dang don ï'U Blei Nongthaw Nongpynlong;",
          "Hynrei soitan da la buit u pynthame,",
          "Bad u pynbakla lut ki rukom mane.",
        ],
      },
      {
        id: "verse-3",
        order: 4,
        type: "VERSE",
        lines: [
          "Hynrei Jisu U la shah halor diengphna,",
          "Oh diengphna long duwan ï'U Jisu b'la kñia;",
          "Jingkñia tang shisien b'la pvndep ïa baroh,",
          "Oh ka biang ban pynim ïa nongpop baroh.",
        ],
      },
      {
        id: "verse-4",
        order: 5,
        type: "VERSE",
        lines: [
          "Wan sha Jisu, kumta wan kloi wat buhteng,",
          "Jingsuk mynsiem b'U ai ka long jingsuk bneng,",
          "Lad jingpynim b'U Blei U la thaw phylla,",
          "Ba h'U Khun long jingkyrkhu ïa phi mynta.",
        ],
      },
    ],
  },
];
