name: Lynti Bneng Prod Deployment

on:
  push:
    branches: []
    paths: ["src/apps/lynti-bneng/**", "packages/**"] # Only runs if files here change

jobs:
  call-build:
    uses: ./.github/workflows/_expo_build.yml
    with:
      app_name: "Lynti-Bneng"
      app_path: "src/apps/lynti-bneng"
    secrets: inherit # Pass all repo secrets to the template
