import { SongT } from "~/src/types/song";

export const kaJingiaroh: SongT[] = [
  {
    id: 'song-568',
    title: 'Їaroh ïa U Blei',
    metadata: {
      number: 568,
      language: 'khasi',
      composer: 'J.C.E.',
      syllables: 'S.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`To ïaroh ïa U Blei,`',
          '`Ka kam te kaba dei;`',
          '`Ka jingisnei jong U ka khraw,`',
          '`Їa baroh ka pyrthei.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          "`To riwai lang ï'U Blei,`",
          "`B'U khreh man la ka sngi;`",
          "`N'u soh ka khyndew ban pyndap,`",
          '`Jingkyrduh khraw jong ngi.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Ko Seïon, to ïaroh,`',
          "`Ї'U Blei ba ai jingsuk;`",
          '`Jingkyrkhu baroh ruh U ai,`',
          '`Ha ngi ki khun jingduk.`',
        ],
      },
    ],
  },
  {
    id: 'song-569',
    title: "Ї'U Blei long ka Burom",
    metadata: {
      number: 569,
      language: 'khasi',
      composer: 'W.M.',
      syllables: 'S.S. 23',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          "`Ї'U Blei long ka burom ki kam b'U la leh,`",
          "`L'U Khun U la phah ba ïa ngi U ieit eh;`",
          '`U ai la ka jingim ka kuna ban siew,`',
          '`Ka khyrdop bneng U plie ba kin rung [ki briew.`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`To ïaroh ïa U Trai, sngap pyrthei ba U kren!`',
          '`To ïaroh ïa U Trai, phi ki bynriew [shadkmen!`',
          '`To wan da U Jisu U Khun sha U kpa,`',
          "`Ai burom ïa U b'U la leh kam phylla.`",
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Da snam Blei la pynlong jingsiewspah janai,`',
          '`Jingim ha kiba ngeit U kular ban ai;`',
          '`Nongpop uba khraw tam ba wan da ngeit [skhem,`',
          "`Ka jingmap bad jingsuk h'U Jisu un shem.`",
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          '`Ki kam kiba khraw U la leh ha pyrthei,`',
          '`Da U ruh ha dohnud jingkmen ka ïai shlei;`',
          '`Hynrei kan sa long jingphylla kham palat,`',
          '`Ynda ïa U Jisu ngin ïohi mar khmat.`',
        ],
      },
    ],
  },
  {
    id: 'song-570',
    title: 'Ka Jingïaroh ïa U Trai',
    metadata: {
      number: 570,
      language: 'khasi',
      composer: 'J.C.E.',
      syllables: 'L.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`To ïaroh ïa U Khrist U Trai,`',
          '`Phi angel neng to nguh khlem wai;`',
          '`Ka burom baroh ai ha U,`',
          '`Їa baroh phar thung syiem ïa U.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          "`Ma phi b'la siewspah da ka snam,`",
          '`Ha U to dem, to ai ka nam;`',
          '`Phi im da jingisnei jong U,`',
          '`Їa baroh phar thung syiem ïa U.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Ai ba ki bynriew baroh ruh,`',
          '`Bad rit bad khraw kin dem ïa U;`',
          '`Kin riwai jam da kaba nguh,`',
          '`Їa baroh phar thung syiem ïa U.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`La bun ka pop, la bun ka sniew,`',
          '`Ka khraw ka jingpynim jong U;`',
          '`Їa ki yn map, yn pynkhuid ruh,`',
          '`Їa baroh phar thung syiem ïa U.`',
        ],
      },
    ],
  },
  {
    id: 'song-571',
    title: 'Ka Jingpynkhraw ïa U Khrist',
    metadata: {
      number: 571,
      language: 'khasi',
      composer: '',
      syllables: 'C.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          "`Pynkhraw ï'U Jisu Khrist U Trai,`",
          '`Phi baroh junom duh;`',
          '`Ki angel neng bad ki riewkhuid,`',
          '`To burom eh ïa U.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Phi baroh ba la ïap da ngeit,`',
          '`Ki martyr baroh ruh;`',
          '`To dem ha khymat jong U Trai,`',
          '`To burom eh ïa U.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Ki prophet kiba dang ïohi,`',
          '`Ka khmat U Trai khlem duh;`',
          '`To tem duitara ha byneng,`',
          '`Ban burom eh ïa U.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Phi baroh kiba ring mynsiem,`',
          '`Hapoh ka byneng ruh;`',
          '`To ngeit, to kohnguh bad to dem,`',
          '`Ban burom eh ïa U.`',
        ],
      },
    ],
  },
  {
    id: 'song-572',
    title: 'Ka Jingïaroh',
    metadata: {
      number: 572,
      language: 'khasi',
      composer: 'J.C.E.',
      syllables: 'L.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`To ïaroh ïa U Biei ba khraw,`',
          '`Phi paid pyrthei ba U la thaw;`',
          '`Phi paid byneng, ha U phi im,`',
          "`Їaroh ï'U Kpa, Khun bad Mynsiem.`",
        ],
      },
    ],
  },
  {
    id: 'song-573',
    title: 'Ka Jingpynkhraw ïa U Trai',
    metadata: {
      number: 573,
      language: 'khasi',
      composer: 'J.C.E.',
      syllables: '66.66.88.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`U Trai U long U Syiem,`',
          '`Їa ngin ïa riwai lang;`',
          '`Ban ïaroh eh ïa U,`',
          '`Ka mynsiem ka la bang.`',
          '`Pynjam ka ktien, pynkhraw ïa U,`',
          '`U Nongpynim, da kaba nguh.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`U Jisu U synshar,`',
          '`U Syiem jingsuk U long;`',
          '`Їa ngi Un pynkhuid phar,`',
          '`Halor ka khet U shong.`',
          '`Pynjam ka ktien, pynkhraw ïa U,`',
          '`U Nongpynim, da kaba nguh.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Kan jop na kut sha kut,`',
          '`Ka hima bah U Trai;`',
          '`Ki bor ki bymjukut,`',
          "`H'U Jisu Khrist la ai.`",
          '`Pynjam ka ktien, pynkhraw ïa U,`',
          '`U Nongpynim, da kaba nguh.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Ha kti kamon U Blei,`',
          '`U Trai jong ngi U shong;`',
          '`Ha ban da ka pyrthei,`',
          '`Nongbud jong U kan long.`',
          '`Pynjam ka ktien, pynkhraw ïa U,`',
          '`U Nongpynim, da kaba nguh.`',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          '`Sngewkymen ki riewngeit,`',
          '`U Jisu hi Un paw;`',
          '`Ban ïalam ïa phi beit,`',
          '`Sha ïing ba U la thaw.`',
          '`Ki angel khuid kin sawa shen,`',
          '`Bad turoi Blei, to leh kymen.`',
        ],
      },
    ],
  },
  {
    id: 'song-574',
    title: "Ka Jingïaroh ï'U Nongpynim",
    metadata: {
      number: 574,
      language: 'khasi',
      composer: 'J.C.E.',
      syllables: 'C.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Shihajar thylliej, Ah ban ïoh,`',
          '`Ban ïaroh Nongpynim;`',
          '`Ka burom Jisu kum U Syiem,`',
          '`Ngan pynpaw katba im.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Ah Trai ba ieit eh jong nga,`',
          '`Їarap ba ngan ïathuh;`',
          '`Ka kyrteng jong Me ha ki briew,`',
          '`Jingieit jong Me ruh.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Ka kyrteng Jisu ka donbor,`',
          '`Jingsheptieng ban pynduh;`',
          '`Ka riew sngewtynnad ha ka shkor,`',
          "`U nongpop b'la ïohlait.`",
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`U pynduh ïa ka bor ka pop,`',
          "`Ї'u koidi U pyllait;`",
          '`Ka snam jong U ka pynkhuid phar,`',
          '`Їa nga te ka dang sait.`',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          '`U kren bad haba sngap ïa U,`',
          '`Ki nongïap ki im pat;`',
          '`Ka jingsuk jong U ruh ka tuid,`',
          '`Ha kiba khuslai sat.`',
        ],
      },
    ],
  },
  {
    id: 'song-575',
    title: "Ka Jingïaroh ï'U Blei",
    metadata: {
      number: 575,
      language: 'khasi',
      composer: 'J.C.E.',
      syllables: '10.10.11.11.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          "`Phi shakri U Trai, l'U Kynrad ïaroh,`",
          '`Pynpaw jingpynim ha pyrthei baroh;`',
          '`Ka kyrteng ba donbor U Jisu pynkhraw,`',
          '`Ka hima ka jong U ha ngi ka la paw.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`U synshar U Blei, ban pynim U lah,`',
          "`Sha ngi U la jan, l'U Khun U la phah;`",
          '`U paidlang u jong U, un riwai ïaroh,`',
          "`Ka khraw ka jingpynim d'U Jisu b'la ïoh.`",
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          "`Jingïaroh ï'U Blei, Uba ha khlieh tam,`",
          "`Ka burom ï'U Khun, ïa! ngin pyrta jam;`",
          '`Ki angel byneng ruh ki ïaroh ïa U,`',
          '`Khunlangbrot ki mane, ki dem bad ki [nguh.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Їa U ngin ïadem, ïa U ngin ïanguh,`',
          '`Ka dohnud jong ngi, Ah Trai to pynpluh;`',
          "`Ka burom bad ïaroh h'U Jisu ngin ai,`",
          '`Jingnguh ïa U junom, Un synshar khlem [wai.`',
        ],
      },
    ],
  },
  {
    id: 'song-576',
    title: 'JINGЇAROH ЇA U BLEI',
    metadata: {
      number: 576,
      language: 'khasi',
      composer: 'H.R.',
      syllables: '',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          "`Їaroh ï'U Blei ha ki byneng,`",
          "`Їaroh ï'U Blei, ïaroh ï'U Blei;`",
          "`Їaroh ï'U Blei ha ki byneng,`",
          '`To burom ruh junom.`',
          "`Їa! ngin ïa riwai lang ï'U Trai,`",
          '`Lem bad ki angel la dang shai;`',
          "`Ka jingbyna ba bha ï'u briew,`",
          "`B'la shem ka lad sh'U Blei ban kiew.`",
          "`Їaroh ï'U Blei ha ki byneng,`",
          '`Їaroh, ïaroh, ïaroh, ïaroh,`',
          '`Їaroh junom ïa U Blei.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          "`Їaroh ï'U Blei ha ki byneng,`",
          "`Їaroh ï'U Blei, ïaroh ï'U Blei;`",
          "`Їaroh ï'U Blei ha ki byneng,`",
          '`To burom ruh junom.`',
          "`Ha khymih ka sngi b'U la paw,`",
          '`Na neng U Nongpynim ba khraw;`',
          '`Ka jingsuk ha ka pyrthei shong,`',
          "`Ka jingman bha ï'u bynriew long.`",
          "`Їaroh ï'U Blei ha ki byneng,`",
          '`Їaroh, ïaroh, ïaroh, ïaroh,`',
          '`Їaroh junom ïa U Blei.`',
        ],
      },
    ],
  },
  {
    id: 'song-577',
    title: 'Jisu Un synshar kat haba',
    metadata: {
      number: 577,
      language: 'khasi',
      composer: 'H.L.',
      syllables: 'L.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Jisu Un synshar kat haba,`',
          '`Ka sngi ka sbai bad ka thaba;`',
          '`Hima kan ïar na kut sha kut,`',
          "`Haduh b'u bnai un ym ngen shuh.`",
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Ki jingduwai kin kiew sha U,`',
          '`Jingïaroh kin thung Syiem ïa U;`',
          '`Kyrteng jong U iwbih kan sieng,`',
          '`Lem bad ki jingkñia man ka sngi.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          "`Jingkyrkhu kat sha b'U synshar,`",
          '`Koidi rynsied ban hap ki nar;`',
          '`Ba tlot ki shem ka jingjahthait,`',
          '`Bad ba kyrduh jingdap kyrhai.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Te, pyrthei baroh kan wallam,`',
          '`Burom kynti ïa la U Syiem;`',
          '`Ki angel kin rwai kin ïakmen,`',
          '`Pyrthei kan pynbud jam, AMEN.`',
        ],
      },
    ],
  },
];