import { SongT } from "~/src/types/song";

export const kiJingrwaiIaKiKhynnah: SongT[] = [
  {
    id: 'song-592',
    title: 'Jisu U ieit ïa nga',
    metadata: {
      number: 592,
      language: 'khasi',
      composer: 'J.C.E.',
      syllables: 'S.S. 1155',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Jisu Khrist U ieit ïa nga,`',
          '`Na ka Baibl nga tip bha;`',
          '`Kiba rit ki long jong U,`',
          '`La ki tlot, U khlaiñ ma U.`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: ["`H'oid U ieit ïa nga, (3)`", '`Ka Baibl hi ka ong.`'],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Jisu Khrist U ieit ïa nga,`',
          '`U la ïap ha diengphyna;`',
          '`Khyrdop byneng U la plie,`',
          '`Ba ngin ïoh ban rung ma ngi.`',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          '`Jisu Khrist U ieit ïa nga,`',
          '`Un long lok ïa nga, Un da;`',
          '`Lada nga ïai ieit ïa U,`',
          '`Ha byneng ngan ïoh shong duh.`',
        ],
      },
    ],
  },
  {
    id: 'song-593',
    title: 'Un lum ïa ki paila',
    metadata: {
      number: 593,
      language: 'khasi',
      composer: '',
      syllables: 'S.S. 1140',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Un sa wan hi, Un sa wan hi,`',
          '`Ban lum ïa ki paila;`',
          '`Paila baroh, paila kordor,`',
          "`B'la ieit, la ki jong.`",
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`Kum ki khlur shai itynnad,`',
          "`B'la thep ha pansngiat;`",
          '`Kin sa phyrnai, kin tyngshaiñ,`',
          "`Mawkordor b'Un deng.`",
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Un sa lum lang, Un sa lum lang,`',
          '`Ki mawkor ka hima;`',
          '`Kiba khuid phar, kiba sngur phar,`',
          "`B'la ieit, la ki jong.`",
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          '`Khynnah tipsngi, khynnah tipsngi,`',
          "`Baieit i'U Nongsiewspah;`",
          '`Long ki paila, paila baroh,`',
          "`B'la ieit, la ki jong.`",
        ],
      },
    ],
  },
  {
    id: 'song-594',
    title: 'Shah ngan wan sha Me',
    metadata: {
      number: 594,
      language: 'khasi',
      composer: 'J.C.E.',
      syllables: '77.77.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Jisu jemnud bad ba bha,`',
          '`Peit sha iba rit kum nga;`',
          '`Isnei ba nga bieit eh,`',
          '`Shah ïa nga ban wan sha Me.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Ban ïoh wan sha Me nga thrang,`',
          '`Trai baieit, ïa nga wat khang;`',
          '`Ha ka hima khuid jong Me,`',
          '`Ah to ai ba ngan shongneh.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Nga da kwah kum Me ban long,`',
          '`Hajan jong Me ai ngan shong;`',
          '`Me ba isnei bad ba sbun,`',
          '`Ban long kumta ngan sngewhun.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Te ngan ïaroh junom duh,`',
          '`Bad ngan shakri ïa Me ruh;`',
          '`Kumta ka pyrthei kan i,`',
          '`Їa U Jisu da nga hi.`',
        ],
      },
    ],
  },
  {
    id: 'song-595',
    title: 'Burom ïa U Jisu',
    metadata: {
      number: 595,
      language: 'khasi',
      composer: 'W.M.J.',
      syllables: '65.65.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Burom ïa U Jisu,`',
          "`Namar b'U la shah;`",
          '`U la siew ka kuna,`',
          '`Halor diengphyna.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Jingaiei bad jingim,`',
          '`Kiba kordor tam;`',
          '`U la ai U Jisu,`',
          '`Da ka jor ka snam.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Katba ïoh ban synreit,`',
          '`Da ka snam ba kor;`',
          '`Ngi la jop ki nongshun,`',
          '`U Blei, U ai bor.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Riwai to nang riwai,`',
          '`Da ka sur ba jam;`',
          '`Їaroh ïa U Jisu,`',
          '`Bad ka bor ka snam.`',
        ],
      },
    ],
  },
  {
    id: 'song-596',
    title: 'Tyngshaiñ, U ong U Jisu',
    metadata: {
      number: 596,
      language: 'khasi',
      composer: 'J.J.',
      syllables: 'S.S. 1138',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Tyngshaiñ, ong Jisu, tyngshaiñ, tyngshaiñ ber,`',
          '`Kum sharak rit mynmiet jingshai ka la her;`',
          '`Ka pyrthei ka la dum, te to tyngshaiñ,`',
          '`Ha ka ïing ka jong phi khlem sngewlehraiñ.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Tyngshaiñ, ong Jisu, tyngshaiñ ki jong nga,`',
          '`Lada phi man jyngut, kata Ngam sngewbha;`',
          '`Na byneng Ngan khymih la phin tyngshaiñ,`',
          '`Ha ki shnong ki jong phi khlem sngewlehraiñ.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Tyngshaiñ, ong Jisu, ha ki shnong kyndong,`',
          '`Bun jait ki jingsniew shisha ki ker sawdong;`',
          '`Pop, kyrduh, bad sngewsih, te to tyngshaiñ,`',
          '`Ha ka ri ka jong phi khlem sngewlehraiñ.`',
        ],
      },
    ],
  },
  {
    id: 'song-597',
    title: 'Ki khynnah Khristan',
    metadata: {
      number: 597,
      language: 'khasi',
      composer: '',
      syllables: 'L.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Ngi long ki khynnah kiba rit,`',
          '`Ka spah bad burom ruh ngim don;`',
          '`Ban long ki nongtrei ki jong Me,`',
          '`Ko Nongpynim ba ieit ngi mon.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Ki khynnah Khristan baroh phar,`',
          '`Ki don ka thyma man ka sngi;`',
          '`Ban jop ki pop ba rit ba khraw,`',
          '`Ko Jisu, to ïarap ïa ngi.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Ka dohnud bunsien ka dap lin,`',
          '`Da sarong bad da jingsngewmeng;`',
          '`Ki ktien pynsngewsih ngi shait kren,`',
          '`Ki ummat bitar ki mih teng.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`To ai ngin kren ki ktien ba bang,`',
          '`Ban ym pynmong ki lok ki jor;`',
          '`Їa baroh ki jingsniew ngin jop,`',
          '`U Kapten jong ngi Un ai bor.`',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          '`Ngi dei ban bah ka diengphyna,`',
          '`Ki khynnah baroh ha ka ri;`',
          '`Ban ieit, ban shakri man ka sngi,`',
          "`Ї'U Jisu Khrist U Trai jong ngi.`",
        ],
      },
    ],
  },
  {
    id: 'song-598',
    title: "Hosanna, ï'U Khun u David",
    metadata: {
      number: 598,
      language: 'khasi',
      composer: 'H.S.R.',
      syllables: '76.76.D.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Hosanna, jam Hosanna,`',
          '`Ki khynnah ki ïarwai;`',
          '`Ban pynher la jingïaroh,`',
          "`Ї'U Jisu Khrist U Trai.`",
          "`Ї'U Jisu Uba ju rah,`",
          '`Їa ki ha la shadem;`',
          '`Їa U ki wan ban ainguh,`',
          '`Їa U ki wan ban dem.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Na lum Olib ba jymgam,`',
          "`Ki bud ï'U Khrist U Trai;`",
          '`Ki kaweh la ki tnat tlai,`',
          '`Ki riwai de kyrhai.`',
          '`Hosanna, jam Hosanna,`',
          "`Ї'U Khun u Dabid Syiem;`",
          '`Uba la wan ban pyllait,`',
          '`Na pop bad na jingtim.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Hosanna, jam Hosanna,`',
          '`Їa kajuh ngin ïa rwai;`',
          '`Namar ïa ngi la siewspah,`',
          "`Da kuna b'U la ai.`",
          '`Їa U to ai ngin shakri,`',
          '`Da dohnud sngur baroh;`',
          '`Mynta bad ha la ka rta,`',
          "`Ї'U junom ngin ïaroh.`",
        ],
      },
    ],
  },
  {
    id: 'song-599',
    title: "Burom Syiem ï'U Jisu",
    metadata: {
      number: 599,
      language: 'khasi',
      composer: 'E.H.W.',
      syllables: '66.66.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Wan khynnah to ïaroh,`',
          '`Haleluïa! Amen;`',
          "`Burom ï'U Khrist baroh,`",
          '`Haleluïa! Amen.`',
          "`Ї'U Jisu pynlong Syiem,`",
          '`Hapoh la ka mynsiem;`',
          '`Ngin ainguh katba im,`',
          '`Haleluïa! Amen.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Wan, khynnah, ïaroh jam,`',
          '`Haleluïa! Amen;`',
          '`Trai Jisu, khraw ka nam,`',
          '`Haleluïa! Amen.`',
          '`U long U Nongpynim,`',
          '`Ba ieit na mynbarim;`',
          '`U ai la ka jingim,`',
          '`Haleluïa! Amen.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          "`Junom ngin nguh ï'U Trai,`",
          '`Haleluïa! Amen;`',
          '`Jingiaroh ngin ïa ai,`',
          '`Haleluïa! Amen.`',
          '`Ha bneng lang ngin ïashem,`',
          '`Ha khmat ka khet ba skhem;`',
          '`Ban burom Syiem to dem,`',
          '`Haleluïa! Amen.`',
        ],
      },
    ],
  },
  {
    id: 'song-600',
    title: 'Sawdong ka khet U Blei haneng',
    metadata: {
      number: 600,
      language: 'khasi',
      composer: 'E.H.W.',
      syllables: 'C.M. & REFRAIN',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Sawdong ka khet U Blei haneng,`',
          '`Khynnah bun lak ki ïeng;`',
          '`Baroh ki pop jong ki la weng,`',
          '`Ah suk ka jingïaseng,`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: ['`Ki ïariwai, Burom, Burom.`'],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Kumno ki poi ki khynnah duk,`',
          '`Sha byneng, ri sngewbha;`',
          '`Ba don ka kymen bad jingsuk,`',
          '`Kumno ki poi hangta ?`',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          "`Namar b'U Khrist U shah jingïap,`",
          '`U pynmih la ka snam;`',
          '`Ban sait ïa ki ka wah la dap,`',
          '`Ka pop jong ki la dam,`',
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          '`Hangne ha pyrthei, ki la wad,`',
          "`Ї'U Jisu Khrist U Trai;`",
          '`Bad kumta ki la shem ka lad`',
          '`Ban shong bad U khlem wai,`',
        ],
      },
    ],
  },
  {
    id: 'song-601',
    title: 'Shah ïa ki khynnah ban wan ha nga',
    metadata: {
      number: 601,
      language: 'khasi',
      composer: 'S.M.R.',
      syllables: 'R.S. 683',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Ki kymie na Salem,`',
          "`Ki khun ki lam sh'U Jisu;`",
          '`Ki synran te kim shah kin wan,`',
          '`Ki beh noh ruh ïa ki;`',
          '`U Jisu Kynrad U ïohi,`',
          '`U peit sngewbha, U ong ha ki,`',
          '`“Shah ïa ki khynnah ba kin wan ha Nga.”`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`“Ngan shim kum ïa kita,`',
          '`Ban kydup ha ka shadem;`',
          '`Ngan long nongsumar ïa ki ruh,`',
          '`Wat beh noh te ïa ki;`',
          '`Ha nga ki dohnud te kin ai,`',
          '`Kin shong bad nga ha ri jingshai,`',
          '`Shah ïa ki khynnah ba kin wan ha nga.”`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`U sybun U Jisu,`',
          "`B'U khot sngewbha ïa kita;`",
          '`Bun hajar pynban ki dang sah,`',
          '`Ka nam jong U kim tip;`',
          '`Kim pat ithuh ka ktien U Blei,`',
          '`Kim pat ïohsngew ka ktien aiei,`',
          '`“Shah ïa ki khynnah ba kin wan ha Nga.”`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Ki riewdum to wallam,`',
          '`To ring ki bynriew baroh;`',
          '`Kin bret ïa ki bleithaw jong ki,`',
          '`Ban ngeit ka ktien jong Me;`',
          '`Pynpaw ïa lade Ah U Blei,`',
          '`Pyni ha ki ka jingaiei,`',
          '`Khot ïa ki khynnah ban wan lut ha Me.`',
        ],
      },
    ],
  },
  {
    id: 'song-602',
    title: 'Ei, ko khun phi thmu ?',
    metadata: {
      number: 602,
      language: 'khasi',
      composer: 'R.E.',
      syllables: '65.65',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Ei, ko khun, phi thymu,`',
          '`Ha la ka jingim ?`',
          '`Shakri ïa U Jisu,`',
          '`Їaid ka lynti khim.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Khuid ka dohnud samla,`',
          '`Khuid ka ktien ba kren;`',
          '`Kynmaw la ka burom,`',
          '`Їa U Khrist wat len.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Kynmaw la U Kynrad,`',
          '`Bud dienjat jong U;`',
          '`Na diengphna ba shitom,`',
          '`Wat da kynran shuh.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Їa ki thiep ka jingim,`',
          '`Kiew da bor U Blei;`',
          '`Ynda poi ha kliar,`',
          '`Jingïaroh phin sei.`',
        ],
      },
    ],
  },
  {
    id: 'song-603',
    title: 'U Lok ki khynnah rit',
    metadata: {
      number: 603,
      language: 'khasi',
      composer: 'S.T.',
      syllables: '86.76.76.76.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Don U Lok ïa ki khynnah rit,`',
          '`Ha neng ki khlur phyrnai;`',
          '`U Lok U bym lah kylla,`',
          '`La jingieit ba janai.`',
          '`Ym kum ki lok ha pyrthei,`',
          '`Ba lah ban kylla pat;`',
          '`Une dei U Lok, bad phi,`',
          '`Ban im ban ïap ryngkat.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Don ka ri ïa ki khynnah rit,`',
          '`Ha neng ki khlur phyrnai;`',
          '`Hangta Jisu U synshar,`',
          '`Ha ri ba suk kynjai.`',
          '`Ha pyrthei ym don kat ka,`',
          '`Ba bit ban ïanujor;`',
          '`Jingsuk ba khlem jingïapher,`',
          '`Ym don ba poh ne kor.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Don jingrwai ïa ki khynnah rit,`',
          '`Ha neng ki khlur phyrnai;`',
          '`Kin tem la duitara ksiar,`',
          '`Bad rah la ki diengtlai.`',
          '`Ha neng ka spah la kynshew,`',
          '`Ka don ha U Khrist hi;`',
          '`Ale, ko khynnah baieit,`',
          '`Їa ka phin ïoh kynti.`',
        ],
      },
    ],
  },
  {
    id: 'song-604',
    title: 'Їaroh ïa U',
    metadata: {
      number: 604,
      language: 'khasi',
      composer: 'H.J.',
      syllables: '',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Їaroh, ïaroh, phi ki khynnah baroh,`',
          "`Ї'U Jisu Uba ieit;`",
          '`Їaroh, ïaroh, phi ki khynnah baroh,`',
          "`Ї'U Jisu Uba ieit.`",
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`To nguh, to nguh, phi ki khynnah baroh,`',
          "`Ї'U Jisu Uba ieit;`",
          '`To nguh, to nguh, phi ki khynnah baroh,`',
          "`Ї'U Jisu Uba ieit.`",
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`To ieit, to ieit, phi ki khynnah baroh,`',
          "`Ї'U Jisu Uba ieit;`",
          '`To ieit, to ieit, phi ki khynnah baroh,`',
          "`Ї'U Jisu Uba ieit.`",
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Burom, burom, phi ki khynnah baroh,`',
          "`Ї'U Jisu Uba ieit;`",
          '`Burom, burom, phi ki khynnah baroh,`',
          "`Ї'U Jisu Uba ieit.`",
        ],
      },
    ],
  },
  {
    id: 'song-605',
    title: 'Jisu U sngewbha ïa ki khynnah',
    metadata: {
      number: 605,
      language: 'khasi',
      composer: '',
      syllables: '',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Jisu U sngewbha ki khynnah,`',
          '`Dap da jingisnei U long;`',
          '`Ha la ka sngi ruh U sumar,`',
          '`Ha khet ka bneng la U shong.`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`Nga, nga tip bha ba U dang ieit,`',
          '`Ba U la pdiang ruh ïa nga;`',
          '`U dang ieit, ïa U ngan ïaroh,`',
          '`U la shah ha ka diengphyna.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Lada kylli, nga suk kumno,`',
          '`U la ïap namar jong nga;`',
          '`Bad U ong ruh ha ka Baibl,`',
          '`“Khynnah rit to wan ha Nga.”`',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          "`Kumta nga la wan sh'U Jisu,`",
          '`Kumba dei ïa nga ban leh;`',
          '`Nga da duwai da ka dohnud,`',
          '`Ba ha U ngan ïoh ïaineh.`',
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          '`Ki jingduwai jong ki khynnah,`',
          '`Nga tip ba un sngap U Trai;`',
          "`Ale, ale, wan sh'U Jisu,`",
          "`Ї'U ngin ïaroh khlem da wai.`",
        ],
      },
    ],
  },
  {
    id: 'song-606',
    title: 'Tyngshaiñ kum ki khlur',
    metadata: {
      number: 606,
      language: 'khasi',
      composer: '',
      syllables: '',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Ngi long ki khynnah ba rit,`',
          '`Kum ki khlur ngi tyngshaiñ;`',
          '`Hapdeng jingdum jong ka miet,`',
          '`Khrik khrik ngi ïai tyngshaiñ.`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`Tyngshaiñ, tyngshaiñ, tyngshaiñ,`',
          '`Kum ki khlur rit ha bneng;`',
          '`Man la ki par ngi ïai tyngshaiñ,`',
          '`Jingsuk, jingkmen kylleng.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Khrip khrip kumba khih ki khlur,`',
          '`Katba sha tbian ki peit;`',
          '`Ngi ruh ngin nang ïai tyngshaiñ,`',
          '`Kat sha ba ngi nang leit.`',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          '`Kum ki khlur rit ha suiñ bneng,`',
          '`La ngi trei ne lehkai;`',
          '`Barabor ngin ïai tyngshaiñ,`',
          '`Sha jingsniew ngin ym phai.`',
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          '`Hosanna ! jam Hosanna !`',
          '`Їa U Trai ngin ïaroh;`',
          '`Ngi long mawkordor U Khrist,`',
          '`Jingkmen ki briew baroh.`',
        ],
      },
    ],
  },
  {
    id: 'song-607',
    title: 'U Blei U ieit ïa nga',
    metadata: {
      number: 607,
      language: 'khasi',
      composer: '',
      syllables: '',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`U Blei U thaw ki sim baroh,`',
          "`Bad 'tiew bha rong b'la jied;`",
          '`Ha la ka ktien ki ïai ïaroh,`',
          '`“U Blei U long jingieit.”`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`U Blei U ieit - to ngin ïaroh,`',
          '`U Blei u ieit ïa nga;`',
          '`Lada U ieit ki sim barit,`',
          '`U Blei U ieit ïa nga.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Iwei i sim ïing in ym hap,`',
          '`Khlem ka jingtip I Pa;`',
          '`U ieit ki sim rit ban ïarap,`',
          '`U Blei U ieit ïa nga.`',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          "`U Blei ï'u tiew lili U thaw,`",
          '`Ka jingbha dur shisha;`',
          '`U ieit ki tiew kulab ba saw,`',
          '`U Blei U ieit ïa nga.`',
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          '`Ngin long ki syntiew jong U Trai,`',
          '`Ban pyniwbih la Ri;`',
          '`Ngin tyngshaiñ kum ki khlur phyrnai,`',
          '`U Blei U ieit ïa nga.`',
        ],
      },
    ],
  },
  {
    id: 'song-608',
    title: 'Khynnah ka Jerusalem',
    metadata: {
      number: 608,
      language: 'khasi',
      composer: 'O.H.R.',
      syllables: '',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Ki khynnah Jerusalem,`',
          '`Kyrteng Jisu rwai shitrhem;`',
          '`Ki khynnah ba mynta ruh,`',
          '`Ki rwai ïaroh ïa kajuh.`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`Sngap! Sngap! Sngap! Ki khynnah ki ïarwai,`',
          '`Sngap! Sngap! Sngap! Ki ïaroh khlem da wai,`',
          '`Jam Hosanna! Jam Hosanna! Jam Hosanna! [ïa U Trai.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          "`La hikai ban ieit ï'U Trai,`",
          '`Ban pule ka ktien khlem wai;`',
          '`Lynti sha bneng de ban ïoh,`',
          "`Burom ai sh'U Blei baroh.`",
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          '`Bad rit bad khraw baroh lang,`',
          '`Ki rwai lem ki sur ba bang;`',
          '`Ryndang ba syiang ki pynjam,`',
          '`Hosanna! kiba jrong tam.`',
        ],
      },
    ],
  },
  {
    id: 'song-609',
    title: 'Ka Jingsumar ieit U Blei',
    metadata: {
      number: 609,
      language: 'khasi',
      composer: '',
      syllables: '77.77.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Jisu ba khuid, ba janai,`',
          '`Khmih ïa nga i khynnah rit;`',
          '`Me la phah ïa la jingshai,`',
          '`Kaba beh jingdum ka miet.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Me phah ka sngi ban tyngshaiñ,`',
          '`Halor pyrthei itynnad;`',
          '`Ban ai jingsyaid, ban pynkhlaiñ,`',
          '`Jingthung bad syntiew ha ka.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Dang step phyrngab, sim ki rwai,`',
          '`Sngewbha halor tnat ki dieng;`',
          '`Da sur bang, ïaroh ki ai,`',
          "`Ї'U Nongthaw ba long U Syiem.`",
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Me ïa ki sim Uba bsa,`',
          '`Їa nga ruh bsa man ka sngi;`',
          '`Їa U Mynsiem Bakhuid ai,`',
          '`Khlem ma U ngam lah ban im.`',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          '`Їa nga, Trai, pynlong jemnud,`',
          '`Kumba dei ia u khynnah;`',
          '`Baroh shisngi ialam ruh,`',
          '`Bthah aiu ngan ong, ngan leh.`',
        ],
      },
      {
        id: 'verse-6',
        order: 6,
        type: 'verse',
        lines: [
          '`Haba lehkai haba trei,`',
          '`Ai ngan san ha la ka sngi;`',
          '`Ynda por Men wan la dei,`',
          '`Shim ïa nga sha lade hi.`',
        ],
      },
    ],
  },
  {
    id: 'song-610',
    title: 'Nga ieit ban sngap ka khubor',
    metadata: {
      number: 610,
      language: 'khasi',
      composer: 'H.S.R.',
      syllables: 'S.S. 46.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Nga ieit ban sngap ka khubor,`',
          '`Ba angel ki ïalap;`',
          "`Kumno b'U Syiem ka burom,`",
          '`La wan long briew ban ïap;`',
          '`La nga la pop bad la jot,`',
          '`Їa kane nga tip bha;`',
          '`Ba U la wan ban pynim,`',
          "`Namar b'U ieit ïa nga.`",
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`Nga ieit ban sngap ka khubor,`',
          '`Ba angel neng ki ïalap;`',
          "`Kumno b'U Syiem ka burom,`",
          '`La wan longbriew ban ïap.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Nga sngewbha ba U Jisu,`',
          '`Long khynnah kum ma nga;`',
          '`Ban pyni kumno ngan im,`',
          '`Ka jingim kaba bha.`',
          '`Bad mynta lada ngan bud,`',
          "`Ї'U Lynti, Jingshisha;`",
          '`Um klet ïa nga da lei lei,`',
          "`Namar b'U ieit ia nga.`",
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          '`Jingriwai bang kan ïai long,`',
          '`Ban ïaroh ïa U Khun;`',
          '`Jingkynud sngur ka dohnud,`',
          '`U Trai un pydiang hun;`',
          '`U Jisu Khrist U kular,`',
          '`Ba ngan ïoh leit shisha;`',
          '`Ban riwai bad ki angel,`',
          "`Namar b'U ieit ïa nga.`",
        ],
      },
    ],
  },
  {
    id: 'song-611',
    title: 'Lada wan sha U Jisu',
    metadata: {
      number: 611,
      language: 'khasi',
      composer: '',
      syllables: 'C.H. No. 669, Woodbrook (65.65 & Refrain)',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Lada wan sha Jisu,`',
          '`Jingkmen un pyndap;`',
          '`Jingsngewbha ruh Un ai,`',
          '`Ha jingsngewsih sat.`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`Lada wan sha Jisu,`',
          '`Da shisha ngan suk;`',
          '`Da jingieit U ïai khot,`',
          '`Nga barit baduk.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Lada wan sha Jisu,`',
          '`Jingdwai ruh un sngap;`',
          '`Un ieit ïa nga shisha,`',
          '`Pop jong nga un map.`',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          '`Lada wan sha Jisu,`',
          '`Un bytin ïa nga;`',
          '`Un ïalam beit ïa nga,`',
          '`Sha Ri kaba bha.`',
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          '`Ha ki jaiñkup phyrnai,`',
          '`Ngin ïakynduh lang;`',
          '`Ngin ïohi ïa U Trai,`',
          '`Ha Ri ka jingshai.`',
        ],
      },
    ],
  },
  {
    id: 'song-612',
    title: 'Kti ba rit aïu kin leh ?',
    metadata: {
      number: 612,
      language: 'khasi',
      composer: '',
      syllables: 'C.H. No. 670, Child Service (76.887)',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Kti ba rit aïu kin leh,`',
          "`Ban pynsngewbha ï'U Blei?`",
          '`Kti ba rit kam babha kin trei,`',
          '`Їarap ba shitom ha pyrthei;`',
          '`Ban long kumne, nga kwah.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          "`Shyntur ba rit aïu 'nleh,`",
          "`Ban pynsngewbha ï'U Blei?`",
          '`Shyntur ba rit jingsawa sei,`',
          "`Jingduwai, jingïaroh ï'U Blei;`",
          '`Ban long kumne, nga kwah.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Khmat ba rit aïu kin leh,`',
          "`Ban pynsngewbha ï'U Blei?`",
          '`Ki khmat ba rit sha U kin peit,`',
          '`Ban ieit ka Ktien Bakhuid U Blei;`',
          '`Ban long kumne, nga kwah.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          "`Dohnud ba rit aïu 'nleh,`",
          "`Ban pynsngewbha ï'U Blei?`",
          '`Dohnud ba rit ïa U ban ai,`',
          "`Ban ieit ï'U Jisu Khrist U Trai;`",
          '`Ban long kumne nga kwah.`',
        ],
      },
    ],
  },
  {
    id: 'song-613',
    title: 'Wat klet duwai',
    metadata: {
      number: 613,
      language: 'khasi',
      composer: '',
      syllables: 'ALEX - III No. 39',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Wat klet duwai, Blei U hajan,`',
          '`Wat klet duwai, ïa phi Un shan;`',
          '`La jingkular Un pyndep hi,`',
          '`Wat klet duwai, Un sngew ïaphi.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Wat klet duwai, ha jingdonkam,`',
          '`Wat klet duwai, phin ïoh khamtam;`',
          '`Ki jingkyrpad la rit ne khraw,`',
          '`Wat klet duwai, na U kin jaw.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Wat klet duwai, ha jingpynshoi,`',
          '`Wat klet duwai, ïarap U kloi;`',
          '`Trai hi la shah pynshoi kum ngi,`',
          '`Wat klet duwai, Un da ïaphi.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Wat klet duwai, ha jingkhuslai,`',
          '`Wat klet duwai, Un ai jingshai;`',
          '`U tip ma U kumno ban leh,`',
          '`Wat klet duwai, ha U ïaineh.`',
        ],
      },
    ],
  },
  {
    id: 'song-614',
    title: "Khynnah ba rit ïaroh ï'U Blei",
    metadata: {
      number: 614,
      language: 'khasi',
      composer: '',
      syllables: '',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          "`Khynnah ba rit ïaroh ï'U Blei,`",
          '`Na bneng hi U peit ïaphi;`',
          '`Їaroh namar jingieit bashlei,`',
          "`Ba ï'U Khun U ai ha ngi.`",
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`Rwai Hosanna, rwai Hosanna,`',
          '`Їa ka kyrteng Jisu Khrist;`',
          '`Rwai Hosanna, rwai Hosanna,`',
          '`Їa ka kyrteng Jisu Khrist.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`La ka khet burom U iehnoh,`',
          '`Ban long khynnah kum ma ngi;`',
          '`Haba khynnah rit ki ïaroh,`',
          '`Da ka shkor U sngap ïa ki.`',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          "`Khynnah ba rit ïaroh ï'U Blei,`",
          '`Long tang ma U lok baneh;`',
          '`Ynda la wai jingim pyrthei,`',
          '`Ha bneng bad U ngin shongneh.`',
        ],
      },
    ],
  },
  {
    id: 'song-615',
    title: 'Jisu U Lok ki khynnah',
    metadata: {
      number: 615,
      language: 'khasi',
      composer: '',
      syllables: '',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Jisu U Lok ki khynnah,`',
          '`U khot sha U ïa ki;`',
          '`U aiti la ka jingim,`',
          '`Ka khyrdop bneng ban plie.`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`Jisu U lok ki khynnah,`',
          '`Jisu Jisu;`',
          '`U aiti ïa la ka jingim,`',
          '`U Lok jong ki khynnah.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Jisu U Lok ki khynnah,`',
          '`Bad ki U ïakmen lem;`',
          '`U tip ruh khuslai jongki,`',
          '`U kloi de ban pynjem.`',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          '`Jisu U Lok ki khynnah,`',
          '`U long U ba ïaineh;`',
          '`Їa kiba shaniah ha U,`',
          '`La jingaiei U theh.`',
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          '`Jisu U Lok ki khynnah,`',
          '`U kwah ïa ki ban trei;`',
          '`Sha ka kam da mon sngewbha,`',
          '`Ka bor ruh de ban sei.`',
        ],
      },
    ],
  },
  {
    id: 'song-616',
    title: 'To long bad nga Ah Trai',
    metadata: {
      number: 616,
      language: 'khasi',
      composer: 'W.R.L.',
      syllables: '',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`To long ma Me ka bor jongnga,`',
          '`Lama jong me ban rah;`',
          '`Nongshun ba bun ban jop ïa ki,`',
          '`Da bor jong Me nga lah.`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`To long bad nga Jisu jemnud,`',
          '`To long bad nga Ah Trai;`',
          '`Ha la ka sngi ïa Me ngan ieit,`',
          '`Junom ruh ngan ïai rwai.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`To long ma Me ryndang jong nga,`',
          '`Sur bathiang ba ngan rwai;`',
          '`Da ki ïa kiwei ban ïoh khring,`',
          '`Sha khet ka jong Me Trai.`',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          '`To long ma Me met bad mynsiem,`',
          '`Mon ka jong me ban leh;`',
          '`Ha por bad jinglong baroh Trai,`',
          '`Bad nga to ïai shongneh.`',
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          '`To long ma Me lynti jong nga,`',
          '`To long ruh ka jingshai;`',
          '`Haduh ba jingim hi kan wai,`',
          '`To long ma Me ko Trai.`',
        ],
      },
    ],
  },
  {
    id: 'song-617',
    title: 'Jingim jongnga pynlong Ah Blei',
    metadata: {
      number: 617,
      language: 'khasi',
      composer: 'A.W.T.',
      syllables: 'S.S. No. 1143.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '`Jingim jong nga, pynlong Ah Blei,`',
          '`Kum sharak rit phyrnai;`',
          '`Ba tyngshaiñ noh ha ka pyrthei,`',
          '`Kat shaba leit bad phai.`',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          '`Jingim jong nga, pynlong Ah Blei,`',
          '`Kum syntiew rit iewbih;`',
          '`Ba phuh ha ïing la jong marwei,`',
          '`Ba pynthiang ïa ka Ri.`',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          '`Jingim jong nga, pynlong Ah Blei,`',
          '`Kum jingrwai rit babang;`',
          '`Ba pyntngen ki ba dap khuslai,`',
          '`Pynkmen ïa baroh lang.`',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          '`Jingim jong nga, pynlong Ah Blei,`',
          '`Kum diengduh rit ba khlaiñ,`',
          '`Ban kyrshan ki ba tlot baswai,`',
          '`Їa baroh ban pynshngaiñ.`',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          '`Jingim jong nga, pynlong Ah Blei,`',
          '`Kum sur jingrwai ïaroh;`',
          '`Ba ngeit ha jingïalam jong Me,`',
          '`Ha lynti ïaid baroh.`',
        ],
      },
    ],
  },
  {
    id: 'song-618',
    title: 'Shaphang U Jisu',
    metadata: {
      number: 618,
      language: 'khasi',
      composer: 'S.R.L.',
      syllables: 'ALEX - III No. 429.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          "`Ai ba ngan kham ieit ï'U Jisu,`",
          '`Ai ngan ïalap kyrteng jong U;`',
          '`Namar jingpynim ba phylla,`',
          "`B'U ïap ïapli namar jongnga.`",
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`Tang shaphang U Jisu,`',
          '`Tang shaphang U Jisu;`',
          '`Ai ngan ïai rwai ha la ka rta,`',
          '`Jingsiewspah bymjukut ïa nga.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          '`Jinglong babha Jisu ban beh,`',
          '`Mon bakhuid jong U ruh ban leh;`',
          '`Ah Blei ïarap ma Me ïa nga,`',
          '`Ngan lah ban ïaid lynti diengphna.`',
        ],
      },
    ],
  },
  {
    id: 'song-619',
    title: 'Ha jingshai',
    metadata: {
      number: 619,
      language: 'khasi',
      composer: '',
      syllables: 'ALOTE',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          "`Sh'U Nongpynim ïa ngin leit,`",
          '`Ha jingshai, ha jingshai;`',
          '`Lynti pyrthei Un pynbeit,`',
          '`Ha jingshai U Blei.`',
          '`Na pop Un pynim ïa ngi,`',
          '`Ha jingshai, ha jingshai;`',
          '`Un pynkhuid da lade hi,`',
          '`Ha jingshai U Blei.`',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          '`Ha ka jingshai to ngin ïaid,`',
          '`Ka jingshai, ka jingshai;`',
          '`Ha ka jingshai to ngin ïaid,`',
          '`Ka jingshai U Blei.`',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          "`Ї'U Khrist ngi kwah ban shakri,`",
          '`Ha jingshai, ha jingshai;`',
          '`Bor Un ai ma U ïa ngi,`',
          '`Ha jingshai U Blei.`',
          '`Pop bad soitan kim lah jop,`',
          '`Ha jingshai, ha jingshai;`',
          '`Jisu ïa ngi Un kdup khop,`',
          '`Ha jingshai U Blei.`',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          '`Jingïap kan wan ngim sngewphieng,`',
          '`Ha jingshai, ha jingshai;`',
          '`Jisu U don ngim sheptieng,`',
          '`Ha jingshai U Blei.`',
          '`Kumta Paradais ngin rung,`',
          '`Ha jingshai, ha jingshai;`',
          '`Shong sah bad Jisu khlem wai,`',
          '`Ha jingshai U Blei.`',
        ],
      },
    ],
  },
];