import { SongT } from '~/src/types/song';

export const kiJingrwaiShaphangKiIngKhristan: SongT[] = [
  {
    id: 'song-521',
    title: 'Ka Їing Khristan',
    metadata: {
      number: 521,
      language: 'khasi',
      composer: 'S.S. 231 (11.10.11.10.11.10.11.10.)',
      syllables: '11.10.11.10.11.10.11.10.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ki jingduwai, jingainguh, jingrwai ïaroh,`,
          `Kum ïing Khristan, baroh lang ngin ïasoh;`,
          `Ka ïing ba la kyrkhu, ka ïing ba la tei,`,
          `Long shisha ka ïing ba shong briew shong Blei.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Trai to kyrkhu ki rympei Khristan jong ngi,`,
          `Kin rhem jingdwai jingïaroh man ka sngi;`,
          `Mynmiet, mynstep 'tien Blei ngin ïasyllok lang,`,
          `Rympei Khristan kin shit kum ding ba klang.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Shisha, Ktien U Blei, ban plied man la ka sngi,`,
          `Jingbam mynsiem, ha ïing ha sem jong ngi;`,
          `Kum ïing Khristan ngin ïit shisha ïalade,`,
          `Ka ïing Khristan, long ïing Blei ba mane.`,
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          `U Trai Jisu jong ngi tang U hi marwei,`,
          `Man ki ïing ki sem Khristan long U Khlieh;`,
          `Nongrim jingim Khristan tang ha U la tei,`,
          `Soh bathiang ki sei haba paw ne rieh.`,
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          `Jingieit Blei kan synshar ha ki ïing ki sem,`,
          `Hapoh, habar pynpaw sha ka pyrthei;`,
          `Ka Gospel ban pynim kiba jot barem,`,
          `Ki soh ba bha na ïing Khristan kin sei.`,
        ],
      },
    ],
  },
  {
    id: 'song-522',
    title: 'Ka Їing Khristan',
    metadata: {
      number: 522,
      language: 'khasi',
      composer: 'S.S. 357',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Їing Khristan ba synshar U Blei,`,
          `Jingsuk ka don hangta;`,
          `Ki jingïaroh ba dap ba shlei,`,
          `Їa U ha la karta.`,
          `Tang ha U ban aiti,`,
          `Bad ïa U ban shakri;`,
          `Man la ka sngi man la ka por,`,
          `U long Uba kordor.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [`Man la ka sngi man la ka por,`, `U long Uba kordor.`],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Ka Ktien jong U Blei kaba kor,`,
          `Ha rympei ïing Khristan;`,
          `Tang ma ka hi kaba ai bor,`,
          `Mynsiem tlot ka kyrshan.`,
          `Jingkular don hangne,`,
          `Plied ïa ka ban pule:`,
          `Man la ka sngi man la ka por,`,
          `Ka long kaba donbor.`,
        ],
      },
      {
        id: 'chorus-2',
        order: 4,
        type: 'chorus',
        lines: [`Man la ka sngi man la ka por,`, `Ka long kaba donbor.`],
      },
      {
        id: 'verse-3',
        order: 5,
        type: 'verse',
        lines: [
          `Jingdwai na rympei ïing Khristan,`,
          `Kin ïai long borabor;`,
          `Lad tang kane ban roi ban san,`,
          `Lada ngi la ñiewkor.`,
          `Jingpynshoi u soitan,`,
          `Kim lah ban tur hajan;`,
          `Namar ha syndah jong U Trai,`,
          `Ka bor jingjop Un ai.`,
        ],
      },
      {
        id: 'chorus-3',
        order: 6,
        type: 'chorus',
        lines: [`Namar ha syndah jong U Trai,`, `Ka bor jingjop Un ai.`],
      },
      {
        id: 'verse-4',
        order: 7,
        type: 'verse',
        lines: [
          `U Jisu U kwah ban synshar,`,
          `Їing Khristan baroh phar;`,
          `Pdiang bad pynlong U Khlieh jong ka,`,
          `Un ri na ki jingma.`,
          `Lada kiwei kim treh,`,
          `Hukum jong U ban leh;`,
          `Ma nga lem bad ka ïing ngin ai,`,
          `JingshakriïaU Trai.`,
        ],
      },
      {
        id: 'chorus-4',
        order: 8,
        type: 'chorus',
        lines: [`Ma nga lem bad ka ïing ngin ai,`, `JingshakriïaU Trai.`],
      },
    ],
  },
  {
    id: 'song-523',
    title: 'Їa Me baroh shi ïing ngi nguh',
    metadata: {
      number: 523,
      language: 'khasi',
      composer: 'S.S. 873',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Їa Me Ah Jisu baieit ngi nguh,`,
          `Mynstep bad mynmiet duwan ngi buh;`,
          `Namar jingleh isnei ba ïai tuid,`,
          `Їa ka ïing jong ngi kum ka wah duid.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Baroh ngi dem, hooid, baroh ngi nguh,`,
          `Burom ïa Me shilynter jingim;`,
          `Baroh ngi dem, hooid, baroh ngi nguh,`,
          `Burom ïa Me shilynter jingim.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Їa Me Ah Jisu baieit ngi nguh,`,
          `Namar jingpynim, jingsiewspah ruh;`,
          `Halor ka diengphna ba Me la shah,`,
          `Їa ka pop jong ngi Me la siewspah.`,
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          `Їa Me Ah Jisu baieit ngi nguh,`,
          `Namar ki khun baieit jong ngi ruh;`,
          `Ki long ki mawkordor bad paila,`,
          `Ba pyndap jingkmen bad jingsngewbha.`,
        ],
      },
    ],
  },
  {
    id: 'song-524',
    title: 'Ngin ïa rwai ïaroh da ka jingkmen',
    metadata: {
      number: 524,
      language: 'khasi',
      composer: 'S.S. 510',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Їing Khristan ïing ki khun U Blei baim,`,
          `B'la siewspah d'U Khrist Nongpynim;`,
          `Ki ïaroh jam kyrteng U Jisu Khrist,`,
          `B'U la siewspah ka ïing jong ki.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Ngin rwai ïaroh da ka jingkmen,`,
          `Ngin rwai ïa ka jingsiewspah jong U;`,
          `Ngin rwai shitrhem da ka jingieit,`,
          `Katba sngi bad snem ki nang leit.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Ha la rympei duwan jong U ngin tei,`,
          `Jingsuk jingkmen na U ka shlei;`,
          `Haba ïa U ngi nguh ngi dem khlem wai,`,
          `Ym don jingsngewsih jingkhuslai.`,
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          `Ka shap jong U Nongpynim ba la shon,`,
          `Hapoh la rympei ai kan don;`,
          `Da jingduwai bad jingrwai ngin pynpaw,`,
          `Ba tang ma U, U long bakhraw.`,
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          `Ngin long jingshai ban pynshai sha kiwei,`,
          `Jingshai kan paw ha ka pyrthei;`,
          `Haba jingduwai ka rhem ha rympei,`,
          `La ngi bun ne don tang marwei.`,
        ],
      },
      {
        id: 'verse-5',
        order: 6,
        type: 'verse',
        lines: [
          `Ah Trai to ïarap ïa ngi ba ngin rwai,`,
          `Kum u briew jong me mynhyndai;`,
          `Їing jong nga, kan shakri tang ïa Me Trai,`,
          `Haduh ba jingim kan da wai.`,
        ],
      },
    ],
  },
];
