// @ts-ignore
import { SongT } from '~/src/types/song';

export const shaphangUBlei: SongT[] = [
  {
    id: 'song-001',
    title: 'U Blei Uba Halor Baroh',
    metadata: {
      number: 1,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Lowel (L.M.) O.C.H. 222',
      syllables: '88.88',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Don Uwei U Blei ha byneng,',
          'U Trai ia baroh ba la seng;',
          'U synshar hi na mynta rim;',
          'Ngan ieit, ngan iaroh katba im.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ki hukum don ba U la ai,',
          'Ban hikai ia ka mon U Trai;',
          'Ngan ngeit ka ktien jong U ba neh,',
          'Ba kaba hok, ba shisha eh.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'La wan ka Gospel Blei ha ngi,',
          'Ka jingsuk jai na ka la mih;',
          'Ha ka, Ah Blei, ngin shem ia Me,',
          'Ai bor ngin wad nongrim ba neh.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'La buh ka por ia nga ban iap,',
          'Leh kyndit eh ia nga kan lap;',
          'Ki samla bad ki khynnah ruh,',
          'Ki iap, ban khreh ngan ym tud shuh.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Ngan sumar ia ki por ba sah;',
          'To wan, Mynsiem, pynkhreh ia nga;',
          'Tang lap ka jingiap ngam lah phai,',
          'Ka aiom wad jingmap la wai.',
        ],
      },
    ],
  },
  {
    id: 'song-002',
    title: 'Ka Jingdon U Blei',
    metadata: {
      number: 2,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Oldenburg (87.87.) Iambic O.W. 77',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ka khyndew long ka jong U Trai,',
          'Jingdap kyrhai de jong ka;',
          'Ka pyrthei bad ki briew ki long,',
          'Ki jong U Trai ki paidbah.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka nongrim jong ka U la seng,',
          'Hapdeng ki um ka duriaw;',
          'Ha jingshlei um U pynskhem bha,',
          'Ia ka, ngi shngain ban kymraw.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Uei ban kiew sha iing U Trai,',
          'Ban ym phai khymat nangta?',
          'Ha lum ba kyntang Me, Ah Blei,',
          'Uei un ieng hangta?',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Riewkhuid ka dohnud bad ki ktî,',
          'Bym iaid ha lynti jubor;',
          'Sha kaba thala um ju phai,',
          'Um smai da kaba shukor.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Jingkyrkhu na U Trai un ioh,',
          'Ban kerkut baroh sawdong;',
          'Ka hok de na U Blei ba im,',
          'Ka jingpynim ba pynlong.',
        ],
      },
      {
        id: 'verse-6',
        order: 6,
        type: 'verse',
        lines: [
          'Ka pateng bynriew ba ju wad,',
          'L’U Kynrad ka long kane;',
          'Ah Blei u Jakob! ki iadem,',
          'Ban shem ka khymat jong Me.',
        ],
      },
    ],
  },
  {
    id: 'song-003',
    title: 'Ka Jingiaroh Ia Uwei-Lai',
    metadata: {
      number: 3,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Nicaea (11.12.12.10.) S.S. 22',
      syllables: '11.12.12.10',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Bakhuid, Bakhuid, Bakhuid, Bakhrawbor, Ah Blei!',
          'Dang step phyngab, Kynrad, ngi rwai nguh ia Me;',
          'Bakhuid, Bakhuid, Bakhuid, khlain bad dap jingsneng,',
          'Lai ngut ba tang Wei long U Trai ba neh!',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Bakhuid, Bakhuid, Bakhuid, riewkhuid ki iaroh,',
          'Baroh ki pangsngiat ksiar, ki loi’t ban nguh ia Me;',
          'Kherub bad ki Seraph ki mane dem baroh,',
          'Ia Me ba junom U Juh Me iaineh.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Bakhuid, Bakhuid, Bakhuid, b’la tap da u lyoh;',
          'U briew ba pop ban peit ban i ia Me um lah;',
          'Ma Me bad tang Ma Me, Bakhuid ba dei iaroh,',
          'Ka bor, jingieit, jingkhuid, ha Me ki sah.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Bakhuid, Bakhuid, Bakhuid, bym ieng ha ka tip,',
          'Ka bor U Trai long shnong, ka long ka bor U Blei;',
          'Bakhuid, Bakhuid, Bakhuid, ngi shngeit baroh ruh,',
          'Ban long U Trai ba shisha, ka jingkyrkhu.',
        ],
      },
    ],
  },
  {
    id: 'song-004',
    title: 'Shano Mynsiem O.C.H. 222',
    metadata: {
      number: 4,
      language: 'khasi',
      composer: 'Lowel (L.M.) O.C.H. 222',
      syllables: '88.88',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Shano mynsiem, shano nga miet,',
          'Ka U Blei ka shong, ka shong,',
          'Ka la pynkhuid ia ka pyrthei,',
          'Bakhuid, Bakhuid, Ah Blei!',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Lai ngut ba tang Wei long, khaniew,',
          'Ka jingkyrkhu U Trai,',
          'Bakhuid, Bakhuid, Bakhuid, baroh,',
          'Pyrthei, bymkiew!',
        ],
      },
    ],
  },
  {
    id: 'song-005',
    title: 'Ka Jingkyrkhu Jong Me',
    metadata: {
      number: 5,
      language: 'khasi',
      composer: 'Sukhr (87.87.) Ambic N.W. 112',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ka jingkyrkhu jong Me ka da shngiat,',
          'Ka la nga ka shnong Me da baroh ruh,',
          'Ah Trai! ngi shngeit hi ia Me,',
          'Ban long ka bor U Blei.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka jingkyrkhu U Trai long ka tip,',
          'Tang ka bor U Blei ka shisha,',
          'Ka la nga ka shnong Me da baroh,',
          'Ban long ka bor U Blei.',
        ],
      },
    ],
  },
  {
    id: 'song-006',
    title: 'Ka Jinglarap U Trai',
    metadata: {
      number: 6,
      language: 'khasi',
      composer: 'Glanarch (86.86.) S.S. 88',
      syllables: '86.86',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Namar ingshaki U Trai,',
          'Ka jinglarap U Trai ka shon,',
          'Ka la ingsha be la khot,',
          'Ngi shakla ban larap.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka khyndiat larap U Trai,',
          'Ka larap ban larap Israel,',
          'Un shah ka Israel baroh,',
          'Un shah ka Israel.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Sha kyrdong jong U Kamon,',
          'Ka U Trai un shah bymkhuid,',
          'Ka U Trai un shah bymkhuid,',
          'Ka U Trai un shah.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'U Trai un shah bymkhuid,',
          'Ka jinglarap U Trai un shah,',
          'Ngi shakla ban larap U Trai,',
          'Ngi shakla ban larap.',
        ],
      },
    ],
  },
  {
    id: 'song-007',
    title: 'U Blei U Nongthaw',
    metadata: {
      number: 7,
      language: 'khasi',
      composer: 'Hursley (L.M.) C.H. 292',
      syllables: 'L.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'U Blei U Nongthaw ba da shngiat,',
          'To iaroh U Trai ka ma khiah,',
          'Bad nadu U Trai un shong ma U,',
          'Haba me U Blei un shong ma U.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Na ka long ka ma U Trai,',
          'Ka ba suid ban die U Blei,',
          'Ka ba suid ban die U Blei,',
          'Ka long ka ma U Trai.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ha ka long ka ma U Trai,',
          'U Trai un shong ka ma khiah,',
          'Ki suid ban die U Blei,',
          'Ki suid ban die U Blei.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ka long ka ma U Trai,',
          'U Blei un shong ka ma khiah,',
          'To iaroh U Trai ka ma U,',
          'To iaroh U Trai ka ma U.',
        ],
      },
    ],
  },
  {
    id: 'song-008',
    title: 'U Blei U Winchester',
    metadata: {
      number: 8,
      language: 'khasi',
      composer: 'Winchester (C.M.) S.S. 177',
      syllables: 'C.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ka la kaba la khraw sa paw,',
          'Ka jinglarap U Trai,',
          'Ka la kaba la khraw sa paw,',
          'Ka jinglarap U Trai.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Na ka long ka jong U Trai,',
          'Ka la kaba la khraw,',
          'Na ka long ka jong U Trai,',
          'Ka la kaba la khraw.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Sha khyndiat U Blei,',
          'Ka la kaba la khraw sa paw,',
          'Sha khyndiat U Blei,',
          'Ka la kaba la khraw.',
        ],
      },
    ],
  },
  {
    id: 'song-009',
    title: 'Lai Ngut Ba Khyndiat U Blei',
    metadata: {
      number: 9,
      language: 'khasi',
      composer: 'Harts, Glasgow (77.77.) Sukhr S.S. 320',
      syllables: '77.77',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ki bor ka jinglarap U Trai,',
          'Ki bor ka jinglarap U Trai,',
          'Ki bor ka jinglarap U Trai,',
          'Lai ngut ba khyndiat U Blei.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka la kaba la khraw sa paw,',
          'Ka la kaba la khraw sa paw,',
          'Ka la kaba la khraw sa paw,',
          'Ka jinglarap U Trai.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Na ka long ka jong U Trai,',
          'Na ka long ka jong U Trai,',
          'Na ka long ka jong U Trai,',
          'Ka la kaba la khraw.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ki bor ka jinglarap U Trai,',
          'Ki bor ka jinglarap U Trai,',
          'Ki bor ka jinglarap U Trai,',
          'Lai ngut ba khyndiat U Blei.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Ka la kaba la khraw sa paw,',
          'Ka la kaba la khraw sa paw,',
          'Ka la kaba la khraw sa paw,',
          'Ka jinglarap U Trai.',
        ],
      },
      {
        id: 'verse-6',
        order: 6,
        type: 'verse',
        lines: [
          'Na ka long ka jong U Trai,',
          'Na ka long ka jong U Trai,',
          'Na ka long ka jong U Trai,',
          'Ka la kaba la khraw.',
        ],
      },
    ],
  },
  {
    id: 'song-010',
    title: 'Ka Jinglarap U Trai',
    metadata: {
      number: 10,
      language: 'khasi',
      composer: 'Sukhr (C.M.) S.S. 329',
      syllables: 'C.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ai ba ngin iaroh ka jinglarap,',
          'Ngin iaroh ka da ka ma khiah,',
          'Ai ba ngin iaroh ka jinglarap,',
          'Ka jinglarap U Trai.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka la kaba la khraw sa paw,',
          'Ka la kaba la khraw sa paw,',
          'Ka la kaba la khraw sa paw,',
          'Ka jinglarap U Trai.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Na ka long ka jong U Trai,',
          'Na ka long ka jong U Trai,',
          'Na ka long ka jong U Trai,',
          'Ka la kaba la khraw.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ai ba ngin iaroh ka jinglarap,',
          'Ngin iaroh ka da ka ma khiah,',
          'Ai ba ngin iaroh ka jinglarap,',
          'Ka jinglarap U Trai.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Ka la kaba la khraw sa paw,',
          'Ka la kaba la khraw sa paw,',
          'Ka la kaba la khraw sa paw,',
          'Ka jinglarap U Trai.',
        ],
      },
      {
        id: 'verse-6',
        order: 6,
        type: 'verse',
        lines: [
          'Na ka long ka jong U Trai,',
          'Na ka long ka jong U Trai,',
          'Na ka long ka jong U Trai,',
          'Ka la kaba la khraw.',
        ],
      },
    ],
  },
  {
    id: 'song-011',
    title: 'U Blei Tu Nonglarap',
    metadata: {
      number: 11,
      language: 'khasi',
      composer: 'Warwick (C.M.) C.H. 358',
      syllables: 'C.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ngin iaroh ka da ka ma khiah,',
          'Ka jinglarap U Trai An swi,',
          'Ka jinglarap U Trai An swi,',
          'Ngin iaroh ka da ka ma khiah.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'To wat la buh ka jinglarap,',
          'Me Pop Me jinglarap U Trai,',
          'Me Pop Me jinglarap U Trai,',
          'To wat la buh ka jinglarap.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ka jinglarap U Trai An swi,',
          'Ka jinglarap U Trai An swi,',
          'Ka jinglarap U Trai An swi,',
          'Ngin iaroh ka da ka ma khiah.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Me Pop Me jinglarap U Trai,',
          'Me Pop Me jinglarap U Trai,',
          'Me Pop Me jinglarap U Trai,',
          'To wat la buh ka jinglarap.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Ka jinglarap U Trai An swi,',
          'Ka jinglarap U Trai An swi,',
          'Ka jinglarap U Trai An swi,',
          'Ngin iaroh ka da ka ma khiah.',
        ],
      },
    ],
  },
  {
    id: 'song-012',
    title: 'Ka Ba Khyndiat U Blei',
    metadata: {
      number: 12,
      language: 'khasi',
      composer: 'St. Anne (C.M.) S.S. 313',
      syllables: 'C.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ha ka long ka jong U Trai,',
          'Ngi ba khyndiat U Blei,',
          'Ha ka long ka jong U Trai,',
          'Ka ba khyndiat U Blei.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka jinglarap U Trai,',
          'Ka jinglarap U Trai,',
          'Ka jinglarap U Trai,',
          'Ka ba khyndiat U Blei.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ha ka long ka jong U Trai,',
          'Ngi ba khyndiat U Blei,',
          'Ha ka long ka jong U Trai,',
          'Ka ba khyndiat U Blei.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ka jinglarap U Tra依赖,',
          'Ka jinglarap U Trai,',
          'Ka jinglarap U Trai,',
          'Ka ba khyndiat U Blei.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Ha ka long ka jong U Trai,',
          'Ngi ba khyndiat U Blei,',
          'Ha ka long ka jong U Trai,',
          'Ka ba khyndiat U Blei.',
        ],
      },
      {
        id: 'verse-6',
        order: 6,
        type: 'verse',
        lines: [
          'Ka jinglarap U Trai,',
          'Ka jinglarap U Trai,',
          'Ka jinglarap U Trai,',
          'Ka ba khyndiat U Blei.',
        ],
      },
    ],
  },
  {
    id: 'song-011',
    title: 'U Blei U Nonglarap',
    metadata: {
      number: 11,
      language: 'khasi',
      composer: 'Warrington (L.M.)',
      syllables: 'L.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'To wat buhrieh, Ah Trai ba bha,',
          'Ia lade na u khñiang kat nga,',
          'Ba khia ka pop, jingpang nga shah,',
          'To wan ma Me, iarap ia nga.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Me ju pyndap byneng ba khraw,',
          'Sawdong pyrthei Me long ba paw;',
          'Pyni ka khmat isnei, Ko Pa,',
          'Tang kata lah pynshngaiñ ia nga.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ka khmat jong Me, ha pulit rieh,',
          'Bunsien mynshuwa la iohi;',
          'Nga sliang mynta bad nga swai,',
          'To kren sngewbha ha nga, Ah Trai.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ah ban iohi ka khmat jong Me,',
          'Ah ban ioh mad ka bor ba neh;',
          'Ka bor jingsuk, ka bor jingmap,',
          'Khlem ioh ia ki, nga duh, nga iap.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Te lano ka jingdum kan jah?',
          'Ki lyoh bym kyrmen kiba kah?',
          'Lano kan mih ka sngi ba bha,',
          'Ba pynshai na ka iing I Pa?',
        ],
      },
    ],
  },
  {
    id: 'song-012',
    title: 'Kaba Kyrmen Ha U Blei',
    metadata: {
      number: 12,
      language: 'khasi',
      author: 'J.C.E.',
      composer: 'St. Anne (C.M.)',
      syllables: 'C.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ah Blei ba ju iarap ia ngi,',
          'Ngi kyrmen ruh ha Me;',
          'Ha eriong bah long jakarieh,',
          'Bad jaka shong ba neh.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ha syrngiew jong ka khet jong Me,',
          'Riewkhuid ki la ju shong;',
          'Ka khlain ka ksangkti khraw jong Me,',
          'Ka jingiada ka long.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Mynba ki lum Mem pat shym sei,',
          'Pyrthei Mem pat pynlong;',
          'Na bymjukut Me ju long Blei,',
          'Bad junom Men iai long.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Shihajar snem ha khmat jong Me,',
          'Ki long kum shisngi hi;',
          'Kum jingapmiet ba khatduh eh,',
          'Ha bym pat mih ka sngi.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Ka por ba kum ka wah ba shlei,',
          'Ki khun ka kit noh hi;',
          'Ki her bla klet kum jingphohsniew,',
          'Ba jah tang mih ka sngi.',
        ],
      },
      {
        id: 'verse-6',
        order: 6,
        type: 'verse',
        lines: [
          'Ah Blei ba ju iarap ia ngi,',
          'Ngi kyrmen ruh ha Me;',
          'Ha shitom baroh long ka stieh,',
          'Long jaka shong ba neh.',
        ],
      },
    ],
  },
  {
    id: 'song-013',
    title: 'Ka Jingmap-Ei U Blei',
    metadata: {
      number: 13,
      language: 'khasi',
      author: 'J.J. & Ed.W.',
      composer: 'Huddersfield; Melita (88.88.88.)',
      syllables: '88.88.88',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ah Blei ba khraw, ba phylla eh,',
          'Ha baroh phar ba Me la leh;',
          'Te ia ki kam jong Me, Ah Blei,',
          'Kham phylla long ka jingaiei.',
          'Ma Me, ko Blei, tang marwei hi,',
          'Me ju map ei ki pop jong ngi.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Jingpalat jong ngi map, Ah Blei,',
          'Ngi rem ngi swai, to pynim ei;',
          'Nalor jong Me, ym don ba lah,',
          'Ia ngi ba pop, ban map ban shna.',
          'Ma Me, ko Blei, tang marwei hi,',
          'Me ju map ei ki pop jong ngi.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ai ba ki soh ka jingaiei,',
          'Ki kam ba bha jingieit U Blei,',
          'Kin nang pynkhraw ka nam jong U,',
          'Ha pyrthei bah ha byneng ruh.',
          'Ma Me, ko Blei, tang marwei hi,',
          'Me ju map ei ki pop jong ngi.',
        ],
      },
    ],
  },
  {
    id: 'song-014',
    title: 'Ka Jingthmu U Blei',
    metadata: {
      number: 14,
      language: 'khasi',
      composer: 'Navarre (10.10.10.10.)',
      syllables: '10.10.10.10',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Pyrthei, byneng, ia kine ym pat thaw,',
          'Ka sngi, u bnai, ki khlur ruh ym pat paw;',
          'Myn ha ka jingiasyllok Uwei-Lai,',
          'Iakut bun im u briew ba rem, ba swai.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Hu Jisu Khrist la kynshew jingaiei,',
          'Bym lah ban thew, ba khraw ka jingisnei;',
          'La jyntia lut ka pyrthei kylleng bah,',
          'Ba tuid ki um jingthymu ieit I Pa.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'La pynbna mynta ka jinglaitim ia ngi,',
          'Ka snam U Khun la mih ha Kalbari;',
          'To iaroh jam, ka ktien pynkylluid war,',
          'IU diengphyna, ka snam ba pyllait phar.',
        ],
      },
    ],
  },
  {
    id: 'song-015',
    title: 'Ka Jutang U Blei',
    metadata: {
      number: 15,
      language: 'khasi',
      composer: 'Holley (10.10.10.10.)',
      syllables: '10.10.10.10',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Jutang jingsuk, jutang ba skhem U Blei,',
          'Bym kynriah noh, la kad nongrim pyrthei;',
          'Jutang ba shisha, bym lah kylla shuh,',
          'La jur ka pop, ka jingim ngim ju duh.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Jutang aiei, bla thaw da Uwei-Lai,',
          'Ka spah ia ngi, ka skhem ka ktien jingsmai;',
          'Ka long ba lah ban kyntiew lin ia ngi,',
          'Ka bor jong ka, ka bor jong U Blei hi.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Jutang ba dap, ba ai jinghun iU Blei,',
          'Shuwa ba thaw ki lum bah ka pyrthei;',
          'Ka jor jong ka, bun byllien kan pyllait.',
          'Ka snam U Khun ka ram jong ki ka sait.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Jutang donbor, bym lah pyntor ia ka,',
          'Pyrthei, jingiap, kim lah pynduh ia ka,',
          'Ka dang neh skhem jingthymu slem U Blei,',
          'Kam khih kum kiba tlot ki jong pyrthei.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'La hap sha pop, la ngop ki khun U Blei,',
          'Jutang dang don, ia ki ban ioh isnei;',
          'Ban sait ia ki, jingpalat ruh pynduh,',
          'Ban pynmihpat na jingtep khlem pop shuh.',
        ],
      },
    ],
  },
  {
    id: 'song-016',
    title: 'Ka Jaka Rieh Ha U Blei',
    metadata: {
      number: 16,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Nashville (888. D.)',
      syllables: '888. D.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'U Blei ka bor bad jakarieh,',
          'Ha khim bad ha jingshipa hi,',
          'Haba ngi kyrpad, U la jan;',
          'Ki lum sha duriaw ai kin hap,',
          'Kan pra pyrthei bad ka jingdap,',
          'Ha nga jingtieng mynsiem kam wan.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ki duriaw halor ka pyrthei,',
          'Kin jyntia lut da ka jingshlei,',
          'Kin ngop ki lum kum mynbarim;',
          'Ka wah ba sngur ka tuid kyrhai,',
          'Sha nongbah U Blei khlem da wai,',
          'Ki khun U Blei junom kin im.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'U Blei U don bad ki, ban da,',
          'Ia kiba tlot U kyrshan bha,',
          'Jingiarap lypa U la khreh,',
          'Ki jingbanbein to ai kin wan,',
          'Jingshitom mynsiem ai kin ban,',
          'Ka bor U Blei sha ki la theh.',
        ],
      },
    ],
  },
  {
    id: 'song-017',
    title: 'Ka Spah Ha U Blei',
    metadata: {
      number: 17,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Waterstock (S.S. 490.)',
      syllables: 'S.S. 490',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ka spah ba ngi la ioh,',
          'Kat ka ban shem ym lah;',
          'Ka jingioh suk ba ei,',
          'Ha ri seisoh I Pa.',
          'Ym don ba lah ia nga te shuh,',
          'Na U pynkhlad da lei lei ruh.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka jerong bym lah khein,',
          'Ka jylliew bym lah ong;',
          'Ka jingim kaba kor,',
          'Ka dor bym lah pynshong,',
          'Phi lah ban ong phi Seraph khuid,',
          'Ka dor ka spah sha ngi bla tuid?',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ka jingpah ka pyrthei,',
          'Te baroh phar ka duh;',
          'Jingpynshoi kiba jur,',
          'Ki dam, kim donbor shuh;',
          'Ka duh ka rong ki tiew pyrthei,',
          'Nga shem itynnad tang U Blei.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ka sngi, ki khlur, byneng,',
          'Ki hap ki noh arsut,',
          'Ka jingdum tliw ka tap,',
          'Ka jingsngewbha la lut;',
          'Itynnad eh tang U Blei hi,',
          'Bad tang na U ka suk ka mih.',
        ],
      },
    ],
  },
  {
    id: 'song-018',
    title: 'Uwei-Lai Bakhuid',
    metadata: {
      number: 18,
      language: 'khasi',
      author: 'H.L.',
      composer: 'Sanctus (87.87. D.)',
      syllables: '87.87. D.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Sawdong ka burom jong U Trai,',
          'Kherub bad Seraph ki ieng;',
          'Ki jingiaroh ba ki iarwai,',
          'Ki pynsawa ia ki bneng.',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          'Ka bneng bad ka khyndew ka shlei,',
          'Da ka burom jong U Trai,',
          'Sha Me ban ai burom ka dei,',
          'Bakhuid Bakhuid Bakhuid, Trai.',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          'Ka la khynwin ka bneng hajrong,',
          'Pyrthei ruh ka iaroh jam;',
          '“Bakhuid, Bakhuid, Bakhuid,” ka ong,',
          'Trai ki paid, ba ha khlieh tam.',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          'Lem bad Seraph baroh ha bneng,',
          'Lem bad ka Balang hangne,',
          'Ia U ngin mane dem kylleng,',
          'Ia U ngin rwai iaroh de.',
        ],
      },
    ],
  },
  {
    id: 'song-019',
    title: 'Ka Jakarieh U Khristan (Salm xlvi)',
    metadata: {
      number: 19,
      language: 'khasi',
      composer: 'St. Trond (87.87.) (Iambic)',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'To wan ma phi, to khymih de,',
          'Ki jingleh U Trai jong ngi;',
          'Kumno pynduh, kumno pynmih,',
          'Ki hima jong ka pyrthei.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka jingiapom Un sa pynduh,',
          'Na mihngi haduh sepngi;',
          'Ka ryntieh, jingsum, bad u khnam,',
          'Un pynduh U Trai jong ngi.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Sngap jar, to tip ba nga long Blei,',
          'Uba ka dei ban iaroh;',
          'Ki Jentil kin pynkhraw ia Nga,',
          'Ka pyrthei bah ruh baroh.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'U Trai da lade long bad ngi,',
          'U Trai ki paidbah angel;',
          'Ka bor bad jakarieh U long,',
          'U Blei U jong ki Israel.',
        ],
      },
    ],
  },
  {
    id: 'song-020',
    title: 'Ka Jingshlur Ha U Blei',
    metadata: {
      number: 20,
      language: 'khasi',
      composer: 'Mary (87.87.) (Iambic)',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'U Trai U long jingshai jong nga,',
          'Jingkhiah, ngan tieng iano?',
          'U Trai U long ka bor jingim,',
          'Pynkhim ia nga lah mano?',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Nga shaniah lut ha Me U Blei,',
          'Ngan lehraiñ lei ban ialap?',
          'Ah Blei, da la ka hok pynim,',
          'Ban im mynsiem to iarap.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Haneng ka jaka jong Me toi,',
          'Me kloi la shkor ban pynshah;',
          'Ia nga ban pynim long mawsiang,',
          'Ka synrang kaba shisha.',
        ],
      },
    ],
  },
  {
    id: 'song-021',
    title: 'Salm Cxxxix',
    metadata: {
      number: 21,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Oldenburgh (87.87.) (Iambic)',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Iu bymman, Trai Me pyniap duh,',
          'Mem ju riej shuh kum kita;',
          'To kynriah phi ki riew bitsnam,',
          'Ioh ngam lem nga ruh hangta.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ki kren ‘tien sniew pyrshah ia Me,',
          'Ba meh jingbitar hapoh;',
          'Ki kynnoh bein ka nam jong Me,',
          '‘Riewsniew kim treh ban iaroh.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ki nongshun jong Me, Trai, nga shun,',
          'Bad ki, kam hun ka mynsiem;',
          'Kat kiba ieng ialeh ia Me,',
          'Kim neh, kan ngat ka jingtim.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'To iit ia nga, Ah Blei, ithuh,',
          'To tynjuh dohnud jong nga;',
          'To tip ki jingmut tynrai hi,',
          'Ioh ka dang sap jingbakla.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Shapoh jong nga to khymih thuh,',
          'Ioh nga dang buh jingbymman;',
          'Ha lynti bymjukut to lam,',
          'Nga iam ha Me, to kyrshan.',
        ],
      },
    ],
  },
  {
    id: 'song-022',
    title: 'Ka Salm Xxvii',
    metadata: {
      number: 22,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Oldenburgh (87.87.)',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'U Trai ka jingshai nga U long,',
          'U Nongpynim ia baroh;',
          'Ka bor jingim hangne U ai,',
          'Trai, ngan sheptieng iano?',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'La shet, la sylla, byllien bah,',
          'Kam ma ka mynsiem jong nga;',
          'La mih kynhun nongshun ban thap,',
          'Kam duh jingshlur ‘riew shisha‘.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Tang kane kawei ngan iai pan,',
          'Ban wan ia im shi-ryta;',
          'Ha iing U Trai, ban i bU shong,',
          'BU long itynnad hangta.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ha ka sngi jynjar Un sa mih,',
          'Ban rieh ha iing sngewtyngen;',
          'Ha u mawbah Un kyntiew bha,',
          'Um shah ban duh jingkyrmen.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'To sngew, Ah Trai, lu khun ba kyang,',
          'To nang iashah, isynei;',
          'Me ong ma Me, “To wad ia nga,”',
          'Kumta nga wad, Ah U Blei.',
        ],
      },
    ],
  },
  {
    id: 'song-023',
    title: 'Ka Jakarieh U Khristan (Salm xlvi)',
    metadata: {
      number: 23,
      language: 'khasi',
      composer: 'Dymuniad (87.87.) (Iambic)',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'U Blei U long ka jakarieh,',
          'Ka bor ia ngi ban kyrshan;',
          'Ha ki jingkhuslai katba lap,',
          'U nongiarap ba hajan.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Te namarkata ngin ym tieng,',
          'La don jingjynjar ba khraw;',
          'La khih pyrthei la noh ki lum,',
          'Ha pydeng ki um duriaw.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'La ki um jong ka ki kyrhuh,',
          'Ki lum ruh ki ishyrkhei;',
          'Ka don ka wah, ki um jong ka,',
          'Ki pynkmen ka shnong U Blei.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'U Blei ha pdeng jong ka U long,',
          'U shong, kan ym khih; hynrei,',
          'U Blei Un kyrshan dang step hi,',
          'Un pyni la jingisnei.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'La dom nongmane ki bleithaw,',
          'La ki bakhraw ki bitar;',
          'U Trai u kren ki briew ki sngap,',
          'Ka pyrthei ka jar jar.',
        ],
      },
    ],
  },
  {
    id: 'song-024',
    title: 'Ka Jingiada U Blei Ia La Ki Briew (Salm xlvi)',
    metadata: {
      number: 24,
      language: 'khasi',
      composer: 'Ely (87.81) (Iambic)',
      syllables: '87.81',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'U Blei U long ka jakarieh,',
          'Ka bor ia ngi ban kyrshan;',
          'Ha ki jingkhuslai baroh phar,',
          'U Nongiarap ba hajan.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'La khih pyrthei ngin tieng ruh lei?',
          'U Blei sha khlieh ka jynjar;',
          'La noh ki lum sha duriaw bah,',
          'U lah ma U ban synshar.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'La at la kyrhuh lang ka um,',
          'La win ki lum na kata;',
          'Ka wah ka tuid sha shnong U Blei,',
          'Sngew shngain ha Seion shisha.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ha iing ba khuid U Trai U shong,',
          'U long ma U ban kyrshan;',
          'U kloi ban wan iarap, ban ri,',
          'Kam khih, la ban u bymman.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'La win ki hima kylleng ruh,',
          'La bitar ki riewthala,',
          'Te tang shu lap ba kren U Trai,',
          'La wai jingsniew riewsylla.',
        ],
      },
      {
        id: 'verse-6',
        order: 6,
        type: 'verse',
        lines: [
          'U Trai ki paidbah U ialam,',
          'Ka lah ka waitlam jong ngi;',
          'Ai kin iakyntur ki nongpop,',
          'Ngin jop ruh ha la ka sngi.',
        ],
      },
    ],
  },
  {
    id: 'song-025',
    title: 'Ka Jingkhraw Ka Jingisynei (Salm xxxvi)',
    metadata: {
      number: 25,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Morganwg (87.87.)',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Katno ba kor ki jingisnei,',
          'U Blei U bymjukylla;',
          'Te namarkata ngi ki briew,',
          'Ha syrngiew Me ngi shaniah.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ha iing jong Me don bam kyrhai,',
          'Ban ai ha kiba thyngan;',
          'Na wah jong Me kin dih sngewbha,',
          'Na ka kin ioh jingkyrshan.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Me long ma Me ka tynrai hi,',
          'Na Me ka mih ka jingim;',
          'Ha jingshai khymat jong Me, Trai,',
          'Ka shai kydar ka mynsiem.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Jingisnei jong Me Trai, wat khang,',
          'Na kiba thrang ka mynsiem;',
          'Nang ai sngewbha ka hok jong Me,',
          'Ia kiba beh ka jingim.',
        ],
      },
    ],
  },
];
