 import { SongT } from '~/src/types/song';

export const shaphangKaKtienUBlei: SongT[] = [
  {
    id: 'song-129',
    title: 'Ka Jingiaid Ha Ki Hukum',
    metadata: {
      number: 129,
      language: 'khasi',
      author: 'Unknown',
      composer: 'Sabbath (87.87)',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Suk u briew uba khuid ka lad,`,
          `Ba wad ki hukum janai,`,
          `Ba shida hi la ka jingïaid,`,
          `Ba shait ban bat ki tynrai.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Kumno, Ah Trai, u samla'n bat,`,
          `Un sumar khuid la jingleit?`,
          `Da kaba sumar pyrkhing eh,`,
          `Ban leh khlem shah ban kyrbeit.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Sngewtynnad eh, Ah Trai, ha nga,`,
          `Ban phla ka ktien ka jutang:`,
          `Ha kane hi ngan ïai buh lut,`,
          `Ka jingmut bad jingshemphang.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Ka sharak, lynti ban ïalam,`,
          `Ban jam, ngan ïoh ka jingshai;`,
          `Nga smai ba ngan ym kylla shuh,`,
          `Ngam lyndet ruh ki tynrai.`,
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          `Nang kyrshan, Ah nang kyrshan, Trai,`,
          `Ngan phai ban ïoh khiah junom;`,
          `Bad ha ki hukum ngan sa shem,`,
          `Ka jingskhem bad ka burom.`,
        ],
      },
    ],
  },
  {
    id: 'song-130',
    title: 'Ki Ktien U Blei',
    metadata: {
      number: 130,
      language: 'khasi',
      author: 'Unknown',
      composer: 'St. Mabyn (87.87)',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ki ktien b'la kyrkhu jong U Trai,`,
          `Jingshai ban shngaiñ u bynriew;`,
          `Na jingdum tliw ba nga la ngam,`,
          `Kin lam sh'U Blei, kin kyntiew.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Da sngap ki mynsiem baroh phar,`,
          `Ba ïar ki ktien jingkyrmen;`,
          `Ki long ka jingim ï'u nongpop,`,
          `L'u ngop ha rem, la tyngen.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Ki jingpynpaw U Blei na neng,`,
          `Ha ki U ïeng U Kynrad;`,
          `Ban ai jinghun ha ka pyrthei,`,
          `Khlem pud U trei U pyrkhat.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Ïa ngin ïakyntiew la ka ktien,`,
          `Ïariwai hin ha lynti;`,
          `Ka lad ka jingpynim la paw,`,
          `Ban law ïa ngi na byndi.`,
        ],
      },
    ],
  },
  {
    id: 'song-131',
    title: 'Ka Jingskhem Ka Ktien',
    metadata: {
      number: 131,
      language: 'khasi',
      author: 'Unknown',
      composer: 'Brooklyn (C.M)',
      syllables: 'C.M',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ka jingshai bad ka bor ba khraw,`,
          `Ka long ka Ktien U Blei;`,
          `Shikynnoh em, kam lah ban duh,`,
          `Da shisha kan sah skhem.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Ka Ktien ba thiang kum ka ngap,`,
          `Ba dap da jinggaiei;`,
          `Ka ïai pynpaw ki jor ba bha,`,
          `Ka jinglong khuid U Blei.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Ki kular jong U kum ka sngi,`,
          `Da lei lei kim lah khih;`,
          `Shikynnoh em kan ym lah jah,`,
          `Ka Ktien U Blei jong ngi.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Ki kular jong U ba la shon,`,
          `Ki um ba kyrsoi sngur;`,
          `B'la pun ka lynti phyrnai eh,`,
          `Shaneng sha khlieh ki khlur.`,
        ],
      },
    ],
  },
  {
    id: 'song-132',
    title: 'Ka Jingitynnad Ka Gospel',
    metadata: {
      number: 132,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Elliot (98.98.D)',
      syllables: '98.98.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ki sngur ki wah U Blei, ha khymih,`,
          `Ki tuid ba ki pilgrim kin suk;`,
          `Ki madan iwbih bad ba jyrngam,`,
          `Ki sei ki soh bang ban pynsuk!.`,
          `Tang mad ki soh shngiam bad sla de,`,
          `Na kine ki dieng kiba mih,`,
          `Men die noh ki mar pyrthei baroh,`,
          `Ban thied te ïa kane ka bri.`,
        ],
      },
    ],
  },
  {
    id: 'song-133',
    title: 'Ka Baibl',
    metadata: {
      number: 133,
      language: 'khasi',
      author: 'Unknown',
      composer: 'Ewing (76.76.D)',
      syllables: '76.76.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ki jingmut ki jong U Blei,`,
          `Ha Baibl ki la paw,`,
          `Kiba long ïaineh junom,`,
          `Jingshisha kaba khraw;`,
          `Jingkular don ba shisha,`,
          `Ba la pynskhem da snam,`,
          `Kham kor de ïa ka ksiar,`,
          `Bad paila kordor tam.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Ka phla ha bynriew baroh,`,
          `Kaba long shisha hi,`,
          `Ba U Blei ha ka burom,`,
          `U thaw ï'u kpa jong ki;`,
          `Ka jinglong suk ba nyngkong,`,
          `U briew u pynduh hi;`,
          `Na kata mih jingsngewsih,`,
          `Jingrem ka jait jong ngi.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Ngi shem ruh ha ka Baibl,`,
          `Ka ktien ba sawa jam,`,
          `Ba don ka jingim janai,`,
          `Ïa uba tyngit tam;`,
          `Jingpynïasuk la pyndep,`,
          `Ha jingïap jong U Khun;`,
          `U Blei, namar U Jisu,`,
          `U pydiang ki nongshun.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Ka Baibl kaba kynthup,`,
          `Ki hukum jong U Blei;`,
          `Jingsneng jong ka kham kordor,`,
          `Ïa baroh ka pyrthei,`,
          `Ha kane don bun hajar,`,
          `Atiar kiba nep;`,
          `Khlem pud ïa ka ngan pule,`,
          `Ngan pyrkhat khlem da pep.`,
        ],
      },
    ],
  },
  {
    id: 'song-134',
    title: 'Ka Jingiaroh Ia Ka Ktien U Blei',
    metadata: {
      number: 134,
      language: 'khasi',
      author: 'Unknown',
      composer: 'Unknown',
      syllables: '83.83.88.83',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ba ngi la ïoh ka Ktien U Blei,`,
          `Ngin ïaroh;`,
          `Ka long ka ktien sngewbha aiei,`,
          `Ngin ïaroh,`,
          `Kum ka sngi ba pynshai sngur bha,`,
          `Pynjem ka lynti khlaw ka lah;`,
          `Ba ngi la ïoh ka jingshisha,`,
          `Ngin ïaroh.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Kham thiang hi ia ka rewngap,`,
          `Ngin ïaroh;`,
          `Ngin ïoh ka jingsngewbha ba dap,`,
          `Ngin ïaroh.`,
          `Ïa baroh lang kham kor shsha,`,
          `Ïa ksiar bad ïa ki paila;`,
          `Ka Ktien U Blei long la ka spah,`,
          `Ngin ïaroh.`,
        ],
      },
    ],
  },
  {
    id: 'song-135',
    title: 'Ka Jingkren U Jisu',
    metadata: {
      number: 135,
      language: 'khasi',
      author: 'H.R.',
      composer: 'Noah Williams (87.87.D)',
      syllables: '87.87.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ah to kren ba jemnud Jisu,`,
          `Ki Ktien jong Me long umsoh,`,
          `Kiba lah pynmih ka jingsuk,`,
          `Kaba dap da jor baroh.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Ka jingsawa ka jingpynlong,`,
          `Ki jingpynshoi doh bad pop;`,
          `Ha jingsawa sngewbha jong Me,`,
          `Ki jam jai jai, ki duh khop.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Kiei kiei ba itynnad,`,
          `Kiba bang ruh jong pyrthei;`,
          `Ym lah nujor bad jingsawa,`,
          `Ki ktien sngur ka jingmap ei.`,
        ],
      },
      {
        id: 'chorus-2',
        order: 4,
        type: 'chorus',
        lines: [
          `Ai ngin sngew jingsawa jong Me,`,
          `Ka jingsawa ba donbor;`,
          `Hapoh jong nga, ha ka dohnud,`,
          `Pynmih jingsuk kaba kor.`,
        ],
      },
      {
        id: 'verse-3',
        order: 5,
        type: 'verse',
        lines: [
          `Ong ha nga ba Me long jong nga,`,
          `Ong da ka ktien kaba shai;`,
          `To pynduh ka jingartatien,`,
          `Kren ha nga, to kren, Ah Trai!`,
        ],
      },
      {
        id: 'chorus-3',
        order: 6,
        type: 'chorus',
        lines: [
          `Ai ngan ïohsngew kawei ka ktien,`,
          `Kaba mih na byneng hi;`,
          `Ki jingsheptieng kin jah junom,`,
          `Jingsuk bymjukut kan mih.`,
        ],
      },
    ],
  },
  {
    id: 'song-136',
    title: 'Ka Jingthiang Ka Ktien U Blei',
    metadata: {
      number: 136,
      language: 'khasi',
      author: 'Unknown',
      composer: 'Neander (87.87.87)',
      syllables: '87.87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ka Ktien jong Me kaba kordor,`,
          `Kum ka ksiar b'la pynphrang;`,
          `Ka Ktien jong Me ka itynnad,`,
          `Ka Ktien jong Me kaba bang,`,
          `Kaba dap da rewngap,`,
          `Dohnud jong nga ka pyndap.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Kan ïalam ka Ktien ka jong Me,`,
          `Lyngba ka ri khlaw bymnud;`,
          `Kane long ‘u Iyoh’ ba tyngshaiñ,`,
          `Ba ki Israel kin nang bud,`,
          `Kaba kor, dap da jor,`,
          `Ban ïalam ruh ba donbor.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Haba kynmaw kito ki sngi,`,
          `Ba nga shem sngewbha ba bun;`,
          `Ka jingsawa ka Ktien jong Me,`,
          `Dohnud jong nga ka pynhun;`,
          `Suk ma ki, ba ïohi,`,
          `Khymat jong Me, byneng hi.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Ah! ban sngew ka Ktien ka jong Me,`,
          `Ba kren pasiaw bad ba shon:`,
          `Ïoh ngan ïaid wir khlem jingpyrkhat,`,
          `Sha kadiang sha kamon.`,
          `Nang bytin da ka Ktien,`,
          `Ngan ïaid beit, khlem kylla dien.`,
        ],
      },
    ],
  },
  {
    id: 'song-137',
    title: 'Ka Bor Ka Ktien U Trai',
    metadata: {
      number: 137,
      language: 'khasi',
      author: 'Unknown',
      composer: 'Rheidol (87.87.87)',
      syllables: '87.87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Phah, Ah Trai ïa la jingsawa,`,
          `Mynta da ka bor ba khraw;`,
          `Ban ïaleh ïa ka Ktien jong Me,`,
          `Shah, b'u briew um lah, kan paw;`,
          `‘Ïaid kylleng, ding byneng’,`,
          `Thang ka bymman bad jingmeng.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Ka Ktien jong Me ka la biang,`,
          `Ban ïalam sha kut ka khlaw;`,
          `Long ‘ka jingshai’ long ‘u lyoh’,`,
          `Ban ithuh ba Me da paw;`,
          `Ktien ba neh, long ha Me,`,
          `Kum ha kane ai ngin leh.`,
        ],
      },
    ],
  },
  {
    id: 'song-138',
    title: 'Ka Ktien U Blei',
    metadata: {
      number: 138,
      language: 'khasi',
      author: 'J.C.E.',
      composer: 'Grafenberg (76.76.D)',
      syllables: '76.76.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ban wad ïa ka ktien jong Me,`,
          `Ah Trai, ïarap ïa nga;`,
          `Ha ban da shem ï'U Jisu,`,
          `U Nongpynim ba bha.`,
          `U long U Blei ba donbor,`,
          `Ban shna ïa ki jingpang;`,
          `La khraw ka pop ka jong nga,`,
          `Ban pynduh khoit U nang.`,
        ],
      },
    ],
  },
  {
    id: 'song-139',
    title: 'Ka Burom Ka Ktien U Blei',
    metadata: {
      number: 139,
      language: 'khasi',
      author: 'Unknown',
      composer: 'Bethel (98.98.D)',
      syllables: '98.98.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ah peit ki ‘mat jong nga ban ïohi,`,
          `Ka burom ka ktien jong Me phar;`,
          `Kham myntoi ïa nga ban shem kane,`,
          `Ïa kaba ïoh rupa bad ksiar.`,
          `Ka pyrthei kan ing bad ki paila,`,
          `Ka Ktien U Blei jong nga kan neh;`,
          `Ka jingim bymjukut long ithuh,`,
          `Ï'U Jisu, U Briew bad U Blei.`,
        ],
      },
    ],
  },
  {
    id: 'song-140',
    title: 'Ka Baibl',
    metadata: {
      number: 140,
      language: 'khasi',
      author: 'C.M.S.',
      composer: 'Unknown',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Baibl ba nga ieit,`,
          `Ka long ka Ktien U Blei;`,
          `Ka ïalap ï'U Jisu,`,
          `Nongpynim ka pyrthei.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Ka Baibl, ka Baibl,`,
          `Ka Baibl, ba nga ieit;`,
          `Ka Baibl, ka Baibl,`,
          `Ka long ka Ktien U Blei.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Shem ruh ha ka Baibl,`,
          `Ka jingieit bah U Blei;`,
          `Ba ï'U Khun U aiti,`,
          `Ïa ngi ban pynim ei.`,
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          `Baibl ba nga ieit,`,
          `Ngan kohnguh tang ïa ka;`,
          `Kan sa long ka sharak,`,
          `Ban ïalam beit ia nga.`,
        ],
      },
    ],
  },
  {
    id: 'song-141',
    title: 'Bet Iu Symbai Babha',
    metadata: {
      number: 141,
      language: 'khasi',
      author: 'D.S.Y.',
      composer: 'S.S. 1080',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Bet ï'u symbai babha,`,
          `Bet mynstep, mynsngi bad mynmiet;`,
          `Bet ï'u symbai babha,`,
          `Ka Ktien jong U Blei:`,
          `Bet ï'u symbai babha,`,
          `Ha ki khyndew kiba seisoh;`,
          `Bet ï'u symbai babha,`,
          `Ka Ktien jong U Blei.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Bet ï'u symbai babha,`,
          `Bet ï'u symbai babha,`,
          `Bet ï'u symbai da jingïaishah bad`,
          `jingjemnud;`,
          `Pynbna khubor Gospel`,
          `Bad jingmap ei halor diengphna,`,
          `Bet ï'u symbai babha,`,
          `Ka Ktien jong U Blei.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Bet ï'u symbai babha`,
          `Ha ki jait bynriew ka pyrthei;`,
          `Bet ï'u symbai babha,`,
          `Ka Ktien jong U Blei:`,
          `Bet ï'u symbai ka ktien,`,
          `Khlem jingthohbria ha la jingim,`,
          `Bet ï'u symbai map ei,`,
          `Ka Ktien jong U Blei.`,
        ],
      },
    ],
  },
];