import { SongT } from '~/src/types/song';

export const shaphangKaKamUBlei: SongT[] = [
  {
    id: 'song-221',
    title: 'Ki shipai U Syiem Bneng',
    metadata: {
      number: 221,
      language: 'khasi',
      author: 'J. R.',
      syllables: '66.66.88',
      songId: 'song-221',
      tune: 'BEVERLY',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'U Syiem byneng shaphrang,',
          'Ngi ruh, ngi baroh shlur;',
          'Ka um ka ding kam khang,',
          'Haba ngi nang ïatur;',
          'Ngin tur, ngin tur, ïariwai jam,',
          'Ngin jop, ngin jop, U Syiem Un lam.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ym don uwei ba swai,',
          'Na shipai Syiem byneng;',
          'Ki pydiang de khlem wai,',
          'Ka bor jong U na neng;',
          'Ngin ïoh, ngin ïoh ka waiñ ba sngur,',
          'Kaba sngewbang, kaba pynshlur.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Sydang ban riwai shuh,',
          'U Paidbah ba ïaseng;',
          'Їaroh jingïap jong U-',
          'U Khun U Syiem byneng;',
          'La ïoh la ïoh ki jingkyrkhu,',
          'Ki angel kim ïoh mad ki juh.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Phi Seraph to ïadem,',
          'Ban khymih to wan kloi;',
          'Ki nongpop kiba rem,',
          'Ha byneng ki la poi;',
          'Їohi ma ki ka ri sngewbha,',
          'Ki kynroh ruh ka ïing I Pa.',
        ],
      },
    ],
  },
  {
    id: 'song-222',
    title: 'Ka Jingduwai Ban PynroiÏa Ka Kam',
    metadata: {
      number: 222,
      language: 'khasi',
      composer: 'Boston',
      syllables: 'L.M',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ah Blei Bakhraw, pynbha ka kam,`,
          `Sha kaba kut pyrthei ïalam;`,
          `To tyngshaiñ noh sha lum, sha thor,`,
          `Da nang pyni ïa la ka bor.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Ka Babilon ka khynñiuh, te,`,
          `Kan kyllon ruh ba don ma Me;`,
          `To khymih shen to kad byneng,`,
          `Ka Seïon kan long khlieh kylleng.`,
        ],
      },
    ],
  },
  {
    id: 'song-223',
    title: 'Ka Jingroi Ka Gospel',
    metadata: {
      number: 223,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Ellacombe (S.S.649.)',
      syllables: 'D.C.M',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Kan ïaid ka Gospel Blei shaphrang,`,
          `Sha kylleng ka pyrthei;`,
          `Ban roi, ban roi ha ka Balang,`,
          `Mynsiem to ai ban tei;`,
          `Kin mih bun hajar b'la pyllait,`,
          `Na jingdum tliw ban im;`,
          `Na India ngi kin wan riewshait,`,
          `Ban ïaroh Nongpynim.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Ka jingput rupa Jubili,`,
          `Kan sawa ha ri khlaw;`,
          `To wan u paidbah dang step hi,`,
          `Wad Jingpynim ba khraw;`,
          `Ka ïing ba kyntang, Trai nang tei,`,
          `Pyndep ka ktien jingthoh;`,
          `Te katba sah nongrim pyrthei,`,
          `Ngin sei ka jingïaroh.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Jingduwai ki riewkhuid kin kiew,`,
          `Kum jingainguh ba im;`,
          `Jingïaroh seïon ai kin kiew,`,
          `Jingkyrsoi U Mynsiem;`,
          `Sa khyndiat hi ïa kane'n shem;`,
          `Itynnad kum ka sngi;`,
          `Kin ïaroh jam ha ki jingtem,`,
          `Ka jingjop Kalbari.`,
        ],
      },
    ],
  },
  {
    id: 'song-224',
    title: 'Ka Jingjop U Khrist',
    metadata: {
      number: 224,
      language: 'khasi',
      composer: 'Llandegla',
      syllables: '66.46.88.76',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ka jingput Jubili,`,
          `Ha jingïap Kalbari;`,
          `Ka sawa jam,`,
          `Jingpynim ei ïa ngi;`,
          `To leh sngewbha mynsiem ba swai,`,
          `Jisu la jop ka sngi ba lai;`,
          `Kin mih ki koidi jingïap,`,
          `Na ki jingkhum kin lait.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `U Pharo la u shun,`,
          `Um lah pynsniew ki khun;`,
          `Ba kiew shaneng,`,
          `Sha ïing I Pa ba hun;`,
          `Jingjynjar ma ka ri khlaw bah,`,
          `Ia ki riewngeit pynsniew kam lah;`,
          `Ba rieh ha ki thapniang,`,
          `L'U Kapten uba bha.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `U Syiem jingsuk la jop,`,
          `Pyrthei jingtep bad pop;`,
          `Ka Seïon ruh,`,
          `Da bor jong U kan jop;`,
          `Te mynta baroh risa shait,`,
          `Na ïing jingdum to mih sha lait;`,
          `Ka bynta skhem ka jong phi,`,
          `U Jisu Trai ki paid.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Don paidbah byllien bah,`,
          `Ha pyrthei ki ju sah;`,
          `Ha pang bad pop,`,
          `Ha shitom bad jingma;`,
          `Ha jingsuk jai bad ha jinghun,`,
          `Ki shong ha trai ka khet U Khun;`,
          `Ki Jingïaleh la wai noh,`,
          `Bym don shuh ki nongshun.`,
        ],
      },
    ],
  },
  {
    id: 'song-225',
    title: 'Ka Jingwan ka Gospel',
    metadata: {
      number: 225,
      language: 'khasi',
      author: 'S. S.',
      syllables: '66.66.88',
      songId: 'song-225',
      tune: 'ALUN',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ka Gospel Blei la wan,',
          'Na jyngai bah sha ngi;',
          'To sngap, ha ngi ka kren,',
          'Ka ïaid kylleng ka ri;',
          'To ïeng, to ïeng ban sngew ïa ka,',
          'Ka jingpynim men ïoh sngewbha.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka Gospel Blei la wan,',
          'Ngi wad ïa ka la slem;',
          'Sharum, shaneng, ngi ïaid,',
          "Ia l'U Nongthaw ban shem;",
          'To ïeng, to ïeng, ban sngew ïa ka,',
          'Ka ktien U Nongpynim ba bha.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ka Gospel Blei la wan,',
          'To pydiang ei ïa ka;',
          'Kan pyni lynti beit,',
          'Ban poi sha ïing I Pa;',
          "Ka tyrwa ruh ï'U Nongïalam,",
          'U Jisu Khrist, ban ïaid shaphrang.',
        ],
      },
    ],
  },
  {
    id: 'song-226',
    title: 'Ka Lama ka Gospel',
    metadata: {
      number: 226,
      language: 'khasi',
      syllables: '66.66.88',
      songId: 'song-226',
      tune: 'DEWI SANT',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ka lama khraw la sei,',
          'Ka Gospel Blei ka long;',
          "Ka dujok b'ishyrkhei,",
          'U Jisu la pynmong;',
          'Kan hap, kan hap, la imat skhem,',
          'Ha khmat U Jisu kam lah ïeng.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka dor pansngiat shiah,',
          'Ha khlieh U Syiem byneng;',
          'Ki nar sah kiba nep,',
          'Kham kor ïa ka jingrem;',
          'To wan khymih kane ka kam,',
          'Uba ïong eh u la lieh tam.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          "To riwai b'la ïohi,",
          'Ba mih jingshai byneng;',
          "To riwai b'la ïoh mad,",
          'Ki soh Kanaan ha neng;',
          'Ngin poi, ngin poi, ha Seïon lum,',
          'La don jingpep ha ri khlaw bun.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Wat ai jingieit kan swai,',
          'Jingieit ba kum lyoh ding;',
          'Kaba la thung U Trai,',
          'Ban lam ïa ngi sha ïing;',
          'Nga i ka ri ngan ïohïaka,',
          'Ngan shong lem bad U Trai babha.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Ah! Tynrai khraw jingsuk,',
          'Ka duriaw bah, khlem kut;',
          'Ha Me ïa kiba duk,',
          'Don spah ka bymjukut;',
          'Jong Me ka nam, ïa Me kin nguh,',
          'Byneng, pyrthei bad dujok ruh.',
        ],
      },
    ],
  },
  {
    id: 'song-227',
    title: 'Ka Jingnguh Namar Ka Gospel',
    metadata: {
      number: 227,
      language: 'khasi',
      syllables: '10.7.6',
      songId: 'song-227',
      tune: 'Mawlgan, Diolcham Yrefengyl',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: ['Ngi nguh ïa Me, Ah Blei ba lah baroh,', 'Namar ka Gospel Jisu,—Haleluïa,—AMEN.'],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: ['Haba ngi long ha ka ïing byndi dum,', 'Lawan ka jingshai byneng,—Haleluïa,—AMEN.'],
      },
    ],
  },
  {
    id: 'song-228',
    title: 'Ka Jingroi Ka Hima U Khrist',
    metadata: {
      number: 228,
      language: 'khasi',
      composer: 'Aberafon',
      syllables: '74.74.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Khymih shatai kan sa shai,`,
          `Ngin ïa kymen;`,
          `Ki riewdum kin wan kyrhai,`,
          `Ki da kyrmen;`,
          `Kin pynkhraw ï'U Khun U Blei,`,
          `Ha ka ïaroh;`,
          `Ba ïa ki U pynim ei,`,
          `Kin nguh baroh.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Kham ha khlieh ïa ka pyrthei,`,
          `Ha ka burom;`,
          `Long ka hima jong U Blei,`,
          `Junom, junom;`,
          `Ka ïing jong U kin ïohi,`,
          `Ki jaitbynriew;`,
          `Ïa ki lum kan paw ha khlieh,`,
          `Ba la kyntiew.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Ki riew kyndong ka pyrthei,`,
          `Kin wan kyrpad;`,
          `Ban ïoh mad ka jingaiei,`,
          `Jisu Kynrad;`,
          `Ïa ki hukum kiba khuid,`,
          `Kin sa rakhe;`,
          `Jingsuk kaba shlei, ba tuid,`,
          `Kan wan shane.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Babilon kan kyllon kram,`,
          `Bad u prophet;`,
          `Ki blei thala kin sa ngam,`,
          `Kham sha lyndet;`,
          `Hima kiba rit bad khraw,`,
          `La ki thala;`,
          `Kin sa nguh ï'U Blei Nongthaw,`,
          `Haleluïa!`,
        ],
      },
    ],
  },
  {
    id: 'song-229',
    title: 'Ki Shipai U Syiem Bneng',
    metadata: {
      number: 229,
      language: 'khasi',
      author: 'R.J.',
      composer: 'Canaan (S.S.680)',
      syllables: '76.76.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `To ïeng ïashah sh'U Jisu,`,
          `Phi shipai Syiem byneng;`,
          `To kaweh ïa ka lama,`,
          `To rah ruh kham shaneng;`,
          `Na jingjop sha ka jingjop,`,
          `L'U paid ïapom Un lam;`,
          `Ki nongshun jong U baroh,`,
          `Sha jingjot kin ïa ngam.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `To �ïeng ïashah sh'U Jisu,`,
          `Ka turoi ka la jam;`,
          `Shaphrang, ka jur ka thyma,`,
          `Ïatur, ïapom, U lam;`,
          `Phi kiba khlaiñ, to ïeng,`,
          `Ki bun ki nongïaleh;`,
          `Jingshlur kan mih na jingma,`,
          `Ngin jop, ngin jop la eh.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `To ïeng iashah sh'U Jisu,`,
          `To bat ka bor jong U;`,
          `Wat nud ban ieng marwei,`,
          `Ka bor u briew kan duh;`,
          `Ki tiar ïa pom to kieng noh,`,
          `To sharai, to kyrpad;`,
          `Ha shitom lane jingma,`,
          `To kohnguh l'U Kynrad.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `To ïeng iashah sh'U Jisu,`,
          `Ka jingïaleh nym slem;`,
          `Ka jam ka thyma mynta,`,
          `Lashai jingrisa'n shem;`,
          `Ha uba lah ha thyma,`,
          `Ka nam nongjop yn ai;`,
          `Ha khet U Syiem ka burom,`,
          `Un synshar ruh khlem wai.`,
        ],
      },
    ],
  },
  {
    id: 'song-230',
    title: 'Shipai Jong U Jisu',
    metadata: {
      number: 230,
      language: 'khasi',
      author: 'H.S.R.',
      composer: 'St. Gertrude Rachie',
      syllables: '65.65.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Shipai jong U Jisu,`,
          `Ryntih baroh lang;`,
          `Haba riew ka turoi,`,
          `Ïa ngin tur shaphrang;`,
          `Khrist U Kapten jong ngi,`,
          `Uba donbor tam;`,
          `Sha ka jingjop thiaw,`,
          `Ïa ngi Un ïalam.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `La ka thma ka nang jur,`,
          `Lei lei wat kynran;`,
          `Shaniah tang h'U Jisu,`,
          `Dei ma U ba shan.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Ha jingshakri ïa U,`,
          `Don ka kam kyrhai;`,
          `Kiba hap ban khring pat,`,
          `Pynshait kiba swai;`,
          `Man ka sngi ka por hi,`,
          `Ï'U ngin kyntiew nam;`,
          `Sha ka jingjop thiaw,`,
          `Ïa ngi Un ïalam.`,
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          `Shaphrang to ngin nang tur,`,
          `Ha ka liang U Trai;`,
          `Ïalap ïa ka Gospel,`,
          `Ïaid ruh ha jingshai,`,
          `Hukum jong U ngin leh,`,
          `Bainong ai kan dam;`,
          `Sha ka jingjop thiaw,`,
          `Ïa ngi Un �ïalam.`,
        ],
      },
    ],
  },
  {
    id: 'song-231',
    title: 'Ka Jingjop Ka Gospel',
    metadata: {
      number: 231,
      language: 'khasi',
      composer: 'Missionary',
      syllables: '76.76.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Na ri lum thah ka Greenland,`,
          `Naduh ri India ngi;`,
          `Na ki um kyrsoi Aphrik,`,
          `Ba kit maw ksiar hi.`,
          `Na ki dewlang ri Lyngngam,`,
          `Naduh ki wah barim;`,
          `Ki duwai lem ‘To ïalam,`,
          `Na jingïap sha jingim.’`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `La lyer iwbih ba pyngngad,`,
          `Ka beh ha ri Silon;`,
          `La baroh ka itynnad,`,
          `U briew ha sniew u shong,`,
          `Ka long lehnohei suda,`,
          `Ban theh ki jingai Blei;`,
          `Ba sah u briew ha thala,`,
          `B'u dem ï'u ksuid u khrei.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Ma ngi b'la ïoh ka jingshai,`,
          `Jingstad ba khuid byneng;`,
          `Ngi lah riewdum ban bynnud,`,
          `Ka sharak ka jingim?`,
          `Jingpynim! Ah Jingpynim!`,
          `Ka ktien sngewbha ïalap;`,
          `Ba baroh khun ka jingtim,`,
          `Ï'U Jisu kin ïasngap.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Kit, kit phi lyer ka jingong,`,
          `Phi ruh ki um tyllun;`,
          `Ka Gospel kat ka duriaw,`,
          `Kan tap lup pyrthei p'lun,`,
          `Ki bynriew ba la siewspah,`,
          `Ba siew ïashah U Khun;`,
          `L'U Syiem ba thaw ba pynim,`,
          `Kin wan ïadem ïanguh.`,
        ],
      },
    ],
  },
  {
    id: 'song-232',
    title: 'Ka Jingsynshar U Khrist',
    metadata: {
      number: 232,
      language: 'khasi',
      author: 'J.C.E.',
      composer: 'Duke Street',
      syllables: 'L.M',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `U Jisu Khrist Un synshar lut,`,
          `Ka pyrthei bah na kut sha kut;`,
          `Ka hima jong U kan nang pur,`,
          `Katba dang sah ka sngi bad khlur.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `To synshar hi, ko Trai ki paid,`,
          `Ki koidi na ki nar kin lait;`,
          `Riew thait kin shem ka jingsuk jai,`,
          `Ka shitom baroh de kan wai.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Ki jingthaw baroh ha pyrthei,`,
          `To ai kin ïaroh lang ï'U Blei;`,
          `Ki angel neng to shad kymen,`,
          `Ka khyndew ruh to ong, AMEN.`,
        ],
      },
    ],
  },
  {
    id: 'song-233',
    title: 'Ka Jubil Bneng',
    metadata: {
      number: 233,
      language: 'khasi',
      syllables: '87.87.47',
      songId: 'song-233',
      tune: 'LEWES',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Lyndet lum, ki lyoh bad jingdum,',
          'Suk mynsiem khymih shatei;',
          'Ki jingkular kin sa pynmih,',
          'Їa ka sngi ka jingisnei;',
          'Jubil byneng,',
          'Kata ka sngi ai ngin i.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Wan phi bynriew, wan phi baroh,',
          'Wan nongkyndong ban ïohi;',
          'Їa ka jingjop ba U Jisu,',
          'U la ïoh ha Kalbari;',
          'Ai ba Gospel,',
          'Kan sawa na kut sha kut.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Bun ki ri ba shong ha jingdum,',
          'Ah ban poi jingshai ha ki!',
          'Їa ka miet ba dum to beh noh,',
          'Naduh mihngi sha sepngi;',
          'Ka jingpynim,',
          'Tang ma ka to ai kan jop.',
        ],
      },
    ],
  },
  {
    id: 'song-234',
    title: 'Ka Jingsynshar U Khrist',
    metadata: {
      number: 234,
      language: 'khasi',
      author: 'J.C.E.',
      composer: 'Sicily',
      syllables: '87.87.47',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Trai to synshar ha ka pyrthei,`,
          `Naduh mihngi sha sepngi;`,
          `To pynïoh ki hima baroh,`,
          `Kum ka bynta jong Me hi;`,
          `Jingshai byneng,`,
          `To pynshai ïa ka pyrthei.`,
        ],
      },

      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Ka ri India khraw ba riewspah,`,
          `Ba la dap da ka jingdum,`,
          `Ai kan pydiang ïa ka Gospel,`,
          `Ha ri them bad ha ri lum:`,
          `Te ka jingsuk,`,
          `Kan pyndap na kut sha kut.`,
        ],
      },

      {
        id: 'verse-3',
        order: 5,
        type: 'verse',
        lines: [
          `Ï'U Syiem Seïon to kin riwai,`,
          `Da ki sur sngewbha ba bang;`,
          `Naduh shatei shaduh shathie,`,
          `Ai kin burom ïa U lang:`,
          `Ai kin ïaroh,`,
          `Jingitynnad Syiem byneng.`,
        ],
      },
    ],
  },
  {
    id: 'song-235',
    title: 'Ka Jingkyrmen ïa ka kam',
    metadata: {
      number: 235,
      language: 'khasi',
      syllables: '87.87.47',
      songId: 'song-235',
      tune: 'GNOLL AVENUE',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ah! mynsynñia nga shu khymih,',
          'Khymih lano kan sa shai;',
          'Khymih ba kin plie ki khyrdop,',
          'Na ki nar ba khum ban lait:',
          'Byrngut Jubil,',
          'Lano shisha kan sa paw?',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Kum ka leilieh her jingbyna,',
          'Her ban jop ki bynriew phar;',
          'Ai ki pud kin ïar noh kylleng,',
          'Їa ka pyrthei ban synshar:',
          'Ktien ka jingim,',
          'Sha ba kut ka duriaw poi.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Mih to mih ka sngi ba tyngshaiñ,',
          'Beh ka jingdum na ki briew;',
          'Ka jingsawa jingput Gospel,',
          'Hangne bad shaneng kan riew;',
          'Baroh kawei,',
          'Hima bah Immanuel.',
        ],
      },
    ],
  },
  {
    id: 'song-236',
    title: 'Ka Jingsynshar U Khrist',
    metadata: {
      number: 236,
      language: 'khasi',
      composer: 'Houghton',
      syllables: '10.10.11.11',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `U Syiem ka Seïon Un synshar donbor,`,
          `Ka pyrthei baroh ïa U kan kohnguh;`,
          `Un pynlong la hima ka burom kham kor,`,
          `Ka synshar ka jong U te junom kam duh.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Ah Blei, bor bah jong ngi mynno mynno,`,
          `Ka jingkyrmen jong ngi lano lano;`,
          `Long nongïalam jong ngi katba ngi dang sah,`,
          `Ka jaka rieh jong ngi ka long bym ju jah.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Jisu, Me la wad ïa nga u nongwei,`,
          `Uba la sakma na ka ïing U Blei;`,
          `Me, Men pynim ïa ka mynsiem jot jong nga,`,
          `Ka snam, Me la pynmih, ka snam kordor bah.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Shait eh ban sakma, Trai nga sngew kata,`,
          `Shait ruh ban phai na Me, Uba nga ieit;`,
          `Shim dohnud jong nga Trai, shim pynskhem ïa ka,`,
          `Ba ngan ïaid hun bad Me, Ah Kynrad ba bha.`,
        ],
      },
    ],
  },
  {
    id: 'song-237',
    title: 'Trai Pynim La Ka Kam',
    metadata: {
      number: 237,
      language: 'khasi',
      author: 'H.L.',
      composer: 'St. Bride',
      syllables: 'S.M',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Trai pynim la ka kam,`,
          `Haba Seïon ka swai;`,
          `Ki jingtlot jong ka to pyndam,`,
          `Da bor Blei ba kynsai.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `La ki briew to pynshai,`,
          `Sha mynsiem ba duwai;`,
          `Ai la kular kin pynthymmai,`,
          `Syllok bad la U Trai.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Hangta Mynsiem Un kren,`,
          `Da thylliej tlot jong ngi;`,
          `Hangta kin um ki dohnud rben,`,
          `Bad nongleh kiat kin phai.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Ah Trai, to sngewïangi:`,
          `Ngi ïam, ngi nguh, ngi dem;`,
          `Ah wallam jingpynim ïa ngi!`,
          `Ha Me ngi shaniah skhem.`,
        ],
      },
    ],
  },
  {
    id: 'song-238',
    title: 'Ka Jingsngewshngaiñ Ha U Khrist',
    metadata: {
      number: 238,
      language: 'khasi',
      composer: 'St. Austin',
      syllables: '664.6664',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `B'U Jisu U dang im,`,
          `Un lam ki khun jingtim,`,
          `Sha ïing U Blei;`,
          `Ko khun ka Seïon, shad,`,
          `L'U Kynrad pha la wad;`,
          `Sa khyndiat eh sa mad,`,
          `Jingieit ba shlei.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Ah! ngin ïoh riwai lang,`,
          `Ha khet U Trai kan bang,`,
          `Mynsiem la hun,`,
          `Ki paitbah bun shatei,`,
          `Na baroh ka pyrthei,`,
          `La jingïaroh ki sei,`,
          `‘Burom ï'U Khun.’`,
        ],
      },
    ],
  },
  {
    id: 'song-239',
    title: 'Ngin nang ïaid sha Seïon',
    metadata: {
      number: 239,
      language: 'khasi',
      composer: 'S. S. 823',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ale phi khun U Blei,',
          'Da jingkmen to ngin rwai;',
          'Ban pynsawa jingieit U Blei,(2 sien)',
          'Sawdong ka Khet U Trai.(2 sien)',
        ],
      },
      {
        id: 'chorus',
        order: 2,
        type: 'chorus',
        lines: [
          'Ngin nang ïaid ska Seïon,',
          'Seïon itynnad jong U Trai;',
          'Ngin nang ïaid shatei sha Seïon,',
          'Sha Nongbah Bakhuid jong U Trai.',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          'Phi ki khun U Syiem Bneng,',
          'To kyntiew nam khlem wai,',
          'Pynbna kyrteng U Trai kylleng,(2 sien)',
          "Ba bynriew tip ï'U Trai.(2 sien)",
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          "H'u lum Seïon ba dap,",
          'Da burom jong U Trai;',
          'Ngin ïaid ha lynti ksiar-nylla,(2 sien)',
          'Ban poi ri bneng phyrnai.(2 sien)',
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          'Jingrwai thiang yn ïaisah,',
          'Katba shaphrang nang ïaid;',
          'Ngin nang ïaid sha ka ri U Trai,(2 sien)',
          'Ri bathiang bym ju blad.(2 sien)',
        ],
      },
    ],
  },
  {
    id: 'song-240',
    title: 'Trai PynimÏa Ka Kam',
    metadata: {
      number: 240,
      language: 'khasi',
      author: 'D.E.S.',
      composer: 'S.S. 309',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Trai pynim ïa ka kam,`,
          `Ha la ki briew wan paw;`,
          `Ah kren ha ngi da l'U Mynsiem,`,
          `Burom Me ban pynkhraw.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Trai pynim ïa ka kam,`,
          `Ngi dem duwai ha Me;`,
          `Ah hiar! Ah hiar! da l'U Mynsiem,`,
          `Kyrkhu lang ngi hangne.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Trai pynim ïa ka kam,`,
          `Pynkhraw ïa la Kyrteng;`,
          `Ba jingieit jong Me ha ngi'n shem,`,
          `B'la thang rhem da ding bneng.`,
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          `Trai pynim ïa ka kam,`,
          `Ktien jong Me ban pynbna;`,
          `Ba mynsiem swai, bajot bad rem,`,
          `Shem jingpynim phylla.`,
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          `Trai pynim ïa ka kam,`,
          `Lapbah Pentekost ai;`,
          `Jingnguh, Trai, ngi ai lut sha Me,`,
          `Kyrkhu ïa ngi khlem wai.`,
        ],
      },
    ],
  },
  {
    id: 'song-241',
    title: 'Ka Jingduwai Na Ka Bynta Ki Nongtrei',
    metadata: {
      number: 241,
      language: 'khasi',
      author: 'H.L.',
      composer: 'Bwlchgwyn',
      syllables: 'C.M',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ngi nguh ngi dem ha Me, Ah Blei,`,
          `Kane ka por kyntang;`,
          `Ngi duwai ba Men sngewsynei,`,
          `Jingkyrpad ka Balang.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Ka khlaw ka bun ba dei ban prat,`,
          `Nongtrei ruh duna bun;`,
          `Ha jingdum ngi pan, Ah! to shat,`,
          `Jingshai ka hok U Khun.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Ïa kiba Me la mon ban khot,`,
          `Ïa kiba sngew ïa Me;`,
          `Ah Blei, kyrkhu kin bet kin ot,`,
          `Kat kum ka mon jong Me.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `Pyndap ïa ki da U Mynsiem,`,
          `Da bor ka jingieit Blei;`,
          `Ïa U Jisu ai kin syriem,`,
          `Da ki, Ah Blei, to trei.`,
        ],
      },
    ],
  },
  {
    id: 'song-242',
    title: 'Haba Thung Nongsharai',
    metadata: {
      number: 242,
      language: 'khasi',
      author: 'G.L.',
      composer: 'Dismissal',
      syllables: '87.87.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ko Trai Jisu, ko Nongpynim,`,
          `Me U bym lah ban kylla;`,
          `Kular jong Me ki ïaineh skhem,`,
          `La ka Balang ban ïada;`,
          `Ïa ki Nongsharai nang pynmih,`,
          `Kiba Me hi Me la khot;`,
          `Kam ka jong Me kin kit kin bah,`,
          `Khlem sngewthait bad khlem sngewtlot.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Hangne ruh mynta, ai ngin sngew,`,
          `Jingdon jong Me lem bad ngi;`,
          `Da lade hi wan pynkyntang,`,
          `Ban thung ïa la ki shakri.`,
          `Ïa kine mynta to kyrkhu,`,
          `Da la kti isnei jong Me;`,
          `Pynkup ruh ka bor U Mynsiem,`,
          `Shan ïa ki ha ki jingeh.`,
        ],
      },
    ],
  },
  {
    id: 'song-243',
    title: 'Nga La Pdiang Jingkhot U Trai',
    metadata: {
      number: 243,
      language: 'khasi',
      author: 'H.L.L.',
      composer: 'R.S. 297',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Nga la pdiang jingkhot Nongpynim,`,
          `Nga la pdiang jingkhot Nongpynim,`,
          `U la kren ha dohnud jong nga;`,
          `Bah la diengphna mynta bad shirta.`,
        ],
      },

      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Ngan bud shano Un lam ïa nga,`,
          `Ngan bud shano Un lam ïa nga,`,
          `Katba Un lam ngan bud ïa U;`,
          `Lynter lynti ngan bud ï'U Jisu.`,
        ],
      },

      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Ngan ïaid lem lyngba ka brisoh,`,
          `Ngan ïaid lem lyngba ka brisoh,`,
          `Jingthung kordor ki don ha ka;`,
        ],
      },
      {
        id: 'chorus-3',
        order: 6,
        type: 'chorus',
        lines: [`Kam ba dawa ïa nga don hangta.`],
      },
      {
        id: 'verse-4',
        order: 7,
        type: 'verse',
        lines: [
          `Ngan bud ïa U ha jingtynjuh,`,
          `Ngan bud ïa U ha jingtynjuh,`,
          `Nga tip shai U don lem bad nga;`,
        ],
      },
      {
        id: 'chorus-4',
        order: 8,
        type: 'chorus',
        lines: [`Ïa kane nga tip bha ngam bakla.`],
      },
      {
        id: 'verse-5',
        order: 9,
        type: 'verse',
        lines: [
          `Un pynïoh ïa nga ka burom,`,
          `Un pynïoh ïa nga ka burom,`,
          `Hadien bun ki jingshah shitom;`,
        ],
      },
      {
        id: 'chorus-5',
        order: 10,
        type: 'chorus',
        lines: [`Ngan shong lem bad U hi shi junom.`],
      },
    ],
  },
  {
    id: 'song-244',
    title: 'Ka Kam Ba Ngin Trei',
    metadata: {
      number: 244,
      language: 'khasi',
      author: 'H.L.L.',
      composer: 'S.S. 751',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Sha ka kam U Kynrad ngi ki shakri U Blei,`,
          `Bud ka lynti ba U Trai U ïaid ha pyrthei,`,
          `Ha jingkynpham jong U bor ngin ïai pynthymmai;`,
          `Aiti lut la ki sap ba U hi U la ai.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `To ngin trei, nang ïai trei,`,
          `To ngin trei, nang �ïai trei;`,
          `Ngin kyrmen ngin sharai,`,
          `Haduh ba Kynrad Un wan phai.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Sha ka kam U Kynrad, langbrot ba thngan ngin bsa;`,
          `Na jingma u nongshun dei ma ngi ban ïada;`,
          `Ha lyngkor ka diengphna burom ïa ngi ka ïeng,`,
          `Katba ngi ïai ïalam sha jingshongthait ha bneng.`,
        ],
      },
      {
        id: 'chorus-2',
        order: 4,
        type: 'chorus',
        lines: [
          `To ngin trei, nang ïai trei,`,
          `To ngin trei, nang ïai trei;`,
          `Ngin kyrmen ngin sharai,`,
          `Haduh ba Kynrad Un wan phai.`,
        ],
      },
      {
        id: 'verse-3',
        order: 5,
        type: 'verse',
        lines: [
          `Sha ka kam U Kynrad don ka jingtrei kyrhai;`,
          `Ban pynbeit ka lynti ba kynhun bah ki phai,`,
          `Kyrteng U Jisu Khrist to ngin nang ïai kyntiew,`,
          `Ring sha jingieit jong U na ka pyrthei basniew.`,
        ],
      },
      {
        id: 'chorus-3',
        order: 6,
        type: 'chorus',
        lines: [
          `To ngin trei, nang ïai trei,`,
          `To ngin trei, nang ïai trei;`,
          `Ngin kyrmen ngin sharai,`,
          `Haduh ba Kynrad Un wan phai.`,
        ],
      },
      {
        id: 'verse-4',
        order: 7,
        type: 'verse',
        lines: [
          `Sha ka kam U Kynrad ha jingieit jong U Trai,`,
          `Jaiñkup ba lieh bad pansngiat U kular ban ai,`,
          `Lem bad riewkhuid ngin long ha khmat jong U junom;`,
          `B'la siewspah da ka snam ngin phyrnai ha burom.`,
        ],
      },
      {
        id: 'chorus-4',
        order: 8,
        type: 'chorus',
        lines: [
          `To ngin trei, nang ïai trei,`,
          `To ngin trei, nang ïai trei;`,
          `Ngin kyrmen ngin sharai,`,
          `Haduh ba Kynrad Un wan phai.`,
        ],
      },
    ],
  },
  {
    id: 'song-245',
    title: "Bud ï'U Kynrad Ha Ki Jingeh",
    metadata: {
      number: 245,
      language: 'khasi',
      author: 'H.L.L.',
      composer: 'S.S. 544',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ha lade hi ngam shym pyrkhat,`,
          `Ha pyrthei nga wad bun ki lad;`,
          `Pynban jingieit jong Me ka bat;`,
          `Mon jong Me ngam lah ban khlad.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Ha dienjat Nongpynim ngan bud,`,
          `Ha dienjat Nongpynim ngan bud,`,
          `Kyrshan bor ba ngan ïai aiti;`,
          `Bud ïa U lynter ki sngi.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Ka lynti shisha kaba eh,`,
          `Kjat jong nga ba tlot ban pyneh,`,
          `Kren ha nga ngan sngew man ka sngi;`,
          `Shisha nga la jied ïa phi.`,
        ],
      },
      {
        id: 'chorus-2',
        order: 4,
        type: 'chorus',
        lines: [
          `Ha dienjat Nongpynim ngan bud,`,
          `Ha dienjat Nongpynim ngan bud,`,
          `Kyrshan bor ba ngan ïai aiti;`,
          `Bud ïa U lynter ki sngi.`,
        ],
      },
      {
        id: 'verse-3',
        order: 5,
        type: 'verse',
        lines: [
          `Jingtynjuh ha pyrthei kin wan,`,
          `Erïong jingim ki lah ban ban,`,
          `Kdup ïa nga da ksangti ba jem,`,
          `Ba ngan ïeng skhem khlem pyndem.`,
        ],
      },
      {
        id: 'chorus-3',
        order: 6,
        type: 'chorus',
        lines: [
          `Ha dienjat Nongpynim ngan bud,`,
          `Ha dienjat Nongpynim ngan bud,`,
          `Kyrshan bor ba ngan ïai aiti;`,
          `Bud ïa U lynter ki sngi.`,
        ],
      },
      {
        id: 'verse-4',
        order: 7,
        type: 'verse',
        lines: [
          `Nanglaw ïa ki jingteh pyrthei,`,
          `Dohnud ring ba ngan peit shatei,`,
          `Barabor kti jong Me kan btin,`,
          `Ngan ïaid beit khlem kylla dien.`,
        ],
      },
      {
        id: 'chorus-4',
        order: 8,
        type: 'chorus',
        lines: [
          `Ha dienjat Nongpynim ngan bud,`,
          `Ha dienjat Nongpynim ngan bud,`,
          `Kyrshan bor ba ngan ïai aiti;`,
          `Bud ïa U lynter ki sngi.`,
        ],
      },
    ],
  },
  {
    id: 'song-246',
    title: 'Ïai Trei Ha Ka Balang',
    metadata: {
      number: 246,
      language: 'khasi',
      author: 'H.L.L.',
      composer: 'S.S. 754',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ha jingker U Trai ka kam ka dawa;`,
          `Jingud ba jylliew nongtrei ki duna,`,
          `Ha jingkhot jong U ka dohnud ka shlei;`,
          `Balang U Blei ban nang ïai tei.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Ngin ïai trei, ngin ïai trei,`,
          `Peit ka nong ba thiang shatei,`,
          `Namar U Trai Un ong bor thymmai Un ai;`,
          `Ngin ïai trei haduh ban da wai.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Seïon jong U Trai kan nang ïai phyrnai,`,
          `Ka pyrthei ba sniew kan ym lah pynswai,`,
          `Siewspah por kordor, jingkular ngin bat;`,
          `Jingkmen U Kynrad don ha khmat.`,
        ],
      },
      {
        id: 'chorus-2',
        order: 4,
        type: 'chorus',
        lines: [
          `Ngin ïai trei, ngin �ïai trei,`,
          `Peit ka nong ba thiang shatei,`,
          `Namar U Trai Un ong bor thymmai Un ai;`,
          `Ngin ïai trei haduh ban da wai.`,
        ],
      },
      {
        id: 'verse-3',
        order: 5,
        type: 'verse',
        lines: [
          `Ban wad ki langbrot jingsngewbha ngin shem,`,
          `La ka kam ka eh, lyngkor Un pynjem,`,
          `Jingkit U Kynrad ngin bah ha tyrpeng,`,
          `Mawsiang jingpynim, skhem ngin ïeng.`,
        ],
      },
      {
        id: 'chorus-3',
        order: 6,
        type: 'chorus',
        lines: [
          `Ngin �ïai trei, ngin ïai trei,`,
          `Peit ka nong ba thiang shatei,`,
          `Namar U Trai Un ong bor thymmai Un ai;`,
          `Ngin ïai trei haduh ban da wai.`,
        ],
      },
      {
        id: 'verse-4',
        order: 7,
        type: 'verse',
        lines: [
          `Khmih ka phang jingtrei kumba U la khot,`,
          `Ha jingtlot sngewhun tang ban ïai minot;`,
          `Jingsawa ba thiang U Trai ngin kynud,`,
          `Leit sha ka jingkmen bymjukut.`,
        ],
      },
      {
        id: 'chorus-4',
        order: 8,
        type: 'chorus',
        lines: [
          `Ngin ïai trei, ngin ïai trei,`,
          `Peit ka nong ba thiang shatei,`,
          `Namar U Trai Un ong bor thymmai Un ai;`,
          `Ngin ïai trei haduh ban da wai.`,
        ],
      },
    ],
  },
  {
    id: 'song-247',
    title: 'Pyneh Ha Jingïaleh',
    metadata: {
      number: 247,
      language: 'khasi',
      author: 'H.L.L.',
      composer: 'R.S. 407',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ah Trai Me la khot ïa nga,`,
          `Shawei na neng Mem shah ba ngan ïaid bakha;`,
          `Jingieit jong Me ïa nga ba;`,
          `Tang na Me hi ïa kane nga pan.`,
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          `Nongpyn ka pyrthei,`,
          `Theh ba nga la jingawei;`,
          `Ki langbrot jong Me ban ba,`,
          `Da la dohnud jingieit ba shisha.`,
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          `Katba jingïaleh ki ban,`,
          `Pynkynmaw katno ha Me ki ban,`,
          `Ai ba ngan ban, da jingsngewmen,`,
          `Ktien ba jem na nga Ah Trai ïai kren.`,
        ],
      },
      {
        id: 'chorus-2',
        order: 4,
        type: 'chorus',
        lines: [
          `Nongpyn ka pyrthei,`,
          `Theh ba nga la jingawei;`,
          `Ki langbrot jong Me ban ba,`,
          `Da la dohnud jingieit ba shisha.`,
        ],
      },
      {
        id: 'verse-3',
        order: 5,
        type: 'verse',
        lines: [
          `Pop ha pyrthei, roi ba byllien;`,
          `Jingieit na khait, Me la kren ka ktien,`,
          `Jingsngewdaiaw nga tip nga shem,`,
          `Bor baing ngi byneng ba ngan ïai bat skhem.`,
        ],
      },
      {
        id: 'chorus-3',
        order: 6,
        type: 'chorus',
        lines: [
          `Nongpyn ka pyrthei,`,
          `Theh ba nga la jinga,`,
          `Ki langbrot jong Me ban ba,`,
          `Da la dohnud jingieit ba shisha.`,
        ],
      },
      {
        id: 'verse-4',
        order: 7,
        type: 'verse',
        lines: [
          `Tang kha ba khang ha nga;`,
          `Minot na hangta kum ba,`,
          `Ktien ba, sngewbha ba,`,
          `Men ong ba nga Men shong.`,
        ],
      },
      {
        id: 'chorus-4',
        order: 8,
        type: 'chorus',
        lines: [
          `Nongpyn na pyrthei ba,`,
          `Niang ba nga na jinga,`,
          `Baing ngong jong Me na ba, nga,`,
          `Da nga ba jingieit na shisha.`,
        ],
      },
    ],
  },
  {
    id: 'song-248',
    title: 'Kaba Pynkyntang ba Ki Ning',
    metadata: {
      number: 248,
      language: 'khasi',
      author: 'H.L.L.',
      composer: 'R.S. 483',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Jaing baing sha ba nga ngi ba,`,
          `ba nga ba ngi baseng;`,
          `ba ba nga ba nga briewing,`,
          `ba ba ning ba pynnging.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Khmih ba nga ba ka nga Blei ba,`,
          `ba ba ba baing,`,
          `Kiba ba nga ba shaingtrei,`,
          `ba ba nga ba ba ki ba.`,
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          `Ba ba ba ba nga ba pynkup,`,
          `ba ba ning ha pynngiing;`,
          `haingkting sa nga ba,`,
          `ba ba na rung ba nga baing.`,
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          `ba nga ba khmat ba, nga ngi ba,`,
          `Kting ka ba ba ba;`,
          `ba ngkhing ba pdiang kba ba Me ba,`,
          `ba nga ba ba kumjuh.`,
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          `Ba kin ba nga sha ba ha khmat ba,`,
          `ba ba ba nga baid,`,
          `ba lam ba nga ba nga ba, baing, ba ba,`,
          `ba ba baing ba lait.`,
        ],
      },
      {
        id: 'verse-6',
        order: 6,
        type: 'verse',
        lines: [
          `ba basing ba nga pynkingngang, ba ba, baing ba,`,
          `Ba ba baing Bnei ba, khid;`,
          `ba ba ba ba ba ba nga;`,
          `baing ba ba ba tuid.`,
        ],
      },
    ],
  },
  {
    id: 'song-249',
    title: 'Pynkyntang Nongsharai',
    metadata: {
      number: 249,
      language: 'khasi',
      author: 'S.M.ROY',
      composer: 'Henryd',
      syllables: '87.87.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          `Ah Trai baieit bad ba isnei,`,
          `La ka Balang Me la seng;`,
          `Me ïai pynmih ïa ki nongtrei,`,
          `Kiba sngew jingkhot naneng;`,
          `Me khot ïa kine ki shakri,`,
          `Ban ïai trei kam jong Me Trai,`,
          `To wan pynkyntang ma Me hi,`,
          `Ban shakri ïa Me khlem wai.`,
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          `Da U Mynsiem aiborïaki,`,
          `Ban ïai shakri tang ïa Me;`,
          `Ka Balang kan long shitylli,`,
          `Ban paw ka burom jong Me;`,
          `Kyrshan ïa ki ha ki jingeh,`,
          `Ha jingtynjuh bad khuslai;`,
          `Ba jingieit jong Me kan ïaineh,`,
          `Haduh ba jingtrei la wai.`,
        ],
      },
    ],
  },
];
