import { SongT } from '~/src/types/song';

export const shaphangUKhrist: SongT[] = [
  {
    id: 'song-026',
    title: 'Ka Jingwan U Messaiah',
    metadata: {
      number: 26,
      language: 'khasi',
      author: 'T.J.J.',
      composer: 'Dominus Regit Me (87.87.) (Iambic)',
      syllables: '87.87',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'U Blei ha doh jong ngi la wan,',
          'U Lok bla man Nongsiewspah;',
          'Jar uba ngeit da dohnud skhem,',
          'La tlot um rem da shisha.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Jingknia bah jong ka diengphna,',
          'Ka kuna bla siew Jisu;',
          'Tang kane hi kaba donbor,',
          'Mynsiem ba tlor ban kyntiew.',
        ],
      },
    ],
  },
  {
    id: 'song-027',
    title: 'Ka Jingrwai Ki Angel',
    metadata: {
      number: 27,
      language: 'khasi',
      author: 'H.S.R.',
      composer: 'Mendelssohn (S.S.30.)',
      syllables: 'S.S.30',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Sngap ba rwai ki paidbah angel,',
          '‘Burom ia U Syiem bla kha,',
          'Ha pyrthei la wan ka jingsuk,',
          'Sha ki briew ka jingsngewbha;',
          'Bneng bad pyrthei burom ai,',
          'Ia U Jisu Khrist U Trai.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'U la wan na bneng sha pyrthei,',
          'Syiem ki syiem, U Trai ki Trai,',
          'La ka khet ka burom iehnoh,',
          'U la shong ha sem kulai;',
          'U la wan U Khun U Blei.',
          'Khnang ia ngi ban pynim ei.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Burom ia U Syiem ka jingsuk,',
          'Burom iU Immanuel;',
          'Ha kiba ha khlieh tam eh ruh,',
          '‘Burom.’ rwai phi ki angel;',
          'Bneng bad pyrthei burom ai,',
          'Ia U Jisu Khrist U Trai.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ynda lait shiliang wah Jordan,',
          '‘Ngin iohi kumba U long’;',
          'Ha ka bor ka burom tyngshain,',
          'Lem bad angel ngin ioh shong;',
          'Hangta burom ngin ia ai,',
          'Ia U Jisu khlem da wai.',
        ],
      },
    ],
  },
  {
    id: 'song-028',
    title: 'Kaba Kynja Doh U Khrist',
    metadata: {
      number: 28,
      language: 'khasi',
      composer: 'Ballerma (C.M.)',
      syllables: 'C.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Bla kyrkhu long ka bor jingstad,',
          'Ka hok, ka jingieit ruh;',
          'Kiba iasoh lem ban pyllait,',
          'Iu briew ban ym jot shuh.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Bla kyrkhu long U Blei bla phah,',
          'LU Khun ban kynja briew;',
          'Tang Une hi, ym don ba lah,',
          'Ka ram jong ngi ban siew.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Bla kyrkhu long U Khun bla wan,',
          'Na la ka mon sngewbha;',
          'Namar ia kiba shun pynban,',
          'Jingkordit U la shah.',
        ],
      },
    ],
  },
  {
    id: 'song-029',
    title: 'U Blei Ha Ka Doh',
    metadata: {
      number: 29,
      language: 'khasi',
      author: 'M.B.',
      composer: 'Mendelssohn (S.S.30.) (77.77.D.)',
      syllables: '77.77.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Sngap ki angel ki riwai,',
          'Khubor sngewbha jong U Trai;',
          'Ba la kha iU Syiem jingsuk,',
          'Ha shnong Bethlehem baduk.',
          'Phi ki bynriew baroh lang,',
          'To iakyntiew sur ba bang;',
          'Ha U Blei ba long Nongthaw,',
          'BU wan shim ka jinglongmraw.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Khrist bla phong da burom Blei,',
          'Trai ka bneng bad ka pyrthei;',
          'La urlong ba Un wan paw,',
          'Kum u bynriew bU la thaw.',
          'Peit! U Blei ha doh la wan,',
          'Ah jingphylla, jingmaian;',
          'IU Immanuel Bakhuid,',
          'Junom jingiaroh kan tuid.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Na ka khet burom ha neng,',
          'Ba U synshar ruh kylleng;',
          'U la wan ban shah jingtim,',
          'Ia ka pyrthei ban pynim.',
          'Ale Me ba bhabriew eh,',
          'Bad ngi, sngewbha, to shongneh;',
          'Ieng u symbai jong ka briew,',
          'Jop ha ngi ka pop ka sniew.',
        ],
      },
    ],
  },
  {
    id: 'song-030',
    title: 'Ka Jingwan Long Briew U Khrist',
    metadata: {
      number: 30,
      language: 'khasi',
      author: 'M.B.',
      composer: 'Irby (87.87.47.)',
      syllables: '87.87.47',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Mynwei ha ka shnong u Dabid,',
          'Jingphylla byneng la jia,',
          'Ba U Blei Bakhraw Bymjukut',
          'Ha ka shyngoid U la thiah;',
          'Te ka pyrthei,',
          'Ha U baroh kan sa dem.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ha ka sahit byneng phyrnai,',
          'Paidbah angel bym lah ñiew,',
          'IU Immanuel ki iaroh',
          'Ram ka pyrthei bU wan siew;',
          'Peit ko pyrthei,',
          'Jingshai jong pha ka la wan.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Phi ki ‘riewstad bret noh mynta,',
          'Ki jingpuson ba bun jait;',
          'Lam ka lynti ia ki Jentil,',
          'Bud iu khlur jong U ba iaid;',
          'Ba ngin ioh wan,',
          'Ban iakymen lem bad phi.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Na ka jingim khuid ka jong U,',
          'Thaba jingshai byneng hi,',
          'Te ka burom Blei ka iai kah,',
          'Ia ka dewmet tlot jong ngi;',
          'Peit ko pyrthei,',
          'Nongpynim jong pha la wan.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Pop bad jingiap ki ia khynñiuh,',
          'Tang shu paw U Syiem jingim,',
          'Peit ki phet iap da jinglyngngoh,',
          'Sha jinglehraiñ bad jingtim;',
          'Jisu jong ngi,',
          'Junom Un iai synshar hi.',
        ],
      },
    ],
  },
  {
    id: 'song-031',
    title: 'Ei Uta?',
    metadata: {
      number: 31,
      language: 'khasi',
      author: 'H.S.R.',
      composer: 'S.S. 66',
      syllables: 'S.S. 66',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: ['Ei Uta ba ki iadem,', 'Ki nongaplangbrot ha sem?'],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          'Dei U Trai! A ‘tien sngewphylla!',
          'Dei U Trai, U Syiem ka burom!',
          'Ha ki kjat jong U ngi dem;',
          'Ah to nguh ia U junom.',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: ['Ei Uta ha ri khlaw bah,', 'Jingjynjar, jingthngan U shah?'],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: ['Ei Uta ba ki kyrkhu,', 'Namar ‘tien jemnud jong U?'],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: ['Ei Uta hU ba nongpang,', 'Nongshem jynjar ki ialang?'],
      },
      {
        id: 'verse-5',
        order: 6,
        type: 'verse',
        lines: ['Ei Uta da jingpangnud,', 'Ha jingtep u Lasros ud?'],
      },
      {
        id: 'verse-6',
        order: 7,
        type: 'verse',
        lines: ['Ei Uta ba paidbah wan,', 'Da jingrisa iU ban tan?'],
      },
      {
        id: 'verse-7',
        order: 8,
        type: 'verse',
        lines: ['Ei Uta ba mynmiet hi,', 'Leit duwai sha Gethsmane?'],
      },
      {
        id: 'verse-8',
        order: 9,
        type: 'verse',
        lines: ['Ei Uta ha Kalbari,', 'Iap namar ka pop jong ngi?'],
      },
      {
        id: 'verse-9',
        order: 10,
        type: 'verse',
        lines: ['Ei Uta sawdong pyrthei,', 'Synshar hok hi tang marwei?'],
      },
    ],
  },
  {
    id: 'song-032',
    title: 'Ka Jingkhot Sha Bethlehem',
    metadata: {
      number: 32,
      language: 'khasi',
      author: 'E.H.W.',
      composer: 'Adeste Fideles (Irregular) (S.S.31.)',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'To wan phi ki riewngeit,',
          'Risa bad sngewkymen;',
          'Sha Bethlehem mynta ia ngin nguh iU Trai;',
          'Peit ha ka shyngoid,',
          'La kha iU Syiem ki Angel;',
          'To wan ia U ban mane, U Khrist U Trai.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'To khie, paidbah angel,',
          'Riwai jam ban iaroh;',
          'Lyngba bneng to sawa jingiaroh khlem wai,',
          'Mynta ha U Blei,',
          'Burom Syiem to theh sei;',
          'To wan ia U ban mane, U Khrist U Trai.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Amen! Trai ngi ainguh,',
          'Me bla wan ban pynim,',
          'Ko Jisu! ia Me ka burom junom ngi ai,',
          'Ktien jong U Kypa;',
          'Bla wan paw ha ka doh,',
          'To wan ia U ban mane, U Khrist U Trai.',
        ],
      },
    ],
  },
  {
    id: 'song-033',
    title: 'Ha Khmih U Nongpynim',
    metadata: {
      number: 33,
      language: 'khasi',
      composer: 'Wyddgrug (87.87.67.)',
      syllables: '87.87.67',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ha khymih, la ioh Nongpynim,',
          'Lok ba kordor ngi la shem;',
          'Bla iathuh ruh da u Moses,',
          'Bad ki prophet la mynslem;',
          'Khun U Blei sha pyrthei,',
          'U la wan ban pynim ei.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'U Khunlangbrot U jong U Blei,',
          'U la iap ha Kalbari;',
          'Ia ka ram jong ngi la siew dep,',
          'Lynti sha byneng la plie;',
          'Snam bla mih ha Kalbri,',
          'Jingsuk ka pynioh ia ngi.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Une U Lok bla dei ban ieit,',
          'Bad ban iaroh katba im;',
          'Jingim jong nga U la siewspah,',
          'Un nang sait na jinglong rim;',
          'Ale lang, ba sngewbang,',
          'IU ban iaroh, ei ba khang.',
        ],
      },
    ],
  },
  {
    id: 'song-034',
    title: 'Ka Jingwan U Messaiah',
    metadata: {
      number: 34,
      language: 'khasi',
      composer: 'Irish (C.M.)',
      syllables: 'C.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Sngewbha pyrthei, U Trai la wan,',
          'Ka pyrthei kan ianguh;',
          'Ki dohnud baroh kin iakhreh,',
          'Ban burom Syiem ia U.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Sngewbha pyrthei, Jisu synshar,',
          'Ki briew kin iai riwai,',
          'Tad da ki maw, ki lum, ki thor,',
          'Kin sawa pat sngewbha.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'U synshar da ka jingaiei,',
          'Ki hima U pynleh;',
          'Ka burom jong U ban pynpaw,',
          'Bad ka jingieit ba neh.',
        ],
      },
    ],
  },
  {
    id: 'song-035',
    title: 'Burom, Burom',
    metadata: {
      number: 35,
      language: 'khasi',
      author: 'H.S.R.',
      composer: 'Triumph (87.87.47.)',
      syllables: '87.87.47',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Burom ia U Syiem ki angel,',
          'Burom ia U Trai ki trai;',
          'Burom ia U Syiem ka burom,',
          'Bneng bad pyrthei burom ai.',
          'Burom, burom,',
          'Ia U Jisu Khrist U Trai.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Burom ia Uba ieit ia ngi,',
          'IU ba sait ka dohnud sniew;',
          'Burom iU bla thied rem ia ngi,',
          'Da ka dor ka snam bla siew,',
          'Burom, burom,',
          'Ia U Nongpynim ki briew.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Burom ia U Blei U Kypa,',
          'Burom ia U Khrist U Trai,',
          'Burom ia U Blei U Mynsiem,',
          'Burom junom iU Wei-Lai.',
          'Burom, burom,',
          'Burom junom hi khlem wai.',
        ],
      },
    ],
  },
  {
    id: 'song-036',
    title: 'Ka Jingkha Ia U Khrist',
    metadata: {
      number: 36,
      language: 'khasi',
      author: 'J.R.',
      composer: 'Lovely (66.66.88.)',
      syllables: '66.66.88',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          '‘Yn kha iU Jisu Khrist’,',
          'Bun pateng ki ju ong;',
          'La kha iU Jisu Khrist,',
          'Te mynta ka la long;',
          'Wat khuslai shuh nongpop ba pli,',
          'La kha iU Jisu Khrist ia ngi.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'La kordit ka la ban,',
          'Ia baroh ka pyrthei;',
          'Da Jisu Khrist la wan,',
          'Ka jinglait phar ba ei;',
          'Wat khuslai shuh nongpop ba pli,',
          'La kha iU Jisu Khrist ia ngi.',
        ],
      },
    ],
  },
  {
    id: 'song-037',
    title: 'Jisu Khrist U Nongpynim',
    metadata: {
      number: 37,
      language: 'khasi',
      author: 'J.R.',
      composer: 'S.S. 75',
      syllables: 'S.S. 75',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ei bla wan na neng sha ngi?',
          'Jisu Khrist Nangpynim,',
          'Bla wan khynnah duk ba pli?',
          'Jisu Khrist Nongpynim.',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: [
          'Riwai lang, iaroh khlem thait,',
          'U la khreh ka lad ban lait;',
          'Ah ba kordor! Ah ba ieit!',
          'Jisu Khrist Nongpynim.',
        ],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          'Ei bla shah ha diengphyna?',
          'Jisu Khrist Nongpynim;',
          'Ban sait ram ia phi bad nga?',
          'Jisu Khrist Nongpynim.',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          'Ei bla kular ban iamap?',
          'Jisu Khrist Nongpynim;',
          'Ei ba ai ka jingbymiap?',
          'Jisu Khrist Nongpynim.',
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          'Ei ban synshar junom duh?',
          'Jisu Khrist Nongpynim;',
          'Iano ngin iaieit, ianguh?',
          'Jisu Khrist Nongpynim.',
        ],
      },
      {
        id: 'verse-5',
        order: 6,
        type: 'verse',
        lines: [
          'Ei na byneng pat Un wan?',
          'Jisu Khrist Nongpynim;',
          'Ia ki briew ba Un ioh tan?',
          'Jisu Khrist Nongpynim.',
        ],
      },
    ],
  },
  {
    id: 'song-038',
    title: 'U Blei U Wad Ia Nga',
    metadata: {
      number: 38,
      language: 'khasi',
      author: 'H.L.',
      composer: 'S.S. 40',
      syllables: 'S.S. 40',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Jisu Nongpynim U wan sha pyrthei,',
          'Kha ha sem kulai ban shah i bein ei;',
          'O, kaba phylla, long burom iU Blei,',
          'Bu wad ia nga, ia nga!',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Jisu Nonggynim halor ka diengphna,',
          'Ban im u bynriew, U siew ka kuna,',
          'O, kaba phylla ba U leh kumta,',
          'Namar jong nga, jong nga!',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Jisu Nongpynim kumba mynhyndai,',
          'Haba nga iaid sakma na la U Trai;',
          'Khlem thait U wad, U khroh ia nga la jngai,',
          'U khot ia nga, ia nga!',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Jisu Nongpynim na bneng Un wan biang,',
          'Por ki nangjan, jingkular ki nang thiang;',
          'O! ngan sa iohi, na bneng Un hiar biang,',
          'Namar jong nga, jong nga!',
        ],
      },
    ],
  },
  {
    id: 'song-039',
    title: 'Ka Jinglong Briew U Khrist',
    metadata: {
      number: 39,
      language: 'khasi',
      author: 'H.L.',
      composer: 'The First Nowell',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Angel ki rwai jingrwai Khristmas nyngkong,',
          'Ha ki nongapblang ba sahmiet shabar shnong;',
          'Ha them Bethehem ba ki blang ki bam phlang,',
          'Hapdeng ka jingkhriat ba jur ka miet tlang.',
        ],
      },
      {
        id: 'chorus-1',
        order: 2,
        type: 'chorus',
        lines: ['Nowell, Nowell, Nowell, Nowell,', 'La kha ia U Syiem ki Israel.'],
      },
      {
        id: 'verse-2',
        order: 3,
        type: 'verse',
        lines: [
          'Ki peit, bad ia u khlur ki iohi,',
          'Ba u tyngshain sha mihngi, jngai na ki;',
          'Sha ka pyrthei u shat jingphyrnai,',
          'Bad miet bad sngi jingshai ba khraw u ai.',
        ],
      },
      {
        id: 'verse-3',
        order: 4,
        type: 'verse',
        lines: [
          'Da jingshai une u khlur ba maian,',
          'Lai ngut ki riewstad na ri ba jngai ki wan;',
          'Ban wad ia U Syiem ki la kut jingmut skhem,',
          'Bad ban bud ia u khlur kat haba ki shem.',
        ],
      },
      {
        id: 'verse-4',
        order: 5,
        type: 'verse',
        lines: [
          'Shaphang sepngi u khlur u la leit,',
          'Bad ha shnong Belhlehem u la sangeh beit;',
          'Hangta u la ieng bad u la neh syndon,',
          'Halor ka iingbasa ba U Jisu U don.',
        ],
      },
      {
        id: 'verse-5',
        order: 6,
        type: 'verse',
        lines: [
          'Ki rewstad hangta shapoh iing ki la rung,',
          'Ki dem khohsiew khrup ha khmat I Khunlung;',
          'Ki ai la jingainguh ba ki la taiar,',
          'Ka jingiwbih bad ka mirr bad ka ksiar.',
        ],
      },
      {
        id: 'verse-6',
        order: 7,
        type: 'verse',
        lines: [
          'To, ngi ruh da kawei ka mynsiem,',
          'Ngin iaroh ia U Trai U Syiem;',
          'U Trai Nongthaw ka bneng ka khyndew,',
          'Bad U Nongsiewspah ia u khunbynriew.',
        ],
      },
    ],
  },
  {
    id: 'song-040',
    title: 'Ka Khubor Ka Jingkmen',
    metadata: {
      number: 40,
      language: 'khasi',
      author: 'W.R.',
      composer: 'Noel (D.C.M.)',
      syllables: 'D.C.M.',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ka poi ha por shiteng synnia,',
          'Ka khubor ba sngewkmen;',
          'Ha suin ki angel ki iarwai,',
          'Da sur bang tam ka bneng.',
          '‘Jingsuk pyrthei, jingbha ki briew,’',
          'Ki risa baroh lang;',
          'Khubor kor tam ha neng ba riew,',
          'Ka hiar sha ka pyrthei.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka suin hapdeng jingdum ka miet,',
          'Ka dap da jingphyrnai.',
          'Ki angel la ki sner pynphriang,',
          'Ki hiar na ri jingshai.',
          'Ha ki lum bad ki them pyrthei,',
          'La khubor ki pynsngew,',
          'Jingaiei na ka khet U Blei,',
          'Shu bynriew ba la rem.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ka jingkordit jingtim ka pop,',
          'Ia pyrthei ki la ban;',
          'U khunbynriew ha lanot khop,',
          'U shah hajar ki snem.',
          'Mynta ka miet la wan jinglait;',
          'Sngap! jingpyrta na neng,',
          'To khmied shatei, to sngap ia ka,',
          'Ha lyngngoh shuh wat ieng.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Phi ba da jingkit khia la ban,',
          'Ki syngkai ruh la khein,',
          'Ba par shitom artet u lum,',
          'Ha pyrthei ngi khlem kein.',
          'To khmih ia ki sngi ba sngewbha,',
          'Da jingstet ki wan her;',
          'Jynjar khuslai baroh mynta,',
          'Kin wai kin jah lut phar.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Ki sngi jingsuk ba la pynbna,',
          'Ha ki arta mynbarim,',
          'Da shyntur nongiathuhlypa,',
          'Ha ngi mynta ki poi.',
          'Ynda jingsuk pyrthei synshar,',
          'Jingsuk Eden hyndai;',
          'Na sawdong jingiaroh kan sei,',
          'IU Jisu Trai ki trai.',
        ],
      },
    ],
  },
  {
    id: 'song-041',
    title: 'Khristan To Khie',
    metadata: {
      number: 41,
      language: 'khasi',
      author: 'W.R.',
      composer: 'Stockport (10.10.10.10.10.10.)',
      syllables: '10.10.10.10.10.10',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Khristan to khie, khublei ka sngi ba bha,',
          'Ha kaba Nongpynim pyrthei la kha;',
          'To ieng mynta ban ainguh ia U Trai,',
          'IU ba ki paitbah angel ki iarwai.',
          'Khubor jingkmen nyngkong ia u bynriew,',
          'BU Blei ha ka doh la kha na ka briew.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ki nongaplangbrot ha lum ki iohi,',
          'IU angel ba wallam khubor ha ki;',
          '‘Ha khmih nga wallam ka khubor ba bha,',
          'Ha phi mynta iU Nongpynim la kha,’',
          'La pyndep ka ktien jingkular U Blei,',
          'La kha iU Nongpynim jong ka pyrthei.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Kynsan na ki paid nongrwai jong ka bneng,',
          'La sawa jingrwai ba bang ka jingkmen;',
          'Ki rwai iaroh ia ka jingieit ba tam,',
          'Ka sur Haleluia ka sawa jam;',
          'Ha kiba jrong tam eh, burom iU Blei,',
          'Jingsuk bad jingsngewbha ha ka pyrthei.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ki nongaplangbrot kyrkieh ki ialeit,',
          'Ia ka jingphylla jong U Blei ban peit;',
          'Iu Joseph bad ka Theisotti ki shem,',
          'Bad Khunlung ha shyngoid ha Bethlehem;',
          'Ki pynbna ka khubor kylleng sawdong,',
          'Ka nam Nongpynim pynsawa nyngkong.',
        ],
      },
    ],
  },
  {
    id: 'song-042',
    title: 'Miet Bakhuid!',
    metadata: {
      number: 42,
      language: 'khasi',
      author: 'O.H.R. & H.L.',
      composer: 'Stillenacht (Irr.)',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Miet ba khuid! Miet ba jar jar!',
          'Dum tliw tliw, ka shai kdar;',
          'Tang hangtai ha kaba ki ap,',
          'Ia I Khunlung bla sop bla tap,',
          'Ba iohthiah suk kynjai,',
          'Ba iohthiah suh kynjai.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Miet ba khuid! Miet ba jar jar!',
          'Dum ka phet, ka shai phar;',
          'Nongapblang sngew angel ki rwai,',
          '“Haleluia! burom iU Trai”:',
          'Khrist Nongpynim la kha,',
          'Khrist Nongpynim la kha.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Miet ba khuid! Miet ba jai jai!',
          'Btin ko khlur, ai jingshai;',
          'Khmih ki riewstad na ri mihngi,',
          'Ki dem ki nguh iU Syiem jong ngi;',
          'Khrist Nongpynim la kha,',
          'Khrist Nongpynim la kha.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Miet ba khuid! Miet ba jai jai!',
          'Khlur phylla, ai jingshai;',
          'Lem bad ki angel ngin iarwai,',
          '“Haleluia! iU Syiem U Trai”:',
          'Khrist Nongpynim la kha,',
          'Khrist Nongpynim la kha.',
        ],
      },
    ],
  },
  {
    id: 'song-043',
    title: 'Ka Jingrwai Khristmas',
    metadata: {
      number: 43,
      language: 'khasi',
      author: 'H.J.',
      composer: 'Baban Mair',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ha sngap ka khubor kaba bha,',
          'Ha khymih ka jingshai ba ba;',
          'Ia! ngin ialeit ban mane dem,',
          'IU Khun U Blei ha Bethlehem,',
          'Haleluia! Haleluia!',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ki lai ngut ki riewstad ba shlur,',
          'Ki bud ka jingïalam u khlur,',
          'Ki la sngewhun haba ki shem,',
          `Ї'U Jisu Khrist ha Bethlehem.,`,
          'Haleluia! Haleluia!',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Mynmiet ha u lum la pynbna,',
          'Ki nongaplangbrot ruh la phah',
          `Ban wad ï'U Khunlung Uba tlem,`,
          'Ha shyngoid mrad ha Bethlehem.',
          'Haleluïa! Haleluïa!',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Ka jingiwbih ka ksiar ruh,',
          'Ka mirr ngim don ban ai ha U,',
          'LЇa lade ngin ïa ai shitrhem.,',
          `Ї'U Syiem jingsuk ha Bethlehem.,`,
          'Haleluïa! Haleluïa!',
        ],
      },
    ],
  },
  {
    id: 'song-044',
    title: 'To Wan Sha Baeng, Baeng',
    metadata: {
      number: 44,
      language: 'khasi',
      author: 'P.G.',
      composer: 'S.S.35 (E.S. Elliott)',
      syllables: 'S.S.35',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Me la ieh la ka khet,',
          'Bad ka Pansngiat Syiem,',
          'Mynba Me wan ban wad ia nga;',
          'Ha ka shnong Bethlehem,',
          'Me la thiah ha sem,',
          'Bym don jaka ia Me hangta:',
          'To wan sha dohnud, Trai Jisu,',
          'Don jaka ha dohnud jong nga.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ka suin bneng ka phyrnai,',
          'Da angel ba rwai,',
          'Ban pynbna khubor bneng ba hha;',
          'Ba U Khun U Blei,',
          'U wan sha pyrthei,',
          'Ha jingkhuid, jingsngewrit shisha;',
          'To wan sha dohnud, Trai Jisu,',
          'Don jaka ha dohnud jong nga.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ki myrsiang ha ki krem,',
          'Ki sim bneng ki dem,',
          'Ha syrngiew jong dieng ha khlaw;',
          'Me mem don jaka rieh,',
          'Ba men buh ka khlieh,',
          'Ha ri shyiap duriaw Galilee:',
          'To wan sha dohnud, Trai Jisu,',
          'Don jaka ha dohnud jong nga.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'Me la wan, Ah Trai,',
          'La jingim ban ai,',
          'Ban siewspah iu nongpop ba pli;',
          'Me la phong pansngiat shiah,',
          'Namar jong nga Me shah,',
          'Ka diengphna ha Lum Kalbari:',
          'To wan sha dohnud, Trai Jisu,',
          'Bor diengphna long ka hok ia nga.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'Ynda riew turoi bneng,',
          'Bad ki angel neng,',
          'Kin wan paw ha burom jong Me;',
          'Khot ia nga Trai ba bha,',
          'Ong, ‘Dang don jaka’,',
          'Don jaka ha krung jong Me ia nga:',
          'Ngan shad da jingkmen, Trai Jisu,',
          'Ynda Men wan shaw ia nga.',
        ],
      },
    ],
  },
  {
    id: 'song-045',
    title: 'Ko Miet Bakhuid',
    metadata: {
      number: 45,
      language: 'khasi',
      author: 'B.C.L.',
      composer: 'Londonderry Air (C.W.236)',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ko Miet Bakhuid, ki khlur khrik ki tyngshain ha pha,',
          'Dei ka miet tlang haba iU Trai la kha,',
          'Pyrthei ka thiah lyngngai ha jingkhum jong ka pop,',
          'U wan ban pynim iu briew na jingjot.',
          'Jingkyrmen skhem, mynsiem ba swai ka ioh ban mad,',
          'Hangtai ka mih ka step ba itynnad.',
          'Ha sngap, don ka khubor ba angel ki pynbna,',
          'Ko Miet Bakhuid, shaphang jong pha junom ngan rwai.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Khmih Jingshai na Seion ka shat phyrnai sngur bha,',
          'BU Sngi ka Hok, la wan ban pynthaba,',
          'Da jingpynim ba khraw bad jingshai bneng ba dap,',
          'Na jingiap ba triem ia ngi ban pyllait;',
          'U Syiem ki syiem bla thiah ha shyngoid sem kulai,',
          'Ha ki jingeh, U long U Lok jong ngi,',
          'Na ki Jingkit ka pop ia ngi Un pyllait phar,',
          'Ale, Ko lok baroh ngin nguh iU Trai jong ngi.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Jingsuk bneng U iehnoh ban shim ka jinglong rit;',
          'Jingieit phylla bad jingaiei ba dap;',
          'Namar jong ngi U shah ki shitom bad kordit,',
          'Jinglong ba tlem ha ngi la wan pynpaw,',
          'U Nongpynim ba khraw, la wan ha ngi mynta,',
          'Ki riewkhuid ruh ia U ki iaroh jam,',
          'To ngin ai la dohnud baroh hU Khrist U Trai,',
          'Ban long bad U haduh ba jingim hi kan wai.',
        ],
      },
    ],
  },
  {
    id: 'song-046',
    title: 'Ka Jingkha IU Nongpynim',
    metadata: {
      number: 46,
      language: 'khasi',
      author: 'B.C.L.',
      composer: 'Christmas Morn (76.76.D.) (C.H.363)',
      syllables: '76.76.D',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'La mih ka step ba phyrnai,',
          'Ba dap jingkmen suda;',
          'Jingthaw baroh ki ia rwai,',
          'IU Nongpynim la kha.',
          'U Khlur ha neng u tyngshain,',
          'Halor jingdum ka miet;',
          'Paidbah angel ki ia rwai,',
          'Pyrthei ka sngew kyndit.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ki Nongaplangbrot ha lum,',
          'Ki dap da jinglyngngoh;',
          'Ban sngap khubor bla pynbna,',
          'IU Blei ki rwai iaroh.',
          'Mynta la wan jingpynim,',
          'Bad jingsuk ha pyrthei;',
          'Ha kylleng sawdong pynphriang,',
          'Ka jingieit bah U Blei.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'U Trai Nongpynim la wan,',
          'Jingsuk bneng U iehnoh;',
          'Um khein ki shitom ba ban,',
          'Namar jong ngi baroh.',
          'U la wan U Syiem jingsuk,',
          'Khuslai jong ngi ban bah;',
          'Ban pynim nongpop ba duk,',
          'Bad ngi U wan ban sah.',
        ],
      },
    ],
  },
  {
    id: 'song-047',
    title: 'Nga Ieit Ia Me Jisu',
    metadata: {
      number: 47,
      language: 'khasi',
      author: 'W.R.',
      composer: 'Cradlesong (11.11.11.11.)',
      syllables: '11.11.11.11',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Hapoh ka shyngoid, ba ym ioh iingbasa,',
          'Ia I Khunlung Jisu la pynthiah lyngktop;',
          'Ki khlur baroh shi bneng ki peit lut shata,',
          'HI Khunlung Jisu lyngngai ha u langiap.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ki jingri ki pah bad Khunlung I kyndit,',
          'Hynrei kum kiwei pat ki khunlung im iam;',
          'Nga ieit ia Me, Jisu, halor jong nga peit,',
          'To thiah lang bad nga, Trai haduh ban da shai.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Hajan jong nga, Trai Jisu, nga kyrpad shong,',
          'Shilynter jingim, bad jingieit ruh to ai;',
          'Ki khynnah rit baroh kyrkhu, ban pynlong,',
          'Ba bit ia ka bneng, ban shong bad Me khlem wai.',
        ],
      },
    ],
  },
  {
    id: 'song-048',
    title: 'Khristan To Shadkmen',
    metadata: {
      number: 48,
      language: 'khasi',
      author: 'R.K.',
      composer: 'C.P. 15',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ko khristan to shadkmen,',
          'Iaroh da jingkyrmen;',
          'Sngap khubor ba wan pyrta,',
          'Sngap, sngap:',
          'Jisu Khrist la kha mynta,',
          'Baroh ia U ki dem syiem,',
          'Hapoh shyngoid ka Bethlehem,',
          'Khrist, la kha mynta; Khrist la kha mynta.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Ko khristan to iaroh,',
          'Da ka dohnud baroh;',
          'Trai Jisu la wan long briew,',
          'Sngap, sngap:',
          'Jisu Khrist, la kha mynta,',
          'Bneng bad khyndew ki pynpaw,',
          'Shaphang U Trai U Syiem Bakhraw,',
          'Khrist, la kha mynta; Khrist la kha mynta.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ko khristan, leh sngewbha,',
          'IU Syiem jong ngi la kha;',
          'Angel bneng ruh ki ia rwai,',
          'Sngap, sngap:',
          'Jisu Khrist, la kha mynta,',
          'Da ki sur babang bathiang,',
          'Sawdong pyrthei ki ia pynphriang,',
          'Khrist, la kha mynta; Khrist la kha mynta.',
        ],
      },
    ],
  },
  {
    id: 'song-049',
    title: 'Ka Jingieit U Blei',
    metadata: {
      number: 49,
      language: 'khasi',
      author: 'H.R.',
      composer: 'S.S. 511',
      syllables: 'Irregular',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'Ia ngin ianguh, iariwai lang,',
          'Ka jingieit, jingieit U Blei;',
          'Ki khlur byneng ki iaroh lang,',
          'Ka jingieit, jingieit U Blei;',
          'Mynsiem baroh, na sniew to khie,',
          'Ban tem duitara mynta mih,',
          'Iariwai lang la jaka rieh,',
          'Ka jingieit, jingieit U Blei.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'To leit ialap sha kut pyrthei,',
          'Ka jingieit, jingieit U Blei;',
          'Ba ha U Khrist ban im la dei,',
          'Ka jingieit, jingieit U Blei;',
          'Ka snam ka sait ka ram jong nga,',
          'Mynsiem ba pop, U pynkhuid bha,',
          'Bad mynta kymen eh nga lah,',
          'Ka jingieit, jingieit U Blei.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ah, ka jingsuk ngi shem hangne,',
          'Ka jingieit, jingieit U Blei;',
          'Ki kular jong U ki pynneh,',
          'Ka jingieit, jingieit U Blei,',
          'Ka sngi ba shai, ka stieh ba da,',
          'Mynmiet ruh jan ia nga U sah,',
          'Bad baroh shi rta U iai kah,',
          'Ka jingieit, jingieit U Blei.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'La swai ka met, la noh mynsiem,',
          'Ah jingieit, jingieit U Blei;',
          'U Khrist na jingiap Un pynim,',
          'Ah jingieit, jingieit U Blei;',
          'La at ka Jordan ngan ym tieng,',
          'Ia nga U Jisu Un sa khring,',
          'Ka khlieh Un rah, ngan poi sha iing,',
          'Ah jingieit, jingieit U Blei.',
        ],
      },
    ],
  },
  {
    id: 'song-050',
    title: 'Ka Jutang Jingaiei',
    metadata: {
      number: 50,
      language: 'khasi',
      composer: 'Free Church Hymn 2 (11.11.11.11.)',
      syllables: '11.11.11.11',
    },
    paragraphs: [
      {
        id: 'verse-1',
        order: 1,
        type: 'verse',
        lines: [
          'U Trai U la ieit ia nga la mynslem,',
          'La pynlong da U ia ka jutang ba skhem;',
          'Ban isnei ia nga u nongpop uba khraw,',
          'Bad kata mynshuwa ka pyrthei la thaw.',
        ],
      },
      {
        id: 'verse-2',
        order: 2,
        type: 'verse',
        lines: [
          'Da ieit bymjukut la ieit ia nga,',
          'Jingnguh ia U junom bla kynmaw ia nga;',
          'Ka kyrteng ka jong nga la thoh ruh ha neng,',
          'Ha kitab kj riewkhuid, ha Seion byneng.',
        ],
      },
      {
        id: 'verse-3',
        order: 3,
        type: 'verse',
        lines: [
          'Ma nga te nga ryngkang ka hukum U Blei,',
          'Ia U nga la len ruh ha khymat pyrtheieng;',
          'Uba mawbah ba hawa, Uba mawbah,',
          'Ka ba la ynda kanha.',
        ],
      },
      {
        id: 'verse-4',
        order: 4,
        type: 'verse',
        lines: [
          'La shem ia U ba ha Blei, Hyongmen ba ngi,',
          'U Khun bla kha warwari U Blei ha ha khlieh;',
          'Baing, U baeng iap run la Lum ba eng,',
          'Shaneng baengi ba ba ng ba ngi.',
        ],
      },
      {
        id: 'verse-5',
        order: 5,
        type: 'verse',
        lines: [
          'La pop bad la jot ruh, Um bret ïa nga shuh,',
          'Un map bad Un kyrshan, Un kyrkhu ma U,',
          'Un lam ïa nga beit sha ka jingsuk byneng,',
          'Hosanna ïa Une, ngin ïaroh ha neng.',
        ],
      },
    ],
  },
];
