name: EAS Trigger preview deployment

on:
  push:
    # Deploy only from your protected branch

jobs:
  notify_start:
    name: Notify preview deployment start
    type: slack
    params:
      webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
      message: |
        🚀 UAT deployment started {{ github.event.after }}
        Branch: Master
        App: ${{ github.event.repository.name }}
        Platform: android
        User: ${{ github.event.pusher.name }}
        Commit: ${{ github.event.head_commit.message }}
        Commit URL: ${{ github.event.head_commit.url }}

  check_version_change:
    # 1) Check if app version changed by parsing app.json/app.config.js
    #    Extracts expo.version and android.versionCode to detect version bumps
    name: Check app version change
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Get current + previous commit
      - id: version_check
        run: |
          # Extract current app version and versionCode from app.json/app.config.js
          if [ -f app.json ]; then
            APP_VERSION=$(jq -r '.expo.version // empty' app.json)
            VERSION_CODE=$(jq -r '.expo.android.versionCode // empty' app.json)
          elif [ -f app.config.js ]; then
            APP_VERSION=$(node -pe "require('./app.config.js')({}).expo.version")
            VERSION_CODE=$(node -pe "require('./app.config.js')({}).expo.android?.versionCode")
          fi

          # Get previous commit's versions
          git checkout HEAD~1
          if [ -f app.json ]; then
            PREV_APP_VERSION=$(jq -r '.expo.version // empty' app.json)
            PREV_VERSION_CODE=$(jq -r '.expo.android.versionCode // empty' app.json)
          elif [ -f app.config.js ]; then
            PREV_APP_VERSION=$(node -pe "require('./app.config.js')({}).expo.version")
            PREV_VERSION_CODE=$(node -pe "require('./app.config.js')({}).expo.android?.versionCode")
          fi

          # Check if either changed (version bump detected)
          if [ "$APP_VERSION" != "$PREV_APP_VERSION" ] || [ "$VERSION_CODE" != "$PREV_VERSION_CODE" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "current_version=$APP_VERSION" >> $GITHUB_OUTPUT
            echo "current_version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

          # Reset to current commit
          git checkout HEAD@{1}
        shell: bash

  fingerprint:
    # 2) Generate native fingerprint for current commit
    #    This captures native deps, config, etc. so we know
    #    whether a new binary is required or JS-only update is enough.
    name: Fingerprint
    type: fingerprint
    environment: preview
    needs: [notify_start, check_version_change]

  get_android_build:
    # 3) Check for existing Android build (SKIPPED if version changed)
    #    that matches this fingerprint + profile.
    name: Check for existing android build
    needs: [fingerprint, check_version_change]
    if: ${{ needs.check_version_change.outputs.version_changed != 'true' }}
    type: get_build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: preview

  build_android:
    # 4A) Force new build if version changed OR no compatible build exists
    #     This creates your "mandatory update candidate" (PTA).
    name: Build Android
    needs: [fingerprint, check_version_change, get_android_build]
    if: ${{ needs.check_version_change.outputs.version_changed == 'true' || !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: preview

  publish_android_update:
    # 4B) Compatible build exists AND version unchanged -> publish OTA update
    #     to the preview branch for that existing binary.
    name: Publish Android update
    needs: [fingerprint, check_version_change, get_android_build]
    if: ${{ needs.check_version_change.outputs.version_changed != 'true' && needs.get_android_build.outputs.build_id }}
    type: update
    params:
      branch: preview
      platform: android

  notify_failure:
    name: Notify preview failure
    after:
      [fingerprint, check_version_change, get_android_build, build_android, publish_android_update]
    if: ${{ failure() }}
    type: slack
    params:
      webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
      message: |
        ❌ UAT deployment failed
        Version changed: ${{ needs.check_version_change.outputs.version_changed }}
        Fingerprint status: ${{ needs.fingerprint.status }}
        Build ID check: ${{ needs.get_android_build.outputs.build_id }}
        Build status: ${{ needs.build_android.status }}
        Update status: ${{ needs.publish_android_update.status }}

  notify_success:
    name: Notify preview success
    needs:
      [check_version_change, fingerprint, get_android_build, build_android, publish_android_update]
    if: ${{ success() }}
    type: slack
    params:
      webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
      message: |
        ✅ UAT deployment completed
        Version: ${{ needs.check_version_change.outputs.current_version || 'unchanged' }} (vCode: ${{ needs.check_version_change.outputs.current_version_code || 'unchanged' }})
        Action taken: ${{ needs.build_android.result == 'success' && 'NEW BUILD' || 'OTA UPDATE' }}
        Used existing build: ${{ needs.get_android_build.outputs.build_id || 'none' }}
        New build ID: ${{ needs.build_android.outputs.build_id || 'none' }}
        Branch: preview
        Platform: android [web:41][web:40]
