name: Kot-Jingrwai Prod Deployment

# on:
  # workflow_dispatch:
  # push:
  #   branches: [master]
  #   paths: ["src/apps/mobile/**", "packages/**"] # Only runs if files here change

jobs:
  call-build:
    uses: ./.github/workflows/_expo_build.yml
    with:
      app_name: "kot-jingrwai"
      app_path: "src/apps/mobile"
    secrets: inherit # Pass all repo secrets to the template
